version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy # Запускаем только после того, как БД будет готова
    environment:
      # Параметры для подключения к БД (можно вынести в .env файл)
      - DATABASE_URL=postgres://user:password@db:5432/shanraqdb?sslmode=disable
      - PORT=8080

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shanraqdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d # Автоматически выполнит наш SQL-скрипт при первом запуске
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shanraqdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: