version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shanraq
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SHANRAQ_DATABASE_URL: postgres://postgres:postgres@db:5432/shanraq?sslmode=disable
      SHANRAQ_ENVIRONMENT: docker
      SHANRAQ_AUTH_TOKEN_SECRET: "change-me-now"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db-data:
