"""Beginner-first teaching material for the Cloud & DevOps course.

The short technical facts live in generate_cloud_devops.py.  This module adds
the bridge a first-time learner needs: a familiar image, a compact support
signal, a small vocabulary, an explanation of the experiment, and a tempting
wrong statement to diagnose.  The structure follows the useful parts of
Shatalov's system in an asynchronous course: whole-topic explanation, support
signals, repeated recall, frequent feedback, and an open path to retry.
"""


def tri(ru, kz, en):
    return {"ru": ru, "kz": kz, "en": en}


def term(name, ru, kz, en):
    parts = name.split(" · ")
    localized_name = tri(*parts) if len(parts) == 3 else tri(name, name, name)
    return {"name": localized_name, "text": tri(ru, kz, en)}


def pack(signal, analogy, words, command, mistake, nodes):
    return {
        "signal": tri(*signal),
        "analogy": tri(*analogy),
        "terms": words,
        "command": tri(*command),
        "mistake": tri(*mistake),
        "nodes": {"ru": nodes[0], "kz": nodes[1], "en": nodes[2]},
    }


PACKS = {
    "01-why-now": pack(
        ("🏭 железо → ☁️ ресурс → 🔁 изменение → 👀 наблюдение → 🛟 восстановление",
         "🏭 жабдық → ☁️ ресурс → 🔁 өзгеріс → 👀 бақылау → 🛟 қалпына келтіру",
         "🏭 hardware → ☁️ resource → 🔁 change → 👀 observe → 🛟 recover"),
        ("Представьте современный отель. Здание, электричество и лифты похожи на дата-центр. Возможность снять номер через приложение похожа на облако. А работа команды, которая заселяет гостей, замечает поломку и возвращает лифт в строй, похожа на эксплуатацию сервиса. DevOps связывает тех, кто меняет услугу, с теми, кто отвечает за её работу.",
         "Заманауи қонақүйді елестетіңіз. Ғимарат, электр және лифт — дата-орталық тәрізді. Қосымша арқылы бөлме алу — бұлтқа ұқсайды. Қонақты орналастырып, ақауды байқап, лифтті қайта іске қосатын топ сервис эксплуатациясына ұқсайды. DevOps өзгеріс жасаған адам мен оның жұмысына жауапты адамды байланыстырады.",
         "Imagine a modern hotel. The building, power, and lifts resemble a data centre. Booking a room through an app resembles cloud capacity. The team that checks guests in, spots a broken lift, and restores it resembles service operations. DevOps connects people who change a service with people responsible for running it."),
        [
            term("Дата-центр · Дата-орталық · Data centre", "Здание с серверами, сетью, питанием и охлаждением.", "Сервер, желі, қуат және салқындату орналасқан ғимарат.", "A building containing servers, networking, power, and cooling."),
            term("Облако · Бұлт · Cloud", "Способ заказывать вычислительные ресурсы через программу или панель, не покупая каждый сервер самому.", "Әр серверді сатып алмай, есептеу ресурсын бағдарлама не панель арқылы тапсыру тәсілі.", "A way to request computing resources through software or a control panel without buying every server."),
            term("DevOps", "Практика совместной работы, автоматизации и быстрой обратной связи при выпуске изменений.", "Өзгерісті шығару кезіндегі ортақ жұмыс, автоматтандыру және жылдам кері байланыс тәжірибесі.", "A practice of shared work, automation, and fast feedback when releasing changes."),
            term("SRE", "Подход к надёжности, где цели сервиса измеряются, а повторяемая ручная работа автоматизируется.", "Сервис мақсаты өлшеніп, қайталанатын қол жұмысы автоматтандырылатын сенімділік тәсілі.", "A reliability approach that measures service goals and automates repeated manual work."),
        ],
        ("Две строки `printf` ничего не устанавливают. Они дают первую карту курса. Прочитайте цепочку слева направо, затем закройте её рукой и восстановите по памяти.",
         "Екі `printf` ештеңе орнатпайды. Олар курстың алғашқы картасын береді. Тізбекті солдан оңға оқып, кейін жауып, жатқа қалпына келтіріңіз.",
         "The two `printf` lines install nothing. They provide the first course map. Read the chain left to right, cover it, and rebuild it from memory."),
        ("Ошибка: «DevOps — это администратор, который один отвечает за Docker, серверы и любой сбой». Исправление: ответственность разделяет команда, а инструменты лишь поддерживают процесс.",
         "Қате: «DevOps — Docker, сервер және барлық ақауға жалғыз жауапты әкімші». Дұрысы: жауапкершілікті топ бөліседі, құралдар үрдісті ғана қолдайды.",
         "Mistake: “DevOps is an administrator solely responsible for Docker, servers, and every outage.” Correction: the team shares responsibility; tools support the process."),
        (["железо", "облако", "изменение", "доказательство"], ["жабдық", "бұлт", "өзгеріс", "дәлел"], ["hardware", "cloud", "change", "evidence"]),
    ),
    "02-service-map": pack(
        ("человек → адрес → сервис → ответ; жив ≠ готов ≠ полезен",
         "адам → мекенжай → сервис → жауап; тірі ≠ дайын ≠ пайдалы",
         "person → address → service → response; alive ≠ ready ≠ useful"),
        ("Кафе может быть открыто, но кухня ещё не готова принимать заказ: повар пришёл, а печь прогревается. Вывеска «открыто» похожа на проверку жизни процесса, готовая кухня — на readiness, а выданное блюдо — на реальный пользовательский результат. Одной зелёной лампы недостаточно.",
         "Кафе ашық болғанымен, асүй тапсырысқа дайын болмауы мүмкін: аспаз келді, пеш қызуда. «Ашық» белгісі үдерістің тірі екенін, дайын асүй readiness-ті, берілген тағам пайдаланушы нәтижесін еске салады. Бір жасыл шам жеткіліксіз.",
         "A café may be open while its kitchen is not ready for orders: the cook has arrived but the oven is warming. The open sign resembles process health, the ready kitchen resembles readiness, and a served meal is the user outcome. One green light is insufficient."),
        [
            term("Сервис · Сервис · Service", "Программа, которая выполняет полезную работу и доступна через понятный вход.", "Пайдалы жұмыс істеп, белгілі бір кіріс арқылы қолжетімді бағдарлама.", "A program that does useful work and is reachable through a defined entry point."),
            term("Endpoint", "Конкретный адрес внутри сервиса, например `/healthz`.", "Сервис ішіндегі нақты мекенжай, мысалы `/healthz`.", "A specific address within a service, such as `/healthz`."),
            term("Health", "Признак того, что процесс существует и способен ответить.", "Үдеріс бар және жауап бере алатынының белгісі.", "Evidence that the process exists and can respond."),
            term("Readiness", "Признак готовности принимать настоящий пользовательский трафик.", "Нақты пайдаланушы трафигін қабылдауға дайындық белгісі.", "Evidence that the service is ready for real user traffic."),
        ],
        ("Сначала тесты проверяют известные правила. Затем сервис запускается в фоне, а его номер сохраняется в `pid`. `trap` обещает остановить процесс даже при раннем выходе. `curl` играет роль посетителя и спрашивает два разных адреса.",
         "Алдымен тесттер белгілі ережелерді тексереді. Сервис фонда іске қосылып, нөмірі `pid` ішінде сақталады. `trap` ерте шығуда да үдерісті тоқтатуға уәде береді. `curl` келуші болып, екі мекенжайды сұрайды.",
         "Tests first verify known rules. The service then starts in the background and its number is stored in `pid`. `trap` promises to stop it even after an early exit. `curl` acts as a visitor and asks two different addresses."),
        ("Ошибка: «Если `/healthz` вернул 200, данные точно сохраняются и весь сервис полезен». Исправление: health доказывает только узкое условие, указанное в его контракте.",
         "Қате: «`/healthz` 200 берсе, дерек міндетті түрде сақталып, сервис толық пайдалы». Дұрысы: health өз келісіміндегі тар шартты ғана дәлелдейді.",
         "Mistake: “If `/healthz` returns 200, data is certainly durable and the whole service is useful.” Correction: health proves only its narrow contract."),
        (["запуск", "жив", "готов", "полезен"], ["іске қосу", "тірі", "дайын", "пайдалы"], ["start", "alive", "ready", "useful"]),
    ),
    "03-terminal-git": pack(
        ("📂 где я? → 📝 что изменено? → 📸 какая версия? → ✅ можно повторить",
         "📂 қайдамын? → 📝 не өзгерді? → 📸 қай нұсқа? → ✅ қайталауға болады",
         "📂 where? → 📝 what changed? → 📸 which version? → ✅ repeatable"),
        ("Терминал похож на разговор с очень буквальным помощником: он не угадывает, в какой комнате вы хотели работать. Git похож на журнал мастерской: записывает контрольные состояния и позволяет увидеть, что поменялось между ними. Перед опасной командой сначала спросите «где я?» и «что изменено?».",
         "Терминал өте тура түсінетін көмекшімен сөйлесуге ұқсайды: ол қай бөлмеде жұмыс істегіңіз келгенін болжамайды. Git шеберхана журналы секілді: бақылау күйлерін жазып, айырманы көрсетеді. Қауіпті пәрмен алдында «қайдамын?» және «не өзгерді?» деп сұраңыз.",
         "A terminal is like speaking to a very literal assistant: it will not guess which room you intended to work in. Git resembles a workshop log: it records checkpoints and shows what changed. Before a risky command, ask “where am I?” and “what changed?”"),
        [
            term("Терминал · Терминал · Terminal", "Окно для текстового общения с операционной системой.", "Операциялық жүйемен мәтін арқылы сөйлесетін терезе.", "A window for text-based interaction with the operating system."),
            term("Shell", "Программа, которая читает команду и запускает другие программы.", "Пәрменді оқып, басқа бағдарламаларды іске қосатын бағдарлама.", "A program that reads commands and starts other programs."),
            term("Репозиторий · Репозиторий · Repository", "Каталог проекта вместе с историей Git.", "Жоба қалтасы және оның Git тарихы.", "A project directory together with its Git history."),
            term("Commit и SHA", "Сохранённая точка истории и её уникальный короткий идентификатор.", "Сақталған тарих нүктесі және оның бірегей қысқа идентификаторы.", "A saved history point and its unique short identifier."),
        ],
        ("`pwd` печатает текущий каталог. `status` показывает незаписанные изменения, `diff --check` ищет некоторые ошибки оформления, `rev-parse` называет точную версию, а `log` добавляет дату и смысл последнего commit.",
         "`pwd` ағымдағы қалтаны көрсетеді. `status` жазылмаған өзгерісті, `diff --check` безендіру қатесін, `rev-parse` нақты нұсқаны, `log` соңғы commit күні мен мағынасын көрсетеді.",
         "`pwd` prints the current directory. `status` shows unrecorded changes, `diff --check` finds some formatting errors, `rev-parse` identifies the exact version, and `log` adds the date and meaning of the latest commit."),
        ("Ошибка: «Git автоматически понимает, какое изменение хорошее, и всегда безопасно отменяет всё». Исправление: Git хранит историю файлов; смысл и безопасный способ возврата выбирает человек.",
         "Қате: «Git қай өзгеріс жақсы екенін өзі түсініп, бәрін әрқашан қауіпсіз қайтарады». Дұрысы: Git файл тарихын сақтайды; мағына мен қайтару тәсілін адам таңдайды.",
         "Mistake: “Git knows which change is good and can always undo everything safely.” Correction: Git stores file history; a person chooses meaning and a safe recovery method."),
        (["каталог", "изменение", "commit", "SHA"], ["қалта", "өзгеріс", "commit", "SHA"], ["directory", "change", "commit", "SHA"]),
    ),
    "04-linux-access": pack(
        ("👤 владелец | 👥 группа | 🌍 остальные × читать/писать/выполнять",
         "👤 ие | 👥 топ | 🌍 басқалар × оқу/жазу/орындау",
         "👤 owner | 👥 group | 🌍 others × read/write/execute"),
        ("В мастерской у ключей разные права: один открывает склад, другой только комнату отдыха. Давать каждому генеральный ключ удобно до первой потери. Linux так же разделяет владельца, группу и остальных, а root — генеральный ключ, которым не работают постоянно.",
         "Шеберхана кілттерінің құқығы бөлек: бірі қойманы, бірі демалыс бөлмесін ғана ашады. Бәріне бас кілт беру алғашқы жоғалтуға дейін ыңғайлы. Linux ие, топ және басқаларды осылай бөледі, ал root — үнемі қолданылмайтын бас кілт.",
         "Workshop keys have different rights: one opens storage and another only the break room. Giving everyone a master key is convenient until one is lost. Linux similarly separates owner, group, and others; root is a master key that should not be used continuously."),
        [
            term("Пользователь · Пайдаланушы · User", "Идентичность, от имени которой выполняется процесс.", "Үдеріс атынан орындалатын сәйкестік.", "The identity under which a process runs."),
            term("root", "Суперпользователь почти без обычных ограничений доступа.", "Қалыпты шектеуі аз суперпайдаланушы.", "The superuser with very few ordinary access restrictions."),
            term("Права · Құқық · Permissions", "Правила чтения, записи и выполнения для трёх групп людей.", "Үш адам тобына арналған оқу, жазу және орындау ережесі.", "Read, write, and execute rules for three groups of identities."),
            term("640", "Владелец читает и пишет; группа читает; остальные ничего не могут.", "Ие оқып-жазады; топ оқиды; басқаларға рұқсат жоқ.", "Owner reads and writes; group reads; others have no access."),
        ],
        ("`id` называет вашу текущую идентичность. `umask` показывает ограничения по умолчанию. Затем создаётся учебный файл, `chmod 640` задаёт права, а `ls -l` позволяет расшифровать результат, а не поверить команде на слово.",
         "`id` ағымдағы сәйкестікті атайды. `umask` әдепкі шектеуді көрсетеді. Оқу файлы жасалып, `chmod 640` құқық береді, `ls -l` нәтижені тексереді.",
         "`id` names your current identity. `umask` shows default restrictions. A learning file is created, `chmod 640` assigns rights, and `ls -l` lets you decode the result rather than trusting the command."),
        ("Ошибка: «Запуск от root исправляет проблему прав». Исправление: он скрывает неверную настройку и увеличивает последствия взлома или ошибки.",
         "Қате: «root атынан іске қосу құқық мәселесін шешеді». Дұрысы: ол қате баптауды жасырып, бұзу не қате салдарын үлкейтеді.",
         "Mistake: “Running as root fixes permission problems.” Correction: it hides bad configuration and increases the impact of compromise or error."),
        (["кто", "что", "какое действие", "минимум прав"], ["кім", "не", "қай әрекет", "ең аз құқық"], ["who", "what", "which action", "least privilege"]),
    ),
    "05-processes-logs": pack(
        ("программа + запуск = процесс(PID); TERM → завершиться; журнал → что было",
         "бағдарлама + іске қосу = үдеріс(PID); TERM → аяқталу; журнал → не болды",
         "program + start = process(PID); TERM → stop; log → what happened"),
        ("Нотный текст ещё не музыка: музыка появляется, когда исполнитель начинает играть. Так же файл программы превращается в процесс после запуска. PID — номер исполнителя на сцене, сигнал — просьба дирижёра, а журнал — запись того, что происходило.",
         "Нота әлі музыка емес: орындаушы ойнағанда музыка пайда болады. Бағдарлама файлы да іске қосылғанда үдеріске айналады. PID — сахнадағы орындаушы нөмірі, сигнал — дирижер өтініші, журнал — болған оқиға жазбасы.",
         "Sheet music is not yet music: music appears when a performer starts playing. A program file similarly becomes a process when launched. A PID is the performer's stage number, a signal is the conductor's request, and a log records what happened."),
        [
            term("Процесс · Үдеріс · Process", "Запущенный экземпляр программы с памятью и состоянием.", "Жады мен күйі бар іске қосылған бағдарлама данасы.", "A running instance of a program with memory and state."),
            term("PID", "Числовой идентификатор конкретного процесса.", "Нақты үдерістің сандық идентификаторы.", "The numeric identifier of a specific process."),
            term("SIGTERM", "Вежливая просьба процессу завершиться и убрать за собой.", "Үдеріске аяқталып, күйін реттеуге берілген сыпайы өтініш.", "A polite request for a process to shut down and clean up."),
            term("Лог · Журнал · Log", "Запись событий с временем и контекстом для диагностики.", "Диагностикаға арналған уақыт пен мәнмәтіні бар оқиға жазбасы.", "A time-stamped event record with context for diagnosis."),
        ],
        ("Сервис запускается в фоне, а его PID сохраняется. `ps` доказывает существование именно этого процесса. `kill -TERM` посылает просьбу завершиться, `wait` ждёт результата, `tail` показывает последние события журнала.",
         "Сервис фонда іске қосылып, PID сақталады. `ps` нақты үдерістің барын дәлелдейді. `kill -TERM` аяқталу өтінішін жібереді, `wait` күтеді, `tail` соңғы журнал оқиғасын көрсетеді.",
         "The service starts in the background and its PID is saved. `ps` proves that exact process exists. `kill -TERM` asks it to stop, `wait` collects the result, and `tail` shows the last log events."),
        ("Ошибка: «SIGKILL — более надёжный способ обычной остановки». Исправление: он не оставляет приложению времени сохранить данные и закрыть работу; это аварийная мера.",
         "Қате: «SIGKILL — қалыпты тоқтатудың сенімді жолы». Дұрысы: ол деректі сақтап, жұмысты жабуға уақыт бермейді; бұл апаттық шара.",
         "Mistake: “SIGKILL is a more reliable normal shutdown.” Correction: it gives the application no time to save data or finish work; it is an emergency measure."),
        (["файл", "процесс", "сигнал", "журнал"], ["файл", "үдеріс", "сигнал", "журнал"], ["file", "process", "signal", "log"]),
    ),
    "06-networks-dns-http": pack(
        ("имя → DNS → IP → TCP:порт → TLS → HTTP → ответ",
         "атау → DNS → IP → TCP:порт → TLS → HTTP → жауап",
         "name → DNS → IP → TCP:port → TLS → HTTP → response"),
        ("Представьте большой деловой центр. Доменное имя — знакомое название организации. DNS — справочная, которая находит адрес здания. IP — адрес здания в сети. Порт — номер нужной приёмной внутри здания. TCP проверяет, можно ли установить разговор с этой приёмной. TLS сверяет удостоверение собеседника и создаёт закрытый коридор. HTTP — язык, на котором вы просите конкретный документ.",
         "Үлкен іскерлік орталықты елестетіңіз. Домен — ұйымның таныс атауы. DNS — ғимарат мекенжайын табатын анықтама. IP — желідегі ғимарат мекенжайы. Порт — ішіндегі қабылдау бөлмесінің нөмірі. TCP сол бөлмемен байланыс орнатуды тексереді. TLS әңгімелесуші куәлігін тексеріп, жабық дәліз жасайды. HTTP — құжат сұрайтын тіл.",
         "Imagine a large business centre. A domain is the organisation's familiar name. DNS is the directory that finds its building address. An IP is the building's network address. A port is the required office number inside. TCP establishes a conversation with that office. TLS checks the other party's identity and creates a private corridor. HTTP is the language used to request a document."),
        [
            term("DNS", "Система, которая переводит доменное имя в IP-адрес.", "Домен атауын IP мекенжайға аударатын жүйе.", "The system that translates a domain name into an IP address."),
            term("IP-адрес · IP мекенжай · IP address", "Числовой сетевой адрес устройства или интерфейса.", "Құрылғы не интерфейстің сандық желі мекенжайы.", "A numeric network address for a device or interface."),
            term("Порт · Порт · Port", "Число от 0 до 65535, направляющее соединение к нужной программе на адресе.", "Қосылысты мекенжайдағы қажетті бағдарламаға бағыттайтын 0–65535 саны.", "A number from 0 to 65535 that routes a connection to the right program at an address."),
            term("TCP / HTTP / TLS", "TCP переносит упорядоченный поток; HTTP задаёт смысл запроса; TLS шифрует и проверяет сторону по сертификату.", "TCP реттелген ағынды тасиды; HTTP сұрау мағынасын береді; TLS шифрлап, сертификат арқылы тарапты тексереді.", "TCP carries an ordered stream; HTTP gives a request meaning; TLS encrypts it and verifies the peer with a certificate."),
        ],
        ("Сначала `getent` спрашивает DNS. Затем `curl` отдельно печатает HTTP-код, удалённый IP и результат проверки TLS. Последняя команда обращается прямо к локальному IP и порту. CloudLab мы запустим в следующем уроке, поэтому сейчас отказ соединения допустим и полезен: он показывает, что адрес существует, но на порту никто не принимает запрос.",
         "Алдымен `getent` DNS-тен сұрайды. Кейін `curl` HTTP кодын, қашық IP және TLS тексеру нәтижесін бөлек көрсетеді. Соңғы пәрмен жергілікті IP мен портқа тікелей барады. CloudLab келесі сабақта іске қосылады, сондықтан қазір connection refused пайдалы нәтиже: мекенжай бар, бірақ портта сұрау алатын үдеріс жоқ.",
         "First, `getent` asks DNS. Then `curl` prints the HTTP status, remote IP, and TLS verification result separately. The last command goes directly to a local IP and port. CloudLab starts in the next lesson, so connection refusal is useful evidence here: the address exists, but no process is accepting requests on that port."),
        ("Ошибка: «DNS открывает сайт». Исправление: DNS только сообщает IP; после него ещё нужны соединение, при необходимости TLS, HTTP-запрос и работа приложения.",
         "Қате: «DNS сайтты ашады». Дұрысы: DNS тек IP береді; одан кейін қосылу, TLS, HTTP сұрау және қолданба жұмысы қажет.",
         "Mistake: “DNS opens the website.” Correction: DNS only supplies an IP; a connection, optional TLS, an HTTP request, and the application must still work."),
        (["имя", "адрес", "дверь", "защита"], ["атау", "мекенжай", "есік", "қорғаныс"], ["name", "address", "door", "protection"]),
    ),
}


# The remaining lessons reuse the same teaching rhythm.  Their images are kept
# compact here so the generated article explains them in depth without turning
# the support signal itself into another wall of text.
_REST = [
    ("07-containers", ("контейнер = процесс + границы; VM = отдельная гостевая ОС", "контейнер = үдеріс + шекара; VM = бөлек қонақ ОС", "container = process + boundaries; VM = separate guest OS"),
     ("Кухня ресторана общая, но у каждого повара своя рабочая станция, набор продуктов и лимит места. Контейнер похож на такую станцию: он использует ядро общего Linux, но видит ограниченное окружение. Виртуальная машина больше похожа на отдельную кухню со своей инфраструктурой.", "Мейрамхана асүйі ортақ, бірақ әр аспаздың орны, өнімі және шегі бөлек. Контейнер осындай орынға ұқсайды: ортақ Linux ядросын қолданып, шектелген ортаны көреді. Виртуал машина жеке асүйге көбірек ұқсайды.", "A restaurant kitchen is shared, but each cook has a station, ingredients, and space limit. A container resembles that station: it shares the Linux kernel but sees a bounded environment. A virtual machine is closer to a separate kitchen."),
     [term("Контейнер · Контейнер · Container", "Изолированный процесс с заданными файлами, сетью и лимитами.", "Белгіленген файл, желі және шегі бар оқшауланған үдеріс.", "An isolated process with defined files, networking, and limits."), term("Образ · Образ · Image", "Неизменяемый шаблон файлов для запуска контейнера.", "Контейнер іске қосылатын өзгермейтін файл үлгісі.", "An immutable file template used to start a container."), term("VM", "Виртуальный компьютер со своей гостевой операционной системой.", "Өз қонақ операциялық жүйесі бар виртуал компьютер.", "A virtual computer with its own guest operating system."), term("Namespace", "Механизм Linux, ограничивающий то, что процесс видит.", "Үдеріс көретін нәрсені шектейтін Linux механизмі.", "A Linux mechanism limiting what a process can see.")],
     ("Команды запускают готовый образ, показывают процесс внутри и снаружи, затем удаляют учебный контейнер. Сравните PID и набор файлов: это один процесс с разными границами обзора.", "Пәрмендер дайын образды іске қосып, үдерісті іштен және сырттан көрсетіп, контейнерді жояды. PID пен файлды салыстырыңыз: бұл шекарасы бөлек бір үдеріс.", "The commands start a known image, show its process from inside and outside, then remove the learning container. Compare the PID and files: this is a process viewed through different boundaries."),
     ("Ошибка: «Контейнер — лёгкая виртуальная машина». Исправление: обычно контейнер делит ядро хоста; VM запускает отдельную гостевую ОС.", "Қате: «Контейнер — жеңіл виртуал машина». Дұрысы: контейнер хост ядросын бөліседі; VM бөлек қонақ ОС іске қосады.", "Mistake: “A container is a lightweight VM.” Correction: a container normally shares the host kernel; a VM runs a separate guest OS."),
     (["процесс", "граница", "общее ядро", "лимит"], ["үдеріс", "шекара", "ортақ ядро", "шек"], ["process", "boundary", "shared kernel", "limit"])),
    ("08-images-lifecycle", ("Dockerfile → слои → image@digest → container → stop/remove", "Dockerfile → қабат → image@digest → container → stop/remove", "Dockerfile → layers → image@digest → container → stop/remove"),
     ("Образ похож на запечатанный набор деталей конструктора, контейнер — уже собранная по нему модель. Тег — наклейка на коробке, которую можно переклеить. Digest — отпечаток содержимого: изменится хоть одна деталь, изменится и отпечаток.", "Образ — мөрленген конструктор бөлшектері, контейнер — сол бойынша жиналған модель. Тег — ауыстырылатын жапсырма. Digest — мазмұн ізі: бір бөлшек өзгерсе, із де өзгереді.", "An image resembles a sealed construction kit; a container is a model assembled from it. A tag is a label that can be moved. A digest fingerprints the content: change one part and the fingerprint changes."),
     [term("Слой · Қабат · Layer", "Сохранённое изменение файловой системы образа.", "Образ файл жүйесінің сақталған өзгерісі.", "A saved filesystem change in an image."), term("Тег · Тег · Tag", "Удобное изменяемое имя версии, например `1.0`.", "`1.0` сияқты ыңғайлы өзгермелі нұсқа атауы.", "A convenient movable version name such as `1.0`."), term("Digest", "Криптографический идентификатор точного содержимого образа.", "Образдың нақты мазмұнының криптографиялық идентификаторы.", "A cryptographic identifier for exact image content."), term("Жизненный цикл · Өмір циклі · Lifecycle", "Создание, запуск, остановка и удаление как разные состояния.", "Жасау, іске қосу, тоқтату және жоюдың бөлек күйлері.", "Creation, start, stop, and removal as distinct states.")],
     ("`image history` показывает слои, `inspect` — точный digest, а `run`, `stop`, `start`, `rm` дают почувствовать разницу между образом и экземпляром. После `stop` контейнер существует; после `rm` — нет.", "`image history` қабатты, `inspect` digest-ті көрсетеді. `run`, `stop`, `start`, `rm` образ бен дана айырмасын көрсетеді. `stop` кейін контейнер бар, `rm` кейін жоқ.", "`image history` exposes layers, `inspect` shows the digest, and `run`, `stop`, `start`, and `rm` demonstrate the difference between an image and an instance. After `stop` the container exists; after `rm` it does not."),
     ("Ошибка: «Тег `latest` всегда означает самый новый и неизменный образ». Исправление: это обычная перемещаемая метка; точность даёт digest.", "Қате: «`latest` әрқашан ең жаңа әрі өзгермейтін образ». Дұрысы: ол ауыспалы белгі; дәлдікті digest береді.", "Mistake: “The `latest` tag always means the newest immutable image.” Correction: it is a movable label; a digest gives exact identity."),
     (["рецепт", "слои", "метка", "отпечаток"], ["рецепт", "қабат", "белгі", "із"], ["recipe", "layers", "label", "fingerprint"])),
    ("09-dockerfile", ("source → test → build → copy binary → non-root runtime", "source → test → build → binary көшіру → non-root runtime", "source → test → build → copy binary → non-root runtime"),
     ("В производственный чемодан кладут только то, что понадобится в поездке, а не всю мастерскую. Multi-stage Dockerfile сначала использует большую мастерскую для сборки, затем переносит готовый бинарный файл в маленький чистый образ.", "Сапар чемоданына бүкіл шеберхана емес, керегі ғана салынады. Multi-stage Dockerfile үлкен ортада жинап, дайын binary-ді кішкентай таза образға көшіреді.", "A travel case contains only what the trip needs, not the whole workshop. A multi-stage Dockerfile builds in a large workshop, then copies the finished binary into a small clean image."),
     [term("Dockerfile", "Текстовый рецепт сборки образа по шагам.", "Образды қадаммен жинайтын мәтіндік рецепт.", "A text recipe that builds an image step by step."), term("Build stage", "Временная среда с компилятором и исходным кодом.", "Компилятор мен source бар уақытша орта.", "A temporary environment containing compiler and source."), term("Runtime stage", "Минимальная среда, в которой работает готовая программа.", "Дайын бағдарлама жұмыс істейтін ең аз орта.", "The minimal environment in which the finished program runs."), term("Non-root", "Запуск от пользователя без полномочий суперпользователя.", "Суперпайдаланушы құқығы жоқ user атынан іске қосу.", "Running as an identity without superuser powers.")],
     ("Сборка сперва выполняет тесты, потом компилирует CloudLab и переносит только нужные файлы. `inspect` проверяет пользователя, а health-запрос доказывает запуск. Малый размер сам по себе не доказывает безопасность.", "Жинау алдымен тестті орындап, CloudLab құрып, керекті файлды ғана тасиды. `inspect` user-ді, health сұрау іске қосуды тексереді. Кіші өлшем қауіпсіздікті өзі дәлелдемейді.", "The build runs tests, compiles CloudLab, and carries only required files forward. `inspect` checks the user and a health request proves startup. Small size alone does not prove security."),
     ("Ошибка: «Если образ маленький, он автоматически безопасен». Исправление: меньшая поверхность помогает, но нужны обновления, проверка зависимостей, права и безопасный код.", "Қате: «Образ кіші болса, автоматты қауіпсіз». Дұрысы: кіші бет көмектеседі, бірақ жаңарту, dependency тексеру, құқық және қауіпсіз код керек.", "Mistake: “A small image is automatically secure.” Correction: a smaller surface helps, but updates, dependency checks, permissions, and safe code still matter."),
     (["мастерская", "тест", "бинарник", "минимум"], ["шеберхана", "тест", "binary", "минимум"], ["workshop", "test", "binary", "minimum"])),
    ("10-persistent-data", ("container сменился; volume остался; restore доказал данные", "container ауысты; volume қалды; restore деректі дәлелдеді", "container changed; volume remained; restore proved data"),
     ("Гостиничный номер освобождается вместе с временными вещами гостя, но чемодан в камере хранения остаётся. Файловая система контейнера похожа на номер, volume — на отдельную камеру хранения. Но даже камера хранения не заменяет резервную копию в другом месте.", "Қонақүй бөлмесі босатылғанда уақытша зат кетеді, ал сақтау камерасындағы чемодан қалады. Контейнер файл жүйесі бөлме, volume бөлек сақтау орны сияқты. Бірақ ол басқа жердегі backup-ты алмастырмайды.", "A hotel room loses a guest's temporary items at checkout, while luggage in storage remains. A container filesystem resembles the room; a volume resembles separate storage. Even that storage does not replace a backup elsewhere."),
     [term("Volume", "Хранилище с жизненным циклом отдельно от контейнера.", "Контейнерден бөлек өмір циклі бар сақтау орны.", "Storage with a lifecycle separate from a container."), term("Bind mount", "Прямое подключение конкретного каталога хоста.", "Хосттағы нақты қалтаны тікелей қосу.", "A direct mount of a specific host directory."), term("Состояние · Күй · State", "Данные, которые должны пережить перезапуск или замену процесса.", "Үдеріс ауысса да сақталуы тиіс дерек.", "Data that must survive process restart or replacement."), term("Backup", "Отдельная копия, из которой проверено восстановление.", "Қалпына келтіру тексерілген бөлек көшірме.", "A separate copy from which restoration has been tested.")],
     ("Упражнение записывает заметку, пересоздаёт контейнер и читает её снова. Это проверяет отделение данных от процесса. Затем backup и restore доказывают ещё один путь; простое наличие архива доказательством не считается.", "Тәжірибе жазба сақтап, контейнерді қайта жасап, оны қайта оқиды. Бұл деректің үдерістен бөлек екенін тексереді. Backup пен restore екінші жолды дәлелдейді; архивтің болуы жеткіліксіз.", "The exercise writes a note, recreates the container, and reads it again. This proves separation of data from process. Backup and restore prove another path; merely possessing an archive is insufficient."),
     ("Ошибка: «Volume — это резервная копия». Исправление: volume переживает контейнер, но удаление, повреждение диска или ошибка данных может уничтожить и его.", "Қате: «Volume — backup». Дұрысы: volume контейнерден ұзақ тұрады, бірақ жою, диск бұзылуы не дерек қатесі оны да жояды.", "Mistake: “A volume is a backup.” Correction: it outlives a container, but deletion, disk failure, or data corruption can destroy it too."),
     (["процесс", "данные", "копия", "восстановление"], ["үдеріс", "дерек", "көшірме", "қалпына келтіру"], ["process", "data", "copy", "restore"])),
]


for stem, signal, analogy, words, command, mistake, nodes in _REST:
    PACKS[stem] = pack(signal, analogy, words, command, mistake, nodes)


_REST2 = [
    ("11-compose", ("services + network + volumes = один повторяемый запуск", "services + network + volumes = бір қайталанатын іске қосу", "services + network + volumes = one repeatable start"),
     ("Оркестр не начинает концерт по отдельному звонку каждому музыканту. Партитура перечисляет участников, порядок и связи. Compose-файл играет роль такой партитуры: приложение, proxy, сеть, том и проверки описаны вместе, а имена сервисов работают как внутренние адреса.", "Оркестр әр музыкантқа бөлек қоңыраумен концерт бастамайды. Партитура қатысушы, рет және байланысты көрсетеді. Compose файлы да қолданба, proxy, желі, том және тексеруді бірге сипаттайды; service атауы ішкі мекенжай болады.", "An orchestra does not start by calling every musician separately. A score lists participants, order, and relationships. A Compose file acts as that score: application, proxy, network, volume, and checks are described together, and service names become internal addresses."),
     [term("Docker Compose", "Инструмент запуска нескольких связанных контейнеров по одному YAML-описанию.", "Бір YAML сипаттамасымен байланысқан бірнеше контейнерді іске қосатын құрал.", "A tool that starts related containers from one YAML description."), term("Service", "Именованный тип контейнера и его настройки в Compose.", "Compose ішіндегі атаулы контейнер түрі және баптауы.", "A named container role and its settings in Compose."), term("Network", "Виртуальная сеть, где сервисы находят друг друга по имени.", "Сервистер бірін-бірі атаумен табатын виртуал желі.", "A virtual network where services find one another by name."), term("YAML", "Читаемый человеком формат данных, чувствительный к отступам.", "Шегініске сезімтал, адам оқитын дерек пішімі.", "A human-readable data format in which indentation matters.")],
     ("`config` сначала разворачивает и проверяет итоговое описание. `up -d` приводит среду к нему, `ps` показывает состояние, запрос через proxy проверяет пользовательский путь, а `down` аккуратно убирает созданные процессы и сеть.", "`config` қорытынды сипаттаманы тексереді. `up -d` ортаны соған келтіреді, `ps` күйді көрсетеді, proxy арқылы сұрау пайдаланушы жолын тексереді, `down` үдеріс пен желіні жинайды.", "`config` expands and checks the final description. `up -d` brings the environment to it, `ps` shows state, a request through the proxy tests the user path, and `down` removes the created processes and network."),
     ("Ошибка: «`depends_on` означает, что зависимость уже полностью готова». Исправление: порядок запуска и готовность различаются; readiness нужно проверять отдельно.", "Қате: «`depends_on` dependency толық дайын деген сөз». Дұрысы: іске қосу реті мен дайындық бөлек; readiness жеке тексеріледі.", "Mistake: “`depends_on` means a dependency is fully ready.” Correction: start order and readiness differ; readiness needs a separate check."),
     (["описание", "сервисы", "сеть", "проверка"], ["сипаттама", "сервис", "желі", "тексеру"], ["description", "services", "network", "check"])),
    ("12-health-resources", ("liveness: перезапустить? | readiness: дать трафик? | limits: сколько можно?", "liveness: restart? | readiness: traffic беру? | limits: қанша?", "liveness: restart? | readiness: send traffic? | limits: how much?"),
     ("В больнице пульс отвечает, жив ли человек, но не говорит, готов ли хирург начать операцию. А расписание операционной ограничивает число одновременных операций. Так же liveness, readiness и resource limits отвечают на три разные задачи; смешивать их опасно.", "Ауруханада пульс адамның тірі екенін көрсетеді, бірақ хирург операцияға дайын ба — айтпайды. Операция бөлмесінің кестесі қатар жұмысты шектейді. Liveness, readiness және resource limits те үш бөлек сұраққа жауап береді.", "In a hospital, a pulse says whether a person is alive but not whether a surgeon is ready to operate. An operating-room schedule limits concurrent work. Liveness, readiness, and resource limits likewise answer three different questions."),
     [term("Liveness", "Проверка: завис ли процесс настолько, что его следует перезапустить?", "Үдеріс restart қажет болатындай тұрып қалды ма деген тексеру.", "A check asking whether a process is stuck enough to restart."), term("Readiness", "Проверка: следует ли сейчас направлять сюда запросы?", "Қазір мұнда сұрау жіберуге бола ма деген тексеру.", "A check asking whether requests should be sent here now."), term("Resource limit", "Верхняя граница CPU или памяти для процесса.", "Үдеріске арналған CPU не жадының жоғарғы шегі.", "An upper CPU or memory boundary for a process."), term("Graceful shutdown", "Остановка с прекращением нового трафика и завершением начатой работы.", "Жаңа трафикті тоқтатып, басталған жұмысты аяқтайтын тоқтау.", "Shutdown that stops new traffic and finishes work already started.")],
     ("Упражнение наблюдает оба endpoint, затем посылает SIGTERM и проверяет завершение. Смотрите не только на код команды: спросите, перестал ли сервис принимать новую работу и успел ли закончить старую.", "Тәжірибе екі endpoint-ті бақылайды, SIGTERM жіберіп, аяқталуды тексереді. Пәрмен кодымен шектелмей, жаңа жұмыс тоқтады ма және ескі жұмыс аяқталды ма деп сұраңыз.", "The exercise observes both endpoints, sends SIGTERM, and checks termination. Look beyond the command status: ask whether new work stopped and existing work had time to finish."),
     ("Ошибка: «Чем чаще и глубже liveness-проверка, тем надёжнее». Исправление: тяжёлая или неверная проверка сама создаёт перезапуски и аварию.", "Қате: «Liveness неғұрлым жиі әрі терең болса, соғұрлым сенімді». Дұрысы: ауыр не қате тексеру өзі restart пен апат туғызады.", "Mistake: “The more frequent and deep a liveness check, the more reliable the service.” Correction: an expensive or wrong check can itself trigger restarts and an outage."),
     (["жив", "готов", "границы", "мягкая остановка"], ["тірі", "дайын", "шекара", "жұмсақ тоқтау"], ["alive", "ready", "boundaries", "graceful stop"])),
    ("13-registry", ("commit → image → digest → registry → SBOM/scan → deploy", "commit → image → digest → registry → SBOM/scan → deploy", "commit → image → digest → registry → SBOM/scan → deploy"),
     ("Склад принимает коробки, но сам факт хранения не доказывает качество содержимого. Registry — склад образов. Digest похож на пломбу конкретной коробки, SBOM — опись деталей внутри, сканер — сверка описи со списком известных проблем.", "Қойма қорапты сақтайды, бірақ бұл ішіндегі сапаны дәлелдемейді. Registry — образ қоймасы. Digest — нақты қорап мөрі, SBOM — ішкі бөлшек тізімі, scanner — тізімді белгілі мәселелермен салыстыру.", "A warehouse accepts boxes, but storage alone does not prove their contents are good. A registry is an image warehouse. A digest resembles a seal for one exact box, an SBOM is the parts list, and a scanner compares that list with known problems."),
     [term("Registry", "Сервис хранения и раздачи контейнерных образов.", "Контейнер образын сақтап, тарататын сервис.", "A service that stores and distributes container images."), term("Immutable", "Неизменяемый после публикации; новая версия получает новую идентичность.", "Жарияланған соң өзгермейді; жаңа нұсқа жаңа сәйкестік алады.", "Unchangeable after publication; a new version gets a new identity."), term("SBOM", "Перечень программных компонентов и версий внутри артефакта.", "Артефакт ішіндегі бағдарлама компоненті мен нұсқасының тізімі.", "A list of software components and versions inside an artifact."), term("Vulnerability", "Известная слабость, применимость которой нужно проверить в контексте.", "Контексте қолданылуын тексеру қажет белгілі әлсіздік.", "A known weakness whose applicability must be checked in context.")],
     ("Команды называют образ коротким SHA, получают его digest и создают опись. Если инструмент сканирования отсутствует, урок не притворяется успешным: сначала поймите ожидаемый артефакт и установите инструмент отдельно.", "Пәрмен образды қысқа SHA-мен атап, digest және тізім жасайды. Scanner жоқ болса, сабақ жалған success көрсетпейді: күтілетін артефактты түсініп, құралды бөлек орнатыңыз.", "The commands name an image with a short SHA, obtain its digest, and produce an inventory. If a scanner is absent, the lesson does not pretend success: understand the expected artifact and install the tool separately."),
     ("Ошибка: «Сканер не нашёл CVE, значит образ безопасен». Исправление: база неполна, конфигурация и собственный код тоже могут быть уязвимы.", "Қате: «Scanner CVE таппаса, образ қауіпсіз». Дұрысы: база толық емес, config пен өз кодыңыз да осал болуы мүмкін.", "Mistake: “No CVE was found, so the image is safe.” Correction: databases are incomplete, and configuration or your own code may still be vulnerable."),
     (["коробка", "пломба", "опись", "проверка"], ["қорап", "мөр", "тізім", "тексеру"], ["box", "seal", "inventory", "check"])),
    ("14-cicd", ("commit → fast checks → build once → verify → deliver → deploy deliberately", "commit → fast checks → build once → verify → deliver → deploy deliberately", "commit → fast checks → build once → verify → deliver → deploy deliberately"),
     ("На заводе деталь проходит контроль после каждого важного этапа, а не только когда автомобиль уже собран. CI даёт быструю обратную связь после изменения. Delivery готовит проверенный выпуск, deployment действительно меняет работающую среду. Это три разных обещания.", "Зауытта бөлшек әр маңызды кезеңнен кейін тексеріледі. CI өзгерістен кейін тез кері байланыс береді. Delivery тексерілген шығарылымды дайындайды, deployment жұмыс ортасын өзгертеді. Бұлар үш бөлек уәде.", "In a factory, a part is checked after each important stage, not only after the entire car is assembled. CI gives fast feedback after a change. Delivery prepares a verified release; deployment actually changes a running environment. These are different promises."),
     [term("CI", "Автоматическая интеграция изменений с быстрыми тестами и проверками.", "Өзгерісті жылдам тест пен тексерумен автоматты біріктіру.", "Automated integration of changes with fast tests and checks."), term("Delivery", "Состояние, когда проверенный выпуск готов к развёртыванию.", "Тексерілген шығарылым deploy-ға дайын күй.", "A state in which a verified release is ready to deploy."), term("Deployment", "Фактическая установка версии в среду.", "Нұсқаны ортаға нақты орнату.", "The actual installation of a version into an environment."), term("Pipeline", "Последовательность автоматических этапов и условий перехода.", "Автоматты кезеңдер мен өту шарттарының тізбегі.", "A sequence of automated stages and transition conditions.")],
     ("Локальный скрипт повторяет будущий pipeline: форматирование, тесты, сборка, проверка образа. Запустите его после намеренной маленькой ошибки и снова после исправления — обратная связь должна быть понятной.", "Жергілікті script болашақ pipeline-ды қайталайды: format, test, build, image check. Әдейі шағын қате жасап және түзеткен соң іске қосыңыз — кері байланыс түсінікті болсын.", "The local script mirrors the future pipeline: formatting, tests, build, and image verification. Run it after a deliberate small error and again after fixing it; feedback should be clear."),
     ("Ошибка: «CI/CD означает автоматический deploy каждого commit в production». Исправление: частота и согласование deployment — отдельное решение риска.", "Қате: «CI/CD әр commit-ті production-ға автоматты deploy етеді». Дұрысы: deployment жиілігі мен рұқсаты — тәуекел туралы бөлек шешім.", "Mistake: “CI/CD means every commit automatically deploys to production.” Correction: deployment frequency and approval are separate risk decisions."),
     (["изменение", "быстрая обратная связь", "один артефакт", "решение о deploy"], ["өзгеріс", "жылдам кері байланыс", "бір артефакт", "deploy шешімі"], ["change", "fast feedback", "one artifact", "deploy decision"])),
    ("15-github-actions", ("event → workflow → job → runner → steps → evidence", "event → workflow → job → runner → steps → evidence", "event → workflow → job → runner → steps → evidence"),
     ("Автоматическая мойка начинает работу, когда датчик видит машину, затем выполняет программу на конкретном посту. GitHub Actions похож: событие запускает workflow, job получает чистый runner, а steps по порядку выполняют команды и оставляют результат.", "Автоматты жуу көлікті датчик көргенде басталып, нақты орында бағдарлама орындайды. GitHub Actions те: event workflow бастайды, job таза runner алады, steps пәрменді ретімен орындап, нәтиже қалдырады.", "An automatic car wash starts when a sensor sees a car and runs a program at a specific bay. GitHub Actions is similar: an event starts a workflow, a job receives a clean runner, and steps execute commands in order and leave evidence."),
     [term("Workflow", "YAML-файл с триггерами, полномочиями и заданиями автоматизации.", "Автоматтандыру trigger, құқық және job жазылған YAML файл.", "A YAML file containing automation triggers, permissions, and jobs."), term("Job", "Набор шагов, выполняемый на одном runner.", "Бір runner-де орындалатын қадамдар жиыны.", "A set of steps executed on one runner."), term("Runner", "Временная машина или агент, выполняющий job.", "Job орындайтын уақытша машина не агент.", "A temporary machine or agent that executes a job."), term("Permissions", "Минимальные права временного токена workflow.", "Workflow уақытша token-інің ең аз құқығы.", "The minimum rights granted to a workflow's temporary token.")],
     ("Сначала прочитайте workflow как рассказ: когда начинается, на какой машине, с какими правами, какие доказательства создаёт. Затем сравните команды с локальным preflight, чтобы автоматизация не была тайным вторым способом сборки.", "Workflow-ды әңгіме ретінде оқыңыз: қашан, қай машинада, қандай құқықпен басталып, қандай дәлел жасайды. Пәрменді жергілікті preflight-пен салыстырыңыз.", "Read the workflow as a story: when it begins, on which machine, with what rights, and which evidence it creates. Compare its commands with the local preflight so automation is not a secret second build path."),
     ("Ошибка: «Action из Marketplace безопасен, потому что он популярен». Исправление: сторонний action выполняет код; проверяйте источник, фиксируйте версию и сокращайте permissions.", "Қате: «Marketplace action танымал болса, қауіпсіз». Дұрысы: сыртқы action код орындайды; source тексеріп, нұсқаны бекітіп, permissions азайтыңыз.", "Mistake: “A popular Marketplace action is automatically safe.” Correction: third-party actions execute code; review the source, pin versions, and reduce permissions."),
     (["событие", "чистая машина", "шаги", "доказательство"], ["оқиға", "таза машина", "қадам", "дәлел"], ["event", "clean machine", "steps", "evidence"])),
    ("16-release-image", ("test once → build once → sign/scan → push digest → promote same digest", "test once → build once → sign/scan → push digest → promote same digest", "test once → build once → sign/scan → push digest → promote same digest"),
     ("Образец лекарства проверяют, а затем распространяют именно проверенную партию. Если для каждой аптеки изготовить новую партию, прежняя проверка уже не доказывает её состав. Так же один образ строят один раз и переносят между средами по digest.", "Дәрінің бір партиясы тексеріліп, дәл сол партия таратылады. Әр дәріханаға қайта жасалса, бұрынғы тексеру құрамын дәлелдемейді. Образ да бір рет жиналып, орта арасында digest-пен жылжиды.", "A medicine sample is tested, and that exact batch is distributed. If a new batch is made for each pharmacy, the earlier test no longer proves its contents. Likewise, one image is built once and promoted across environments by digest."),
     [term("Artifact", "Собранный результат pipeline: бинарник, образ или пакет.", "Pipeline жинаған нәтиже: binary, image не package.", "A built pipeline output such as a binary, image, or package."), term("Release", "Идентифицированный набор изменений и артефактов, готовый к использованию.", "Қолдануға дайын, сәйкестендірілген өзгеріс пен артефакт жиыны.", "An identified set of changes and artifacts ready for use."), term("Promotion", "Перевод того же артефакта в следующую среду без пересборки.", "Сол артефактты қайта жинамай келесі ортаға өткізу.", "Moving the same artifact to the next environment without rebuilding."), term("Provenance", "Запись, откуда и каким процессом получен артефакт.", "Артефакт қайдан және қандай үрдіспен алынғанын көрсететін жазба.", "A record of where and how an artifact was produced.")],
     ("Упражнение строит образ, связывает его с commit SHA и извлекает digest. Скопируйте digest в журнал выпуска. Именно его должен получить следующий этап, а не новое локальное содержимое под тем же тегом.", "Тәжірибе образ жинап, commit SHA-мен байланыстырып, digest алады. Digest-ті release журналына жазыңыз. Келесі кезең сол digest-ті алуы тиіс.", "The exercise builds an image, ties it to a commit SHA, and extracts its digest. Record that digest in the release log. The next stage must receive it, not newly built local content under the same tag."),
     ("Ошибка: «Пересобрать тот же commit в production — то же самое». Исправление: зависимости, base image или builder могли измениться; продвигайте проверенный digest.", "Қате: «Сол commit-ті production-да қайта жинау бірдей». Дұрысы: dependency, base image не builder өзгеруі мүмкін; тексерілген digest-ті жылжытыңыз.", "Mistake: “Rebuilding the same commit in production is identical.” Correction: dependencies, base images, or builders may change; promote the verified digest."),
     (["исходник", "одна сборка", "digest", "продвижение"], ["source", "бір жинау", "digest", "жылжыту"], ["source", "one build", "digest", "promotion"])),
    ("17-secrets", ("config можно показать | secret нужно ограничить | оба вводятся извне image", "config көрсетуге болады | secret шектеледі | екеуі image сыртынан", "config may be shown | secret is restricted | both enter outside image"),
     ("Адрес офиса можно напечатать на визитке, ключ от сейфа — нельзя. Оба нужны работе, но обращаются с ними по-разному. Обычная конфигурация описывает среду, секрет даёт полномочия. Секрет не кладут в образ, журнал или историю Git.", "Офис мекенжайын визиткаға жазуға болады, сейф кілтін болмайды. Екеуі де жұмысқа керек, бірақ тәртібі бөлек. Config ортаны сипаттайды, secret өкілеттік береді. Secret image, log не Git тарихына салынбайды.", "An office address may be printed on a card; a safe key may not. Both support work but require different handling. Configuration describes an environment; a secret grants power. A secret does not belong in an image, log, or Git history."),
     [term("Configuration", "Несекретные параметры поведения приложения.", "Қолданба мінезін анықтайтын құпия емес параметр.", "Non-secret parameters controlling application behaviour."), term("Secret", "Значение, раскрытие которого даёт доступ или причиняет ущерб.", "Ашылса қолжетімділік беретін не зиян келтіретін мән.", "A value whose disclosure grants access or causes harm."), term("Environment variable", "Один из каналов передачи настройки процессу при запуске.", "Іске қосқанда үдеріске баптау беретін арналардың бірі.", "One channel for passing a setting to a process at startup."), term("Rotation", "Замена секрета и отзыв старого значения по плану.", "Secret-ті ауыстырып, ескі мәнді жоспармен қайтарып алу.", "Replacing a secret and revoking the old value according to a plan.")],
     ("Упражнение использует только фиктивное значение, проверяет `.gitignore` и ищет подозрительные строки. Затем процесс получает секрет во время запуска. Не печатайте значение даже ради демонстрации: доказывайте только факт наличия.", "Тәжірибе жалған мән қолданып, `.gitignore` және күмәнді жолды тексереді. Үдеріс secret-ті іске қосқанда алады. Демонстрация үшін де мәнді баспаңыз; барын ғана дәлелдеңіз.", "The exercise uses only a dummy value, checks `.gitignore`, and searches for suspicious strings. The process receives the secret at startup. Do not print it even for demonstration; prove only its presence."),
     ("Ошибка: «Удалить секрет из последнего commit достаточно». Исправление: он остаётся в истории и мог быть скопирован; значение нужно отозвать и заменить.", "Қате: «Secret-ті соңғы commit-тен өшіру жеткілікті». Дұрысы: ол тарихта қалып, көшірілген болуы мүмкін; мәнді revoke және rotate ету керек.", "Mistake: “Removing a secret from the latest commit is enough.” Correction: it remains in history and may have been copied; revoke and rotate it."),
     (["параметр", "полномочие", "не журналировать", "заменить"], ["параметр", "өкілеттік", "log-қа жазбау", "ауыстыру"], ["setting", "power", "never log", "rotate"])),
    ("18-deploy-rollback", ("deploy version X → smoke test → observe → keep X OR rollback Y → verify", "deploy X → smoke test → observe → keep X OR rollback Y → verify", "deploy X → smoke test → observe → keep X OR rollback Y → verify"),
     ("После ремонта водопровода мастер не уходит, увидев, что кран установлен. Он открывает воду, проверяет течь и знает, как вернуть прежнюю деталь. Deploy устанавливает версию, smoke test проверяет главный путь, наблюдение ищет последствия, rollback возвращает заранее известный вариант.", "Су құбырын жөндеген шебер кран орнатылды деп кетпейді. Суды ашып, ағып тұр ма тексереді және ескі бөлшекті қайтаруды біледі. Deploy нұсқа орнатады, smoke test негізгі жолды тексереді, rollback бұрынғы нұсқаны қайтарады.", "A plumber does not leave merely because a tap was installed. They run water, check for leaks, and know how to restore the old part. Deploy installs a version, a smoke test checks the main path, observation finds consequences, and rollback restores a known version."),
     [term("Deploy", "Установка конкретной версии в конкретную среду.", "Нақты нұсқаны нақты ортаға орнату.", "Installing a specific version into a specific environment."), term("Smoke test", "Короткая проверка критического пользовательского пути после изменения.", "Өзгерістен кейінгі негізгі пайдаланушы жолының қысқа тексеруі.", "A short check of a critical user path after a change."), term("Rollback", "Возврат к заранее известной версии или состоянию.", "Алдын ала белгілі нұсқа не күйге қайту.", "A return to a previously known version or state."), term("Migration", "Управляемое изменение структуры или смысла данных.", "Дерек құрылымы не мағынасын басқарылып өзгерту.", "A controlled change to data structure or meaning.")],
     ("Сценарий фиксирует старый и новый digest, переключает версию, выполняет smoke test и наблюдает сигнал. Rollback считается готовым только после отдельной репетиции. Помните: возврат кода не всегда совместим с уже изменёнными данными.", "Сценарий ескі және жаңа digest-ті жазып, нұсқаны ауыстырып, smoke test орындайды. Rollback бөлек жаттығудан кейін ғана дайын. Код қайтару өзгерген дерекпен әрқашан үйлеспейді.", "The scenario records old and new digests, switches version, runs a smoke test, and observes a signal. Rollback is ready only after rehearsal. Returning code may not be compatible with data already changed."),
     ("Ошибка: «Успешный exit code deploy означает успешный выпуск». Исправление: нужно проверить пользовательский путь и наблюдать систему после изменения.", "Қате: «Deploy exit code 0 болса, release сәтті». Дұрысы: пайдаланушы жолын тексеріп, өзгерістен кейін жүйені бақылау керек.", "Mistake: “A successful deploy exit code means a successful release.” Correction: test a user path and observe the system after the change."),
     (["версия", "проверка", "наблюдение", "путь назад"], ["нұсқа", "тексеру", "бақылау", "кері жол"], ["version", "check", "observe", "way back"])),
    ("19-cloud", ("need → region/size/access → price alert → create → observe → delete", "need → region/size/access → price alert → create → observe → delete", "need → region/size/access → price alert → create → observe → delete"),
     ("Облако похоже на аренду оборудованного офиса: быстро получаете помещение, но платите за время, площадь и дополнительные услуги. Арендодатель отвечает за здание, вы — за ключи, людей, документы и то, что оставили доступным. Это и есть разделённая ответственность.", "Бұлт жабдықталған кеңсені жалға алуға ұқсайды: тез аласыз, бірақ уақыт, көлем және қосымша қызметке төлейсіз. Иесі ғимаратқа, сіз кілт, адам, құжат және ашық қалдырған нәрсеге жауап бересіз. Бұл ортақ жауапкершілік.", "Cloud resembles renting a furnished office: it is available quickly, but time, size, and extras cost money. The landlord protects the building; you manage keys, people, documents, and anything left exposed. This is shared responsibility."),
     [term("IaaS", "Аренда виртуальных вычислений, сети и дисков с вашей ответственностью за ОС и приложение.", "ОС пен қолданбаға өзіңіз жауап беретін виртуал есептеу, желі және диск жалдау.", "Rental of virtual compute, networking, and disks while you manage the OS and application."), term("Region", "Географическая область размещения облачных ресурсов.", "Бұлт ресурсы орналасатын географиялық аймақ.", "A geographic area in which cloud resources run."), term("IAM", "Правила, кто и какое действие может выполнить над ресурсом.", "Ресурсқа кім қандай әрекет жасай алатынын анықтайтын ереже.", "Rules defining who may perform which action on a resource."), term("Budget alert", "Предупреждение о расходах; оно не всегда автоматически останавливает ресурс.", "Шығын туралы ескерту; ол ресурсты әрқашан автоматты тоқтатпайды.", "A spending warning; it does not necessarily stop resources automatically.")],
     ("Урок сначала создаёт текстовый план, а не оплачиваемый ресурс. В нём есть владелец, срок удаления, открытые порты и предупреждение бюджета. Только понятный план превращается в будущую инфраструктуру.", "Сабақ ақылы ресурс емес, алдымен мәтіндік жоспар жасайды. Онда ие, жою мерзімі, ашық порт және budget alert бар. Түсінікті жоспар ғана кейін инфрақұрылымға айналады.", "The lesson first creates a text plan rather than a billable resource. It records an owner, deletion date, open ports, and a budget alert. Only a understood plan becomes later infrastructure."),
     ("Ошибка: «Бесплатный кредит означает, что счёта быть не может». Исправление: лимит, срок и условия различаются; поставьте alert и условие удаления до создания.", "Қате: «Тегін credit болса, шот болмайды». Дұрысы: шек, мерзім және шарт бөлек; ресурсқа дейін alert пен жою шартын қойыңыз.", "Mistake: “Free credit means a bill is impossible.” Correction: limits, dates, and terms vary; set an alert and deletion condition before creation."),
     (["аренда", "разделённая ответственность", "бюджет", "удаление"], ["жалдау", "ортақ жауапкершілік", "бюджет", "жою"], ["rental", "shared responsibility", "budget", "delete"])),
    ("20-server", ("provider console → user+public key → second login → firewall → updates → app", "provider console → user+public key → second login → firewall → updates → app", "provider console → user+public key → second login → firewall → updates → app"),
     ("Переезжая в квартиру, сначала проверяют новый ключ, оставляя старую дверь открытой, и лишь потом меняют замок окончательно. На сервере сначала создают пользователя и проверяют второй вход, затем ограничивают root и firewall. Иначе можно запереть самого себя снаружи.", "Пәтерге көшкенде жаңа кілтті ескі есік ашық тұрғанда тексеріп, кейін ғана құлыпты толық ауыстырады. Серверде user жасап, екінші login тексеріп, содан соң root пен firewall шектеледі. Әйтпесе өзіңіз сыртта қаласыз.", "When moving into a flat, you test the new key while the old door remains open, then change the lock fully. On a server, create a user and verify a second login before restricting root and the firewall, or you may lock yourself out."),
     [term("SSH", "Защищённый протокол удалённого входа и выполнения команд.", "Қашықтан кіру және пәрмен орындаудың қорғалған протоколы.", "A secure protocol for remote login and command execution."), term("Key pair", "Приватный ключ остаётся у вас; публичный можно положить на сервер.", "Private key өзіңізде қалады; public key серверге беріледі.", "The private key stays with you; the public key may be placed on the server."), term("Firewall", "Правила, какие входящие и исходящие соединения разрешены.", "Қай кіріс және шығыс қосылуға рұқсат беретін ереже.", "Rules controlling which inbound and outbound connections are allowed."), term("Patch", "Обновление, исправляющее ошибки или уязвимости.", "Қате не осалдықты түзейтін жаңарту.", "An update that fixes defects or vulnerabilities.")],
     ("`ssh-keygen` создаёт пару. На сервер уходит только файл `.pub`; приватный файл остаётся с режимом 600. Инструкции намеренно требуют держать первую сессию открытой, пока второй вход не доказан.", "`ssh-keygen` жұп жасайды. Серверге тек `.pub` барады; private файл 600 режимімен қалады. Екінші login дәлелденгенше алғашқы сессия ашық тұрады.", "`ssh-keygen` creates a pair. Only the `.pub` file goes to the server; the private file stays with mode 600. The first session deliberately remains open until a second login is proven."),
     ("Ошибка: «Приватный ключ нужно скопировать на сервер, чтобы сервер узнал меня». Исправление: сервер хранит публичный ключ; приватный нельзя передавать.", "Қате: «Сервер мені тану үшін private key-ді серверге көшіру керек». Дұрысы: сервер public key сақтайды; private key берілмейді.", "Mistake: “The private key must be copied to the server so it recognises me.” Correction: the server stores the public key; never transfer the private key."),
     (["private у вас", "public на сервере", "второй вход", "закрыть лишнее"], ["private өзіңізде", "public серверде", "екінші login", "артықты жабу"], ["private with you", "public on server", "second login", "close extras"])),
    ("21-https", ("domain → DNS → public 443 → Caddy → private app:8080; certificate proves name", "domain → DNS → public 443 → Caddy → private app:8080; certificate атауды дәлелдейді", "domain → DNS → public 443 → Caddy → private app:8080; certificate proves name"),
     ("В большом здании посетитель приходит к общей стойке, а не ищет внутреннюю комнату сотрудника. Reverse proxy — такая стойка: принимает публичное защищённое соединение, проверяет адрес запроса и передаёт его приложению во внутренней сети. Сертификат похож на удостоверение стойки для конкретного имени.", "Үлкен ғимаратта келуші ішкі бөлмені емес, ортақ қабылдауды табады. Reverse proxy — сол қабылдау: ашық қорғалған байланысты алып, мекенжайды тексеріп, ішкі қолданбаға береді. Certificate — нақты атауға арналған куәлік.", "In a large building, a visitor goes to reception rather than finding an employee's internal room. A reverse proxy is that desk: it accepts the public secure connection, checks the requested address, and forwards it to the private application. A certificate is the desk's identity document for a specific name."),
     [term("Reverse proxy", "Публичный посредник перед приложением, принимающий и направляющий запросы.", "Қолданба алдында сұрауды қабылдап, бағыттайтын ашық делдал.", "A public intermediary that accepts and routes requests before an application."), term("HTTPS", "HTTP внутри соединения, защищённого TLS.", "TLS қорғайтын қосылыс ішіндегі HTTP.", "HTTP carried inside a TLS-protected connection."), term("Certificate", "Подписанный документ, связывающий открытый ключ с доменным именем.", "Public key мен домен атауын байланыстыратын қол қойылған құжат.", "A signed document binding a public key to a domain name."), term("Port 443", "Стандартный публичный порт HTTPS; это соглашение, а не шифрование само по себе.", "HTTPS стандарт ашық порты; порттың өзі шифрлау емес.", "The standard public HTTPS port; the port itself is not encryption.")],
     ("DNS сначала должен указывать на сервер. Caddy читает домен, получает сертификат и передаёт запрос на частный адрес приложения. `curl` без `-k` одновременно проверяет доверие сертификату и HTTP-ответ.", "DNS алдымен серверді көрсетуі тиіс. Caddy доменді оқып, certificate алып, сұрауды private қолданбаға береді. `curl` `-k`-сыз certificate trust пен HTTP жауапты бірге тексереді.", "DNS must first point to the server. Caddy reads the domain, obtains a certificate, and forwards the request to the application's private address. `curl` without `-k` checks certificate trust and the HTTP response together."),
     ("Ошибка: «Если страница открывается с `-k`, HTTPS настроен правильно». Исправление: `-k` отключает важную проверку личности и может скрыть неверный сертификат.", "Қате: «Бет `-k`-мен ашылса, HTTPS дұрыс». Дұрысы: `-k` тұлға тексеруін өшіріп, қате certificate-ті жасырады.", "Mistake: “If the page opens with `-k`, HTTPS is configured correctly.” Correction: `-k` disables identity verification and can hide a wrong certificate."),
     (["имя", "сертификат", "публичная стойка", "частное приложение"], ["атау", "certificate", "ашық қабылдау", "private қолданба"], ["name", "certificate", "public desk", "private app"])),
    ("22-iac", ("desired code → plan/diff → approve → apply → state; repeat → no surprise", "desired code → plan/diff → approve → apply → state; repeat → surprise жоқ", "desired code → plan/diff → approve → apply → state; repeat → no surprise"),
     ("Строитель работает по чертежу, а управляющий ведёт ведомость того, что уже построено. OpenTofu описывает желаемые облачные ресурсы и хранит связь с реальными объектами в state. Ansible похож на инструкцию обустройства комнат: устанавливает пакет и приводит файл к нужному виду.", "Құрылысшы сызбамен жұмыс істеп, басқарушы салынған нәрсенің тізімін ұстайды. OpenTofu қалаған cloud resource-ты сипаттап, нақты объект байланысын state-та сақтайды. Ansible бөлмені баптау нұсқаулығы сияқты.", "A builder works from a drawing while a manager keeps a ledger of what already exists. OpenTofu describes desired cloud resources and links them to real objects in state. Ansible resembles a room setup guide that installs packages and brings files to a desired form."),
     [term("Infrastructure as Code", "Описание инфраструктуры в проверяемых версионируемых файлах.", "Инфрақұрылымды тексерілетін, нұсқаланатын файлда сипаттау.", "Infrastructure described in reviewable, versioned files."), term("State", "Чувствительная запись соответствия между кодом и реальными ресурсами.", "Код пен нақты ресурс сәйкестігінің сезімтал жазбасы.", "A sensitive record mapping code to real resources."), term("Plan", "Предварительный список предполагаемых изменений до применения.", "Қолдануға дейінгі болжанған өзгеріс тізімі.", "A preview of proposed changes before application."), term("Idempotence", "Повторный запуск при уже достигнутом состоянии не делает лишних изменений.", "Қажетті күй бар болса, қайталау артық өзгеріс жасамайды.", "Repeating an operation after reaching the desired state makes no needless changes.")],
     ("`fmt` проверяет форму, `init -backend=false` готовит локальную проверку без удалённого state, `validate` проверяет структуру. Ansible syntax-check читает playbook без изменения сервера. Ни одна команда урока не вызывает `apply`.", "`fmt` пішінді, `init -backend=false` remote state-сіз жергілікті тексеруді, `validate` құрылымды тексереді. Ansible syntax-check серверді өзгертпей оқиды. Сабақта `apply` жоқ.", "`fmt` checks form, `init -backend=false` prepares local validation without remote state, and `validate` checks structure. Ansible syntax-check reads the playbook without changing a server. No lesson command invokes `apply`."),
     ("Ошибка: «Код инфраструктуры безопасен, потому что его можно прочитать». Исправление: ошибочный код повторяет ошибку быстрее; нужны plan, review, ограниченные права и защита state.", "Қате: «Infra code оқылатындықтан қауіпсіз». Дұрысы: қате код қатені тез қайталайды; plan, review, аз құқық және state қорғанысы керек.", "Mistake: “Infrastructure code is safe because it is readable.” Correction: wrong code repeats mistakes faster; use plans, review, limited rights, and protected state."),
     (["желаемое", "разница", "разрешение", "состояние"], ["қалаған күй", "айырма", "рұқсат", "state"], ["desired", "difference", "approval", "state"])),
    ("23-kubernetes", ("Deployment wants Pods → Service finds ready Pods → probes steer traffic → rollout changes gradually", "Deployment Pods қалайды → Service ready Pods табады → probes traffic басқарады → rollout біртіндеп", "Deployment wants Pods → Service finds ready Pods → probes steer traffic → rollout changes gradually"),
     ("Представьте сеть пекарен. Центральный план требует три работающих точки — это Deployment. Каждая точка — Pod. Единый номер заказов — Service. Проверка «можно ли принимать заказ?» — readiness probe. Постепенная замена старых точек новыми — rollout.", "Наубайхана желісін елестетіңіз. Орталық жоспар үш жұмыс нүктесін талап етеді — Deployment. Әр нүкте — Pod. Бір тапсырыс нөмірі — Service. «Тапсырыс алуға дайын ба?» — readiness probe. Ескіні жаңамен біртіндеп ауыстыру — rollout.", "Imagine a bakery chain. A central plan requires three operating shops: the Deployment. Each shop is a Pod. One ordering number is the Service. “Can this shop take orders?” is a readiness probe. Gradual replacement of old shops is a rollout."),
     [term("Kubernetes", "Система, которая постоянно приводит контейнерные приложения к описанному состоянию.", "Контейнер қолданбаны сипатталған күйге үнемі келтіретін жүйе.", "A system that continually moves container applications toward declared state."), term("Pod", "Минимальная запускаемая группа одного или нескольких тесно связанных контейнеров.", "Бір не бірнеше тығыз байланысқан контейнердің ең кіші іске қосу тобы.", "The smallest runnable group of one or more tightly related containers."), term("Deployment", "Контроллер желаемого числа Pod и стратегии обновления.", "Қалаған Pod саны мен жаңарту стратегиясын басқаратын controller.", "A controller for desired Pod count and update strategy."), term("Service и probe", "Service даёт стабильный вход; probe сообщает, какой Pod готов или жив.", "Service тұрақты кіріс береді; probe қай Pod дайын не тірі екенін айтады.", "A Service supplies a stable entry point; a probe reports which Pod is ready or alive.")],
     ("`kubectl kustomize` сначала собирает итоговый YAML локально. Поиск проверяет ключевые части, а client-side dry-run просит Kubernetes разобрать объект без создания. Только после понимания манифеста можно применять его к учебному кластеру.", "`kubectl kustomize` қорытынды YAML-ды жергілікті жинайды. Іздеу негізгі бөлікті, client-side dry-run объектіні жасамай талдауды тексереді. Түсінген соң ғана оқу кластеріне apply етіңіз.", "`kubectl kustomize` first renders final YAML locally. A search checks key parts, and client-side dry-run asks Kubernetes to parse objects without creating them. Apply only to a learning cluster after understanding the manifest."),
     ("Ошибка: «Kubernetes автоматически делает любое приложение отказоустойчивым». Исправление: он выполняет описанные правила, но плохие probes, единый диск или ошибка приложения сохраняются.", "Қате: «Kubernetes кез келген қолданбаны автоматты fault-tolerant етеді». Дұрысы: ол ережені орындайды, бірақ қате probe, бір диск және app қатесі қалады.", "Mistake: “Kubernetes automatically makes every application fault tolerant.” Correction: it executes declared rules, but bad probes, a single disk, or application defects remain."),
     (["желаемое", "Pod", "стабильный вход", "постепенная замена"], ["қалаған күй", "Pod", "тұрақты кіріс", "біртіндеп ауысу"], ["desired", "Pod", "stable entry", "gradual replacement"])),
    ("24-incident", ("detect → limit impact → restore service/data → verify → learn → owner+date", "detect → impact шектеу → service/data restore → verify → learn → owner+date", "detect → limit impact → restore service/data → verify → learn → owner+date"),
     ("Когда в доме пропадает вода, мало снова включить насос. Нужно узнать, кого затронуло, остановить утечку, восстановить подачу, проверить качество воды и устранить причину повторения. Инцидент с сервисом проходит тот же путь; поиск виноватого мешает собирать факты.", "Үйде су өшсе, насосты қайта қосу аз. Кімге әсер еткенін біліп, ағуды тоқтатып, суды беріп, сапасын тексеріп, қайталану себебін азайту керек. Сервис инциденті де сол жолдан өтеді; кінәлі іздеу дерек жинауға кедергі.", "When a building loses water, restarting the pump is insufficient. Determine who was affected, stop the leak, restore supply, test water quality, and reduce recurrence. A service incident follows the same path; blame obstructs fact gathering."),
     [term("Observability", "Способность задавать системе новые вопросы по её внешним сигналам.", "Жүйенің сыртқы сигналы арқылы жаңа сұраққа жауап алу қабілеті.", "The ability to ask new questions about a system through its outputs."), term("Metric / log / trace", "Метрика показывает число во времени, log — событие, trace — путь одного запроса.", "Metric уақыттағы санды, log оқиғаны, trace бір сұрау жолын көрсетеді.", "A metric shows a number over time, a log records an event, and a trace follows one request."), term("Incident", "Незапланированное событие, ухудшившее или угрожающее услуге.", "Қызметті нашарлатқан не қауіп төндірген жоспарсыз оқиға.", "An unplanned event that harms or threatens a service."), term("Restore drill", "Безопасная репетиция восстановления из копии в изолированное место.", "Көшірмеден бөлек орынға қауіпсіз қалпына келтіру жаттығуы.", "A safe rehearsal restoring a backup into an isolated location.")],
     ("Сначала снимите метрику и сохраните факты. Backup получает UTC-время и checksum. Restore идёт в отдельное место, где сравнивается содержимое. Отчёт фиксирует воздействие, временную линию, решение и конкретного владельца следующего действия.", "Алдымен metric пен факт сақталады. Backup UTC уақыт пен checksum алады. Restore бөлек жерде жасалып, мазмұн салыстырылады. Есеп impact, timeline, шешім және келесі әрекет иесін жазады.", "First capture a metric and preserve facts. The backup receives a UTC timestamp and checksum. Restoration occurs in an isolated place where content is compared. The report records impact, timeline, resolution, and an owner for follow-up."),
     ("Ошибка: «Инцидент закончился, когда сервис снова отвечает 200». Исправление: нужно проверить пользовательский результат и данные, сохранить факты и назначить работу против повторения.", "Қате: «Сервис қайта 200 берсе, incident бітті». Дұрысы: user нәтижесі мен деректі тексеріп, факт сақтап, қайталануға қарсы жұмыс тағайындау керек.", "Mistake: “The incident ends when the service returns 200.” Correction: verify user outcomes and data, preserve evidence, and assign work to reduce recurrence."),
     (["заметить", "ограничить", "восстановить", "научиться"], ["байқау", "шектеу", "қалпына келтіру", "үйрену"], ["detect", "limit", "restore", "learn"])),
]


for stem, signal, analogy, words, command, mistake, nodes in _REST2:
    PACKS[stem] = pack(signal, analogy, words, command, mistake, nodes)


PREFACE_TEACHING = {
    "ru": """## Как мы будем идти: методика опорных сигналов

Курс рассчитан на человека, который может впервые встретить слова DNS, TCP, TLS, контейнер или pipeline. Мы не считаем их «очевидными». Новое слово сначала связывается со знакомым образом, затем получает точное определение, место на короткой опорной схеме и только после этого появляется в команде.

Мы используем принципы системы Виктора Фёдоровича Шаталова в форме, подходящей самостоятельному онлайн-обучению:

1. **Сначала целое.** В начале урока видна короткая цепочка из четырёх опор, чтобы отдельные команды не висели в пустоте.
2. **Знакомый образ, затем термин.** DNS становится справочной, IP — адресом здания, порт — номером приёмной. После образа мы обязательно уточняем техническую границу аналогии.
3. **Опорный сигнал.** Несколько слов и знаков кодируют логику урока. Его нужно не заучить как лозунг, а раскрыть своими словами.
4. **Повторное воспроизведение.** Следующий урок начинается с короткого возвращения к предыдущей опоре. В конце вы рисуете цепочку по памяти и объясняете её вслух.
5. **Прогноз до опыта.** Перед командой вы сначала предполагаете результат. Сравнение прогноза с фактом превращает термин в собственное понимание.
6. **Частая обратная связь.** Маленькие проверки сразу показывают, на каком шаге потерялась связь. Ошибка — это указатель места для повторения, а не наказание и не запрет идти дальше навсегда.
7. **Открытая перспектива.** В конце видно, зачем нужен следующий урок и какой законченный проект постепенно появляется у вас в руках.

Читайте каждый урок двумя проходами. Первый раз — рассказ и схема без попытки всё запомнить. Второй — термин, прогноз, команда и проверка. Затем закройте схему и восстановите четыре опоры на бумаге. Если объяснение не получается, вернитесь к одному блоку, а не перечитывайте вслепую всю страницу.

## Нулевая подготовка: если вы ещё не открывали терминал

Терминал — обычное приложение с текстовым окном. На macOS откройте **Terminal**, в Ubuntu — приложение **Terminal**, в Windows установите **WSL2 с Ubuntu** и включите интеграцию WSL в Docker Desktop. Это будет ваша безопасная учебная мастерская. Не арендуйте сервер и ничего не оплачивайте на этом этапе.

Установите Git, Docker, Go и curl по официальным инструкциям для своей системы. После установки откройте новое окно терминала и выполните команды по одной:

```shell
git --version
docker version
go version
curl --version
```

Каждая команда должна напечатать версию, а `docker version` — сведения и о Client, и о Server. Если Server недоступен, сначала запустите Docker Desktop или Docker Engine. Затем получите учебный проект:

```shell
git clone https://github.com/DauletBai/shanraq.org.git
cd shanraq.org/course/cloud-devops-lab
pwd
```

`pwd` должен закончиться на `course/cloud-devops-lab`. Пока это не так, не запускайте команды следующих уроков: сначала исправьте рабочий каталог. Официальные страницы установки: [Git](https://git-scm.com/downloads), [Docker](https://docs.docker.com/get-started/get-docker/), [Go](https://go.dev/doc/install), [WSL](https://learn.microsoft.com/windows/wsl/install).
""",
    "kz": """## Қалай жүреміз: тірек сигналдар әдісі

Курс DNS, TCP, TLS, контейнер немесе pipeline сөздерін алғаш көретін адамға арналған. Біз оларды «өзінен-өзі түсінікті» деп санамаймыз. Жаңа сөз алдымен таныс бейнемен байланысады, кейін дәл анықтама мен қысқа тірек сызбада орын алады, содан соң ғана пәрменде қолданылады.

Виктор Фёдорович Шаталов жүйесінің өздігінен онлайн оқуға лайық қағидаларын қолданамыз:

1. **Алдымен тұтас көрініс.** Сабақ басындағы төрт тірек жеке пәрмендерді ортақ мағынаға біріктіреді.
2. **Таныс бейне, кейін термин.** DNS — анықтама, IP — ғимарат мекенжайы, порт — қабылдау бөлмесінің нөмірі. Кейін аналогияның техникалық шегін нақтылаймыз.
3. **Тірек сигнал.** Бірнеше сөз бен белгі сабақ логикасын кодтайды; оны өз сөзіңізбен ашасыз.
4. **Қайталап жаңғырту.** Келесі сабақ бұрынғы тірекке қысқа оралады, соңында тізбекті жатқа сызып, дауыстап түсіндіресіз.
5. **Тәжірибеге дейін болжау.** Пәрмен алдында нәтижені болжайсыз; болжам мен факт айырмасы түсінік қалыптастырады.
6. **Жиі кері байланыс.** Шағын тексеру байланыстың қай жерде үзілгенін бірден көрсетеді. Қате — жаза емес, қай жерді қайталау керегінің белгісі.
7. **Ашық перспектива.** Әр сабақ соңында келесі қадамның не үшін керегі және қолыңызда қандай жоба қалыптасып келе жатқаны көрінеді.

Әр сабақты екі рет оқыңыз. Бірінші өту — әңгіме мен сызба, бәрін жаттауға тырыспаңыз. Екінші өту — термин, болжам, пәрмен және тексеру. Кейін сызбаны жауып, төрт тіректі қағазға түсіріңіз. Түсіндіре алмасаңыз, бүкіл бетті емес, байланыс үзілген бір блокты қайталаңыз.

## Нөлдік дайындық: терминалды әлі ашпаған болсаңыз

Терминал — мәтіндік терезесі бар қалыпты қолданба. macOS-та **Terminal**, Ubuntu-да **Terminal** ашыңыз, Windows-та **Ubuntu бар WSL2** орнатып, Docker Desktop ішінде WSL integration қосыңыз. Бұл сіздің қауіпсіз оқу шеберханаңыз. Бұл кезеңде сервер жалдап, ақша төлемеңіз.

Өз жүйеңізге Git, Docker, Go және curl құралдарын ресми нұсқаулықпен орнатыңыз. Жаңа терминал ашып, бір-бірден орындаңыз:

```shell
git --version
docker version
go version
curl --version
```

Әр пәрмен нұсқаны, ал `docker version` Client және Server мәліметін көрсетуі тиіс. Server жоқ болса, Docker Desktop не Docker Engine іске қосыңыз. Кейін оқу жобасын алыңыз:

```shell
git clone https://github.com/DauletBai/shanraq.org.git
cd shanraq.org/course/cloud-devops-lab
pwd
```

`pwd` соңы `course/cloud-devops-lab` болуы тиіс. Олай болмаса, келесі сабақ пәрменін іске қоспай, алдымен жұмыс қалтасын түзетіңіз. Ресми беттер: [Git](https://git-scm.com/downloads), [Docker](https://docs.docker.com/get-started/get-docker/), [Go](https://go.dev/doc/install), [WSL](https://learn.microsoft.com/windows/wsl/install).
""",
    "en": """## How we will proceed: the support-signal method

This course is for someone who may be meeting DNS, TCP, TLS, container, or pipeline for the first time. We do not treat these words as obvious. A new word first connects to a familiar image, then receives a precise definition and a place on a short support map, and only then appears in a command.

We adapt principles from Viktor Shatalov's teaching system to independent online learning:

1. **See the whole first.** Four supports at the start keep individual commands attached to a larger meaning.
2. **Familiar image, then term.** DNS becomes a directory, an IP a building address, and a port an office number. We then state the technical limit of the analogy.
3. **Support signal.** A few words and symbols encode the lesson logic. You expand them in your own words instead of memorising a slogan.
4. **Repeated recall.** The next lesson briefly returns to the previous signal. At the end, you draw the chain from memory and explain it aloud.
5. **Predict before observing.** Before a command, you predict its result. Comparing prediction with evidence turns a label into understanding.
6. **Frequent feedback.** Small checks reveal the exact link that is missing. An error points to the block to revisit; it is not punishment or a permanent gate.
7. **Open perspective.** Every ending shows why the next lesson matters and which complete project is taking shape in your hands.

Read each lesson in two passes. On the first, follow the story and map without trying to memorise everything. On the second, work through the terms, prediction, command, and verification. Then hide the map and reconstruct its four supports on paper. If you cannot explain a link, revisit that block rather than blindly rereading the whole page.

## Zero setup: if you have never opened a terminal

A terminal is an ordinary application with a text window. Open **Terminal** on macOS or Ubuntu. On Windows, install **WSL2 with Ubuntu** and enable WSL integration in Docker Desktop. This is your safe learning workshop. Do not rent a server or pay for anything at this stage.

Install Git, Docker, Go, and curl using the official instructions for your system. Open a new terminal window and run these commands one at a time:

```shell
git --version
docker version
go version
curl --version
```

Each command should print a version. `docker version` should show both Client and Server information. If Server is unavailable, start Docker Desktop or Docker Engine first. Then obtain the learning project:

```shell
git clone https://github.com/DauletBai/shanraq.org.git
cd shanraq.org/course/cloud-devops-lab
pwd
```

The output of `pwd` must end in `course/cloud-devops-lab`. Do not run later lesson commands until it does; correct the working directory first. Official installation pages: [Git](https://git-scm.com/downloads), [Docker](https://docs.docker.com/get-started/get-docker/), [Go](https://go.dev/doc/install), and [WSL](https://learn.microsoft.com/windows/wsl/install).
""",
}
