#!/usr/bin/env python3
"""Author the trilingual paper-algorithm block of the Informatics course."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "course/lessons/informatics"
CURRICULUM = json.loads((ROOT / "course/informatics/curriculum.json").read_text(encoding="utf-8"))
ROWS = {row["number"]: row for row in CURRICULUM["lessons"]}

HEAD = {
    "ru": ("Лид (summary)", "Где мы на карте", "Ситуация и вопрос", "Новые слова без пропусков", "Опорный сигнал", "Разбираем шаг за шагом", "Предскажите и проверьте", "Поймайте ошибку", "Перенос в новую ситуацию", "Изменение проекта", "Задание и доказательство", "Возврат через 1, 7 и 30 дней", "Следующий урок", "Все уроки курса"),
    "kz": ("Лид (summary)", "Картадағы орнымыз", "Жағдай және сұрақ", "Жаңа сөздерді анық түсінейік", "Сабақтың тірек сигналы", "Қадамдап талдаймыз", "Болжаңыз және тексеріңіз", "Қатені табыңыз", "Жаңа жағдайға көшіру", "Жобаға енгізілетін өзгеріс", "Тапсырма және дәлел", "1, 7 және 30 күннен кейін қайталау", "Келесі сабақ", "Курстың барлық сабақтары"),
    "en": ("Lead (summary)", "Where we are on the map", "Situation and question", "New words without gaps", "The lesson's support signal", "Work through it step by step", "Predict and check", "Catch the error", "Transfer to a new setting", "Project change", "Task and evidence", "Return after 1, 7, and 30 days", "Next lesson", "All course lessons"),
}

STEMS = {
    19: "19-problem-decomposition",
    20: "20-state-variables",
    21: "21-sequence-tracing",
    22: "22-conditions-boundaries",
    23: "23-loops-invariants",
    24: "24-functions-contracts",
    25: "25-correctness-efficiency",
    26: "26-algorithms-mastery",
}

CONTENT = {
    19: {
        "ru": {
            "lead": "Разделим задачу напоминания на маленькие проверяемые действия и соберём первый алгоритм помощника на бумаге.",
            "scene": "Мама просит: «Пусть помощник напомнит о школьном проекте». Сразу нарисовать кнопку соблазнительно, но непонятно, где хранится срок и что делать, если его нет. Сначала ответьте: какой видимый результат должен получить человек и какие данные для него нужны?",
            "terms": "**Задача** — требуемый результат, а не список кнопок. **Декомпозиция** — разбиение задачи на части, каждую из которых можно объяснить и проверить отдельно. **Подзадача** имеет вход и результат: например, «получить срок» возвращает дату или сообщение об её отсутствии. **Зависимость** означает, что один шаг использует результат другого. **Критерий готовности** — наблюдаемое условие: при наличии срока помощник выдаёт правильное напоминание, а при его отсутствии честно сообщает, что срок не задан. Интерфейс — только способ показать результат, не сама логика.",
            "signal": "потребность → входные данные → маленькие шаги → проверяемый результат",
            "worked": "Начните с вымышленной задачи `t-01` «Кітап оқу». Срок «завтра» указан на отдельной тестовой карточке: в старом `tasks.json` срока ещё нет. (1) Найти запись по `id`, а не по названию: названия могут повторяться. (2) Прочесть срок. (3) Если срок отсутствует, вернуть «срок не указан» и остановиться. (4) Сравнить срок с сегодняшним днём. (5) Если задача не выполнена и срок близко, подготовить напоминание. (6) Показать результат. Теперь нарисуйте шесть карточек и стрелки зависимостей. Объясните, почему сравнение не может происходить раньше чтения срока. Эта бумажная модель ещё не программа: в ней нет формата даты и правила слова «близко»; следующие уроки добавят их.",
            "predict": "У записи есть название, но нет срока. Можно ли сразу перейти к сравнению дат? Запишите прогноз. Нет: сравнивать нечего; нужно завершить ветку понятным сообщением. У записи есть срок, но она выполнена — нужна ли напоминалка? Нет, если требование говорит напоминать только о невыполненном. Сравните обе ветки и найдите общую часть — поиск записи.",
            "error": "«Сначала сделаем красивый экран, потом разберёмся с данными». Исправьте план: вход и проверка срока определяют, что экран вообще может обещать. Пустой срок не должен выглядеть как нулевая дата.",
            "transfer": "Разбейте на подзадачи другую просьбу: «Показать, сколько задач завершено». Какие шаги общие с напоминанием, а какие новые? Не включайте поиск срока без причины. Объясните, что подсчёт должен пройти все записи, а не только первую.",
            "project": "В `step-02/ALGORITHM-ru.md` запишите цель, вход, выход и шесть карточек для напоминания. Сохраните три исходные вымышленные задачи без изменений. Добавьте отдельную таблицу предположений: сегодня, формат срока, смысл «близко». Непроверенные предположения нельзя прятать внутри рисунка.",
            "task": "Передайте карточки однокласснику в перепутанном порядке. Он должен восстановить зависимости, показать ветку без срока и объяснить остановку. Доказательство: схема, два прогона на разных входах и одно исправленное предположение. Если порядок можно восстановить двумя несовместимыми способами, допишите правило.",
            "review": "Завтра восстановите шесть шагов по памяти. Через семь дней разложите без подсказки просьбу о подсчёте. Через месяц проверьте, не зависит ли ваш будущий код от неоговорённого формата срока.",
        },
        "kz": {
            "lead": "Еске салу міндетін шағын тексерілетін әрекеттерге бөліп, көмекшінің алғашқы алгоритмін қағазда құрастырамыз.",
            "scene": "Анаңыз «көмекші мектеп жобасын есіме салсын» дейді. Бірден батырма салғыңыз келеді, бірақ мерзімнің қайда сақталатыны және ол жоқ кезде не болатыны белгісіз. Әуелі адам қандай нәтиже көруі тиіс және оған қандай дерек керегін айтыңыз.",
            "terms": "**Міндет** — керекті нәтиже, батырмалар тізімі емес. **Бөлшектеу** — үлкен міндетті бөлек түсіндіріп, тексеруге болатын бөліктерге ажырату. **Ішкі міндеттің** кірісі мен нәтижесі бар: мысалы, «мерзімді алу» күнді не оның жоқтығы туралы хабарды қайтарады. **Тәуелділік** — бір қадам өзге қадамның нәтижесін қолданады. **Дайындық өлшемі** — бақыланатын шарт: мерзім болса, дұрыс еске салу; болмаса, «мерзім берілмеген» деген адал хабар. Интерфейс нәтижені көрсетеді, бірақ логиканың өзі емес.",
            "signal": "қажеттілік → кіріс дерегі → шағын қадамдар → тексерілетін нәтиже",
            "worked": "Ойдан шығарылған `t-01` «Кітап оқу» тапсырмасынан бастаңыз. «Ертең» мерзімі бөлек сынақ карточкасында берілген: ескі `tasks.json` файлында мерзім әлі жоқ. (1) Жазбаны атауынан емес, `id` арқылы табу: атау қайталануы мүмкін. (2) Мерзімді оқу. (3) Ол болмаса, «мерзім берілмеген» деп тоқтау. (4) Мерзімді бүгінгі күнмен салыстыру. (5) Тапсырма орындалмаған және мерзім жақын болса, еске салу дайындау. (6) Нәтижені көрсету. Алты карточка мен тәуелділік бағыттарын салыңыз. Мерзімді оқымай тұрып салыстыру неге мүмкін емес? Бұл әлі бағдарлама емес: күн форматы мен «жақын» сөзінің ережесі белгісіз; оларды кейін анықтаймыз.",
            "predict": "Атау бар, мерзім жоқ. Күндерді бірден салыстыруға бола ма? Жоқ: салыстыратын мән жоқ, түсінікті хабармен тоқтау керек. Мерзім бар, тапсырма орындалған болса ше? Тек орындалмағанға еске салу керек деген талап болса, хабар жібермейміз. Екі тармақтың ортақ қадамын табыңыз: жазбаны іздеу.",
            "error": "«Әуелі әдемі экран жасайық, деректі кейін ойлаймыз». Жоспарды түзетіңіз: кіріс пен мерзімді тексеру экранның қандай уәде бере алатынын анықтайды. Бос мерзімді нөлдік күн етіп көрсетпеңіз.",
            "transfer": "«Орындалған тапсырмалар санын көрсету» өтінішін ішкі міндеттерге бөліңіз. Еске салумен ортақ және бөлек қадамдарды көрсетіңіз. Мерзімді себепсіз іздемеңіз. Санақ біріншісін ғана емес, барлық жазбаны қарауы керек.",
            "project": "`step-02/ALGORITHM-kz.md` ішіне мақсатты, кірісті, шығысты және еске салудың алты карточкасын жазыңыз. Үш бастапқы ойдан шығарылған тапсырманы өзгертпеңіз. Болжамдарға бөлек кесте жасаңыз: бүгінгі күн, мерзім форматы, «жақын» мағынасы. Тексерілмеген болжамды сызбада жасырмаңыз.",
            "task": "Карточкаларды сыныптасыңызға араластырып беріңіз. Ол тәуелділікті қалпына келтіріп, мерзімсіз тармақты және тоқтауды түсіндірсін. Дәлел: сызба, екі түрлі кіріспен сынақ және түзетілген бір болжам. Қадамдардың екі түрлі үйлеспейтін реті шыға берсе, ережені толықтырыңыз.",
            "review": "Ертең алты қадамды жатқа қалпына келтіріңіз. Жеті күннен кейін санау міндетін көмексіз бөлшектеңіз. Бір айдан соң болашақ кодыңыз мерзімнің келісілмеген форматына сүйенбейтінін тексеріңіз.",
        },
        "en": {
            "lead": "Break a reminder request into small testable actions and build the assistant's first paper algorithm.",
            "scene": "A parent says, “Make the assistant remind me about the school project.” Drawing a button immediately is tempting, but where is the due date stored, and what happens when it is missing? First state what result the person should see and which data that result requires.",
            "terms": "A **problem** names the required result, not a list of buttons. **Decomposition** splits the problem into parts that can each be explained and tested. A **subtask** has input and output: “read the due date” returns a date or a message that none is set. A **dependency** means one step uses another step's result. A **success criterion** is observable: with a date, the assistant gives the correct reminder; without one, it honestly says that no date is set. An interface only displays the result; it is not the logic itself.",
            "signal": "need → input data → small steps → testable result",
            "worked": "Start with fictional task `t-01`, “Кітап оқу.” A separate test card says it is due tomorrow; the older `tasks.json` has no due-date field yet. (1) Find the record by `id`, not title: titles may repeat. (2) Read its due date. (3) If none exists, return “no date set” and stop. (4) Compare the date with today. (5) If the task is unfinished and due soon, prepare a reminder. (6) Display the result. Draw six cards and dependency arrows. Explain why comparing dates cannot precede reading the date. This paper model is not yet code: it lacks a date format and a rule for “soon.” Later lessons will supply them.",
            "predict": "A record has a title but no due date. Can date comparison run immediately? No: there is nothing to compare; end that branch with an understandable message. A record has a date but is already done: should it trigger a reminder? No, if the requirement is to remind only about unfinished tasks. Find the shared step in both cases: locating the record.",
            "error": "“Let's make a beautiful screen first and decide on data later.” Repair the plan: the input and date check determine what the screen may honestly promise. An absent date must not look like a zero date.",
            "transfer": "Decompose another request: “Show how many tasks are done.” Which steps are shared with reminding and which are new? Do not read a due date without a reason. Counting must examine every record, not only the first.",
            "project": "In `step-02/ALGORITHM-en.md`, document the goal, input, output, and six reminder cards. Keep the three original fictional tasks unchanged. Add a separate assumptions table for today's date, date format, and the meaning of “soon.” Do not hide unchecked assumptions inside a diagram.",
            "task": "Give the six shuffled cards to a partner. They must restore dependencies, show the no-date branch, and explain the stop. Evidence: a diagram, two runs with different inputs, and one corrected assumption. If two incompatible orders both seem valid, clarify the rule.",
            "review": "Tomorrow reconstruct the six steps from memory. In seven days decompose a counting request unaided. In a month check that future code does not rely on an unstated date format.",
        },
    },
    20: {
        "ru": {
            "lead": "Поймём состояние на игре с тремя жизнями и опишем, как помощник хранит изменение задачи.",
            "scene": "В игре на экране три жизни. После ловушки их две, после бонуса четыре. Экран менялся, но что именно нужно помнить между событиями? В помощнике похожая ситуация: задача была не выполнена, затем стала выполненной.",
            "terms": "**Состояние** — данные о системе в выбранный момент. **Переменная** — имя для значения, которое алгоритм может изменить. **Присваивание** заменяет прежнее значение новым; запись `lives ← lives − 1` не утверждает математическое равенство, а предписывает сначала вычислить правую часть. **Начальное значение** — состояние до первого события. **Переход состояния** — пара «было → стало» после одного действия. **Инвариант** — условие, которое должно оставаться истинным, например число жизней не становится отрицательным. Не путайте переменную в бумажном алгоритме с сохранённым полем в JSON: после выключения временное значение пропадёт, если его не записать.",
            "signal": "начальное состояние → событие → новое значение → проверка ограничения",
            "worked": "Сделайте таблицу с колонками `событие | lives до | действие | lives после`. Начало: 3. Ловушка: `3 − 1 = 2`. Бонус: `2 + 2 = 4`. Три потери подряд: `4 − 1 = 3`, затем 2, затем 1. Если при 0 случится ещё ловушка, алгоритм должен либо оставить 0, либо закончить игру — правило нужно выбрать заранее. Для `t-01` таблица короче: `done=false` → действие «отметить выполненной» → `done=true`. Повторное нажатие не должно случайно вернуть `false`, если кнопка называется «Отметить выполненной».",
            "predict": "Начните с двух жизней и примените ловушку, бонус +2, ловушку. Назовите состояние после каждого шага до просмотра примера: 1, 3, 2. Затем спросите, каким будет `done` после двух одинаковых действий «отметить выполненной»: `true`, если действие задаёт значение, а не переключает его. Это различие важно при повторной отправке команды.",
            "error": "«`lives ← lives − 1` означает, что число равно числу минус один, значит алгоритм неверен». Стрелка означает обновление: прочитать старое значение, вычислить новое, записать новое. Для математики используйте равенство, для бумажной команды — стрелку.",
            "transfer": "Придумайте счётчик прочитанных страниц. Он начинается с 0; по событию «прочитал страницу» увеличивается на 1. Что сделать при случайном повторном событии? Запишите правило, иначе два нажатия дадут ложный прогресс.",
            "project": "В `ALGORITHM-ru.md` добавьте таблицу состояний одной задачи: `id`, `title`, `done`. Отдельно укажите, что `id` не меняется при отметке выполнения. Сохранение нового `done` в файл пока обозначьте отдельным шагом, не выдавая бумажную переменную за запись на диске.",
            "task": "Пройдите вручную три события игры и два действия с задачей. Доказательство — таблица до/после, правило для нижней границы 0 и результат повторной команды. Попросите другого учащегося восстановить итог только по вашей таблице.",
            "review": "Завтра объясните стрелку присваивания. Через семь дней проследите новый счётчик. Через месяц проверьте, где в программе состояние временное, а где сохраняется.",
        },
        "kz": {
            "lead": "Үш өмірі бар ойыннан күй ұғымын түсініп, көмекшідегі тапсырма өзгерісін сипаттаймыз.",
            "scene": "Ойында экранда үш өмір тұр. Тұзақтан кейін екеу, сыйлықтан кейін төртеу. Экран өзгерді, бірақ оқиғалардың арасында нақты нені есте сақтау керек? Көмекшіде де тапсырма орындалмаған күйден орындалған күйге өтеді.",
            "terms": "**Күй** — жүйенің таңдалған сәттегі деректері. **Айнымалы** — алгоритм өзгерте алатын мәннің атауы. **Меншіктеу** ескі мәнді жаңасымен алмастырады; `lives ← lives − 1` математикалық теңдік емес: әуелі оң жақты есептеп, кейін жаз деген нұсқау. **Бастапқы мән** — бірінші оқиғаға дейінгі күй. **Күй ауысуы** — бір әрекеттен кейінгі «болды → болды» жұбы. **Инвариант** — сақталуға тиіс шарт, мысалы өмір саны теріс болмауы. Қағаздағы айнымалыны JSON файлына сақталған өріспен шатастырмаңыз: уақытша мән жазылмаса, құрылғы өшкенде жоғалады.",
            "signal": "бастапқы күй → оқиға → жаңа мән → шектеуді тексеру",
            "worked": "`оқиға | lives бұрын | әрекет | lives кейін` кестесін жасаңыз. Басы: 3. Тұзақ: `3 − 1 = 2`. Сыйлық: `2 + 2 = 4`. Қатарынан үш жоғалту: `4 − 1 = 3`, сосын 2, сосын 1. Нөлде тағы тұзақ кездессе, алгоритм не 0 қалдыруы, не ойынды аяқтауы керек — ережені алдын ала таңдаңыз. `t-01` үшін кесте қысқа: `done=false` → «орындалды деп белгілеу» → `done=true`. Батырма «Орындалды деп белгілеу» деп аталса, қайталап басу мәнді байқамай `false` қылмауы тиіс.",
            "predict": "Екі өмірден бастаңыз: тұзақ, +2 сыйлық, тұзақ. Әр қадамдағы күйді болжаңыз: 1, 3, 2. «Орындалды деп белгілеу» әрекеті екі рет орындалса, `done` қандай болады? Әрекет ауыстырмай, нақты мән берсе, `true` қалады. Бұл команданы қайталағанда маңызды.",
            "error": "«`lives ← lives − 1` деген сан өзінен бірді алғанда өзіне тең деген сөз, сондықтан қате». Жоқ: жебе жаңарту белгісі. Ескі мәнді оқып, жаңасын есептеп, орнына жазамыз. Математикалық теңдікке `=`, қағаздағы командаға жебе қолданамыз.",
            "transfer": "Оқылған беттер санағышын ойлаңыз. Басы 0, «бет оқылды» оқиғасында +1. Оқиға кездейсоқ екі рет жіберілсе не істеу керек? Ережесіз екі басу жалған прогресс береді.",
            "project": "`ALGORITHM-kz.md` ішіне бір тапсырманың `id`, `title`, `done` күй кестесін қосыңыз. Орындалды деп белгілеу `id` мәнін өзгертпейтінін жазыңыз. Жаңа `done` мәнін файлға сақтау қағаздағы айнымалыдан бөлек қадам болсын.",
            "task": "Үш ойын оқиғасын және тапсырмамен екі әрекетті қолмен орындаңыз. Дәлел: бұрын/кейін кестесі, 0 төменгі шегінің ережесі және қайталанған команданың нәтижесі. Өзге оқушы тек кестеңізге қарап соңғы күйді таба алсын.",
            "review": "Ертең меншіктеу жебесін түсіндіріңіз. Жеті күннен соң жаңа санағышты қадағалаңыз. Бір айдан кейін қай күй уақытша, қайсысы файлға жазылатынын тексеріңіз.",
        },
        "en": {
            "lead": "Use a game with three lives to understand state, then describe how the assistant changes a task.",
            "scene": "A game shows three lives. After a trap there are two; after a bonus there are four. The screen changed, but what must be remembered between events? The assistant has a similar transition: a task goes from unfinished to done.",
            "terms": "**State** is data describing the system at a chosen moment. A **variable** names a value the algorithm may change. **Assignment** replaces an old value with a new one; `lives ← lives − 1` is not a mathematical equality but an instruction to compute the right side first. An **initial value** is the state before the first event. A **state transition** is a before/after pair caused by one action. An **invariant** is a condition that must keep holding, such as lives never being negative. Do not confuse a paper variable with a saved JSON field: a temporary value disappears on shutdown unless written to storage.",
            "signal": "initial state → event → new value → check constraint",
            "worked": "Make a table `event | lives before | action | lives after`. Begin at 3. Trap: `3 − 1 = 2`. Bonus: `2 + 2 = 4`. Three more traps yield 3, then 2, then 1. If a trap arrives at 0, the algorithm must keep 0 or end the game; choose the rule in advance. For `t-01`, the table is shorter: `done=false` → “mark as done” → `done=true`. Repeating that action should not unexpectedly return `false` if the button says “Mark as done.”",
            "predict": "Begin with two lives and apply trap, +2 bonus, trap. Name each state before checking: 1, 3, 2. After two identical “mark as done” actions, what is `done`? It remains `true` if the action sets a value rather than toggling it. This matters when a command is sent twice.",
            "error": "“`lives ← lives − 1` says a number equals itself minus one, so the algorithm is impossible.” The arrow means update: read the old value, compute a new one, store it. Use equality in mathematics and an arrow for the paper instruction.",
            "transfer": "Invent a counter of pages read, initially 0, increased by each “page read” event. What if the event is accidentally sent twice? State a rule or two taps will record false progress.",
            "project": "In `ALGORITHM-en.md`, add a state table for one task with `id`, `title`, and `done`. State that marking it done does not change `id`. Keep “save new done value to file” as a separate step; a paper variable is not a disk write.",
            "task": "Trace three game events and two task actions by hand. Evidence: before/after table, rule for the lower bound of 0, and result of a repeated command. Another learner should recover the final state using only your table.",
            "review": "Tomorrow explain the assignment arrow. In seven days trace a new counter. In a month identify which state in the program is temporary and which is saved.",
        },
    },
    21: {
        "ru": {
            "lead": "Проследим каждую команду алгоритма и поймём, как небольшая ошибка меняет окончательный результат.",
            "scene": "Курьер получил три команды: взять посылку, дойти до двери, позвонить. Если позвонить до того, как он взял посылку, адресат откроет дверь, но доставка не состоится. Компьютер тоже исполняет шаги в порядке записи, если мы не задали другое правило.",
            "terms": "**Алгоритм** — конечное описание действий для определённого класса входов. **Последовательность** — выполнение шагов один за другим. **Трассировка** — запись значений после каждого шага, а не только последнего ответа. **Шаг** — одно точно названное действие. **Вход** — данные, которые алгоритм получает; **выход** — то, что он возвращает или показывает. **Побочный эффект** — дополнительное изменение, например запись файла. Два алгоритма могут показывать одинаковый экран сейчас, но по-разному вести себя после повторного запуска из-за разного порядка сохранения.",
            "signal": "вход → шаг 1 → состояние 1 → шаг 2 → состояние 2 → выход",
            "worked": "Пусть `count=0`, а две вымышленные записи имеют `done=false` и `done=true`. Бумажные команды: (1) `count ← count + 1`; (2) показать `count`; (3) `count ← count + 1`; (4) показать `count`. Трасса даёт 1, затем 2. Если сначала выполнить оба прибавления, а потом два показа, выйдет 2 и 2. Набор команд почти тот же, порядок другой. Для помощника правильнее: прочитать файл, найти запись, изменить `done`, сохранить файл, подтвердить результат после повторного чтения. Сообщение «сохранено» перед записью было бы ложным обещанием.",
            "predict": "Начало `count=2`; шаги `+1`, `показать`, `−2`, `показать`. Не считайте в уме только итог. Заполните строку после каждого шага: 3, экран 3, 1, экран 1. Объясните, почему экран не обязан показывать все промежуточные значения.",
            "error": "«В конце `count=1`, значит алгоритм верен». Неверно: промежуточное сообщение могло показать 3 тогда, когда требовалось 1. Проверьте трассу и критерии для каждого наблюдаемого действия.",
            "transfer": "Даны действия «открыть файл», «проверить поля», «показать задачи», «сообщить об ошибке». Расположите их так, чтобы при неверном JSON задачи не показывались как достоверные. Нарисуйте ветку ошибки без перехода к показу.",
            "project": "Добавьте в `ALGORITHM-ru.md` таблицу трассировки для `t-01`: состояние до, действие, состояние после, видимое сообщение. Проследите успешное сохранение и ошибку чтения. Выделите шаг, где действительно меняется файл.",
            "task": "Сделайте две трассы: нормальный путь и путь с отсутствующим файлом. Поменяйте местами два шага и объясните, какое наблюдение изменилось. Доказательство — таблицы и точное указание первого неверного шага.",
            "review": "Завтра восстановите трассу счётчика. Через семь дней найдите ошибку порядка в новой бытовой инструкции. Через месяц сравните фактический порядок программы с бумажной трассой.",
        },
        "kz": {
            "lead": "Алгоритмнің әр командасын бақылап, шағын қате соңғы нәтижені қалай өзгертетінін көреміз.",
            "scene": "Курьерге үш нұсқау берілді: сәлемдемені алу, есікке бару, қоңырау соғу. Ол сәлемдемені алмай тұрып қоңырау соқса, есік ашылады, бірақ жеткізу болмайды. Компьютер де басқа ереже болмаса, қадамдарды жазылған ретімен орындайды.",
            "terms": "**Алгоритм** — белгілі кірістер тобына арналған әрекеттердің аяқталатын сипаттамасы. **Тізбек** — қадамдарды бірінен кейін бірін орындау. **Трассировка** — соңғы жауапты ғана емес, әр қадамнан кейінгі мәнді жазу. **Қадам** — дәл аталған жеке әрекет. **Кіріс** — алгоритм алатын дерек; **шығыс** — қайтаратын не көрсететін нәтиже. **Жанама әсер** — қосымша өзгеріс, мысалы файлға жазу. Қазір бірдей экран көрсеткен екі алгоритм сақтау ретінен кейін қайта іске қосылғанда әртүрлі нәтиже беруі мүмкін.",
            "signal": "кіріс → 1-қадам → 1-күй → 2-қадам → 2-күй → шығыс",
            "worked": "`count=0`, ал екі ойдан шығарылған жазбаның `done` мәндері `false` және `true` болсын. Қағаз командалары: (1) `count ← count + 1`; (2) `count` көрсету; (3) тағы `count ← count + 1`; (4) көрсету. Шығыстар 1, сосын 2. Екі қосу алдымен орындалып, кейін екі көрсету болса, 2 және 2 шығады. Командалар ұқсас, реті бөлек. Көмекші үшін дұрыс рет: файлды оқу, жазбаны табу, `done` өзгерту, файлды сақтау, қайта оқығаннан кейін растау. Жазбай тұрып «сақталды» деу — жалған уәде.",
            "predict": "Басы `count=2`; қадамдар `+1`, `көрсету`, `−2`, `көрсету`. Тек соңғы мәнді ойша таппаңыз. Әр қадамнан кейін жазыңыз: 3, экранда 3, 1, экранда 1. Неге экран барлық аралық мәнді көрсетуге міндетті емес екенін түсіндіріңіз.",
            "error": "«Соңында `count=1`, демек дұрыс». Аралық хабар 1 керек жерде 3 көрсетуі мүмкін. Әр бақыланатын әрекетті трасса және талаппен салыстырыңыз.",
            "transfer": "«Файлды ашу», «өрістерді тексеру», «тапсырмаларды көрсету», «қате хабарын беру» әрекеттерін орналастырыңыз. JSON жарамсыз болса, тапсырма сенімді дерек ретінде көрсетілмесін. Қате тармағын бөлек салыңыз.",
            "project": "`ALGORITHM-kz.md` ішіне `t-01` трассасын енгізіңіз: бұрынғы күй, әрекет, кейінгі күй, көрінетін хабар. Сәтті сақтауды және оқу қатесін тексеріңіз. Файл шынымен өзгеретін қадамды белгілеңіз.",
            "task": "Қалыпты жол және файл жоқ жол үшін екі трасса жасаңыз. Екі қадамның орнын ауыстырып, қай нәтиже өзгергенін көрсетіңіз. Дәлел — кестелер және алғашқы қате қадам.",
            "review": "Ертең санағыш трассасын қалпына келтіріңіз. Жеті күннен соң жаңа тұрмыстық нұсқаулықтағы реттілік қатесін табыңыз. Бір айдан кейін бағдарлама ретін қағаз трассамен салыстырыңыз.",
        },
        "en": {
            "lead": "Trace every algorithmic action and see how a small ordering mistake changes the final result.",
            "scene": "A courier receives three instructions: collect the parcel, go to the door, ring the bell. If they ring before collecting the parcel, the door opens but no delivery happens. A computer also follows written order unless we specify another rule.",
            "terms": "An **algorithm** is a finite description of actions for a defined class of inputs. A **sequence** executes steps one after another. A **trace** records values after every step, not only the final answer. A **step** is one precisely named action. **Input** is data received by the algorithm; **output** is what it returns or displays. A **side effect** is an extra change such as writing a file. Two algorithms can display the same screen now but behave differently after restart because they saved in a different order.",
            "signal": "input → step 1 → state 1 → step 2 → state 2 → output",
            "worked": "Let `count=0`, with two fictional records whose `done` values are `false` and `true`. Paper commands: (1) `count ← count + 1`; (2) display `count`; (3) increment again; (4) display. The trace displays 1, then 2. Move both increments before both displays and you get 2, then 2. Almost the same commands, different order. For the assistant, the honest sequence is: read file, find record, change `done`, save file, confirm after a second read. Saying “saved” before writing would be a false promise.",
            "predict": "Start at `count=2`; steps are `+1`, display, `−2`, display. Do not calculate only the final value. Record each step: 3, screen 3, 1, screen 1. Explain why the screen need not show every intermediate value.",
            "error": "“The final `count` is 1, so the algorithm is right.” The earlier message might have shown 3 when the requirement asked for 1. Compare the full trace with each observable requirement.",
            "transfer": "Order “open file,” “validate fields,” “display tasks,” and “report error” so invalid JSON cannot be displayed as trusted tasks. Draw an error branch that never reaches display.",
            "project": "Add a trace table for `t-01` to `ALGORITHM-en.md`: state before, action, state after, visible message. Trace both a successful save and a read failure. Mark the step that actually changes the file.",
            "task": "Make two traces: normal path and missing-file path. Exchange two steps and explain what observation changes. Evidence: tables and the exact first wrong step.",
            "review": "Tomorrow reconstruct the counter trace. In seven days find an ordering error in a new everyday instruction. In a month compare real program order with your paper trace.",
        },
    },
    22: {
        "ru": {
            "lead": "Научимся проверять условие на границе, чтобы помощник не забывал задачи ровно за два дня до срока.",
            "scene": "Вы договорились напоминать о невыполненной задаче, когда до срока осталось не более двух дней. Помощник молчит при двух днях и будит человека после срока. Ошибка скрыта в одном знаке сравнения. Найдём его на таблице, а не на глаз.",
            "terms": "**Условие** — вопрос с ответом «да» или «нет». **Ветвление** выбирает действия по ответу. **Граница** — значение, на котором ответ меняется: здесь 2 дня. **Граничный случай** проверяет само значение 2 и соседние 1 и 3. **Булево значение** — `true` или `false`; **И** требует выполнения обеих частей, а **ИЛИ** — хотя бы одной. **Просрочено** — срок уже прошёл; это отдельное состояние, а не «ещё ноль дней». Дату сравнивают по календарному правилу и одному часовому поясу; разные часовые пояса без согласования дают разные результаты.",
            "signal": "не выполнено И 0 ≤ дней_до_срока ≤ 2 → напомнить; прошло → просрочено",
            "worked": "Примем `today = 2026-10-09` и считаем целые календарные дни в одном часовом поясе. Для срока 12 октября остаётся 3 дня — не напоминать; 11 октября — 2, напомнить; 10 октября — 1, напомнить; 9 октября — 0, напомнить сегодня; 8 октября — −1, показать «просрочено» по отдельному правилу. Если `done=true`, ни один из этих сроков не создаёт напоминания. Составьте таблицу из пяти строк и добавьте колонку `done`: одна и та же дата с разным состоянием даёт разный ответ.",
            "predict": "Что даст условие `days < 2` при 2 днях? `false`: граница ошибочно исключена. А `days <= 2` при −1? `true`: просроченная задача смешана с будущей. Добавьте нижнюю границу 0 и отдельную ветку для прошедшего срока. Предскажите ответ для отсутствующего срока: сравнение не выполняется, выводится сообщение «срок не указан».",
            "error": "«Заменим `≤` на `<`: разница всего один день». Именно день на границе входит в требование «не более». Исправление проверяется тремя соседними значениями, а не одним удобным примером.",
            "transfer": "Школьный кружок принимает заявки до 18:00 включительно. Проверьте 17:59, 18:00 и 18:01. Уточните часовой пояс и что означает «включительно» для секунды 18:00:30 — без этого требование неоднозначно.",
            "project": "Запишите в `ALGORITHM-ru.md` порядок проверок: запись найдена, срок есть, задача не выполнена, срок не прошёл, осталось 0–2 дня. Добавьте таблицу тестов для −1, 0, 1, 2, 3 и `done=true`. Укажите календарную дату и часовой пояс, чтобы опыт можно было повторить.",
            "task": "Исправьте неверное условие `days < 2` и составьте не менее семи тестов, включая отсутствующий срок и выполненную задачу. Доказательство — таблица входов, ожидаемых сообщений и объяснение каждой границы.",
            "review": "Завтра объясните, почему 2 включено, а −1 нет. Через семь дней проверьте границу другого правила. Через месяц сравните тесты с реальной обработкой даты в программе.",
        },
        "kz": {
            "lead": "Шекарадағы шартты тексеріп, көмекші мерзімге дәл екі күн қалғанда үнсіз қалмауын қамтамасыз етеміз.",
            "scene": "Орындалмаған тапсырма мерзіміне екі күннен аспай қалған кезде еске салуға келістіңіз. Бірақ көмекші дәл екі күн қалғанда үндемей, мерзімнен кейін оятады. Қате бір салыстыру таңбасында. Оны болжаммен емес, кестемен табамыз.",
            "terms": "**Шарт** — «иә» не «жоқ» жауабы бар сұрақ. **Тармақталу** жауапқа қарай әрекет таңдайды. **Шекара** — жауап ауысатын мән: мұнда 2 күн. **Шекаралық жағдай** 2-нің өзін және көршілес 1, 3 мәндерін тексереді. **Логикалық мән** — `true` не `false`; **ЖӘНЕ** екі бөліктің де орындалуын, **НЕМЕСЕ** кемінде біреуін талап етеді. **Мерзімі өткен** жағдай — бөлек күй, «тағы нөл күн» емес. Күнді бір күнтізбелік ережемен және бір уақыт белдеуімен салыстырамыз; олар келісілмесе, нәтиже өзгереді.",
            "signal": "орындалмаған ЖӘНЕ 0 ≤ қалған_күн ≤ 2 → еске салу; өтіп кетсе → мерзімі өткен",
            "worked": "`today = 2026-10-09` болсын; бір белдеудегі толық күнтізбелік күндерді санаймыз. 12 қазанға дейін 3 күн — еске салмаймыз; 11 қазанға 2 — саламыз; 10 қазанға 1 — саламыз; 9 қазанға 0 — бүгін саламыз; 8 қазанға −1 — бөлек «мерзімі өтті» хабарын береміз. `done=true` болса, бұл күндердің ешқайсысы еске салу туғызбайды. Бес жолдық кестеге `done` бағанын қосыңыз: бір күннің жауабы тапсырма күйіне де тәуелді.",
            "predict": "`days < 2` шарты дәл 2 күнде не береді? `false`: шекара қате шығарылды. `days <= 2` шарты −1-де ше? `true`: өткен мерзім болашақпен шатасты. Төменгі 0 шекарасын және өткен мерзімге бөлек тармақ қосыңыз. Мерзім мүлде жоқ болса, салыстырмай, «мерзім берілмеген» деңіз.",
            "error": "«`≤` орнына `<` жазсақ, небәрі бір күн ғана өзгереді». Сол бір күн «екі күннен аспайды» талабына кіреді. Түзетуді ыңғайлы бір мәнмен емес, үш көрші мәнмен тексереміз.",
            "transfer": "Үйірме өтінішті 18:00-ге дейін қоса қабылдайды. 17:59, 18:00, 18:01 уақыттарын тексеріңіз. Уақыт белдеуін және 18:00:30 сәтінің мағынасын нақтылаңыз: әйтпесе талап екіұшты.",
            "project": "`ALGORITHM-kz.md` ішіне тексеру ретін жазыңыз: жазба табылды, мерзім бар, тапсырма орындалмаған, мерзім өтпеген, 0–2 күн қалған. −1, 0, 1, 2, 3 және `done=true` үшін тест кестесін қосыңыз. Тәжірибе қайталану үшін күн мен белдеуді көрсетіңіз.",
            "task": "`days < 2` қатесін түзетіп, жоқ мерзім мен орындалған тапсырманы қоса кемінде жеті тест құрастырыңыз. Дәлел — кірістер, күтілген хабарлар және әр шекараның түсіндірмесі.",
            "review": "Ертең 2 неге кіреді, −1 неге кірмейді, түсіндіріңіз. Жеті күннен соң өзге ереженің шекарасын тексеріңіз. Бір айдан кейін тестті нақты күн өңдеу кодымен салыстырыңыз.",
        },
        "en": {
            "lead": "Test a condition at its boundary so the assistant does not miss a task exactly two days before its due date.",
            "scene": "You agreed to remind about unfinished tasks when no more than two days remain. The assistant stays silent at exactly two days, then wakes someone after the deadline. One comparison sign is wrong. Find it with a table rather than a guess.",
            "terms": "A **condition** is a yes/no question. A **branch** chooses actions from the answer. A **boundary** is a value where the answer changes: here 2 days. A **boundary case** tests 2 itself and its neighbours 1 and 3. A **Boolean** is `true` or `false`; **AND** requires both parts and **OR** at least one. **Overdue** means the date has passed; it is a separate state, not “another zero days.” Compare dates under one calendar rule and one time zone, or the same instant can give different results.",
            "signal": "unfinished AND 0 ≤ days_to_due ≤ 2 → remind; past due → overdue",
            "worked": "Let `today = 2026-10-09` and count whole calendar days in one time zone. Due 12 October means 3 days: no reminder; 11 October means 2: remind; 10 October means 1: remind; 9 October means 0: remind today; 8 October means −1: show “overdue” under a separate rule. If `done=true`, none of those dates triggers a reminder. Make a five-row table and add a `done` column: the same date with another state gives another answer.",
            "predict": "What does `days < 2` return at exactly 2 days? `false`: it wrongly excludes the boundary. What does `days <= 2` return at −1? `true`: it mixes an overdue task with future ones. Add a lower bound of 0 and a separate past-due branch. If the due date is missing, do not compare at all; report “no date set.”",
            "error": "“Changing `≤` to `<` affects only one day.” That exact day is included by “no more than two.” Check a fix with three neighbouring values, not one convenient example.",
            "transfer": "A school club accepts applications through 18:00 inclusive. Test 17:59, 18:00, and 18:01. Clarify the time zone and whether 18:00:30 is included: otherwise the requirement is ambiguous.",
            "project": "In `ALGORITHM-en.md`, write checks in order: record found, date present, task unfinished, not overdue, 0–2 days remain. Add tests for −1, 0, 1, 2, 3, and `done=true`. State the calendar date and time zone so the experiment can be repeated.",
            "task": "Repair `days < 2` and prepare at least seven tests including missing date and done task. Evidence: inputs, expected messages, and reasons for each boundary.",
            "review": "Tomorrow explain why 2 is included but −1 is not. In seven days test another rule's boundary. In a month compare the paper cases with real date-handling code.",
        },
    },
    23: {
        "ru": {
            "lead": "Научимся проходить все задачи без копирования команд и докажем, что повторение заканчивается.",
            "scene": "У помощника три задачи. Написать три команды «проверь задачу» легко. Но завтра задач станет тридцать, и копировать команду тридцать раз уже нелепо. Нам нужен один повторяемый шаг и ясный момент остановки.",
            "terms": "**Цикл** повторяет действие, пока есть элементы или выполнено условие. **Итерация** — один проход цикла. **Счётчик** хранит число уже обработанных элементов. **Условие остановки** говорит, когда повторение закончится. **Инвариант цикла** — утверждение, истинное до и после каждого прохода: «все записи до текущей позиции уже проверены, а остальные ещё нет». **Бесконечный цикл** получается, если условие выхода никогда не наступает, например позиция не увеличивается. **Пустой список** — важный тест: цикл должен закончиться без ошибок и дать ноль выполненных задач.",
            "signal": "позиция = 0 → пока позиция < длина → обработать → позиция + 1 → стоп",
            "worked": "Пусть у `t-01`, `t-02`, `t-03` значения `done` равны false, true, false. Начало: `position=0`, `completed=0`. Первый проход: false, счётчик остаётся 0, позиция 1. Второй: true, счётчик 1, позиция 2. Третий: false, счётчик 1, позиция 3. Теперь `position < 3` ложно, ответ 1. После каждого прохода проверяйте инвариант: счётчик равен числу `true` только в уже просмотренной части. Если увеличить позицию до чтения, первая задача пропадёт. Если не увеличить вовсе, цикл не завершится.",
            "predict": "Каков результат для пустого списка? Ноль: условие ложно сразу. Для `true, true, true` — 3. Для `false, false, false` — 0. Предскажите, сколько проходов будет при четырёх записях: ровно четыре, если индекс меняется один раз за проход.",
            "error": "«Чтобы не пропустить последнюю запись, пишем `position <= length`». При позиции, равной длине, записи уже нет: допустимые индексы от 0 до `length − 1`. Исправьте знак и проверьте список из одного элемента.",
            "transfer": "Вместо подсчёта завершённых задач найдите первую невыполненную. Можно ли закончить раньше конца списка? Да, если условие результата уже выполнено; объясните, почему такой ранний выход не подходит для подсчёта всех завершённых.",
            "project": "Запишите в `ALGORITHM-ru.md` цикл подсчёта `done=true` с таблицей трёх проходов. Добавьте инвариант и условие выхода. Проверьте пустой список, один элемент и три исходные задачи. Алгоритм пока читает данные, но не меняет `tasks.json`.",
            "task": "Создайте трассы для `false,true,false` и пустого списка. Намеренно уберите увеличение позиции и укажите, где доказательство остановки ломается. Доказательство: таблица, инвариант и исправленный цикл.",
            "review": "Завтра объясните, почему пустой список безопасен. Через семь дней проследите поиск первого невыполненного. Через месяц найдите цикл в своём коде и проверьте его остановку.",
        },
        "kz": {
            "lead": "Командаларды көшірмей барлық тапсырманы қараймыз және қайталау аяқталатынын дәлелдейміз.",
            "scene": "Көмекшіде үш тапсырма бар. «Тапсырманы тексер» командасын үш рет жазу оңай. Ертең тапсырма отыз болса, оны отыз рет көшіру қисынсыз. Бір қайталанатын қадам мен айқын тоқтау сәті қажет.",
            "terms": "**Цикл** элемент қалғанша не шарт орындалғанша әрекетті қайталайды. **Итерация** — циклдің бір айналымы. **Санағыш** өңделген элементтер санын сақтайды. **Тоқтау шарты** қайталау қашан бітерін көрсетеді. **Цикл инварианты** — әр айналымға дейін және кейін ақиқат болатын пікір: «ағымдағы орынға дейінгі жазбалар тексерілді, кейінгілері әлі жоқ». **Шексіз цикл** шығу шарты ешқашан орындалмаса, мысалы орын өспесе, пайда болады. **Бос тізім** де маңызды тест: цикл қатесіз аяқталып, орындалғандар саны 0 болуы тиіс.",
            "signal": "орын = 0 → орын < ұзындық кезінде → өңдеу → орын + 1 → тоқтау",
            "worked": "`t-01`, `t-02`, `t-03` үшін `done`: false, true, false. Басы: `position=0`, `completed=0`. Бірінші айналым: false, санағыш 0, орын 1. Екінші: true, санағыш 1, орын 2. Үшінші: false, санағыш 1, орын 3. Енді `position < 3` жалған, жауап 1. Әр айналымда инвариантты тексеріңіз: санағыш тек қаралған бөліктегі `true` санымен тең. Орын оқуға дейін өссе, бірінші тапсырма қалып қояды. Мүлде өспесе, цикл бітпейді.",
            "predict": "Бос тізімнің нәтижесі қандай? 0: шарт бірден жалған. `true, true, true` үшін 3; `false, false, false` үшін 0. Төрт жазбаға неше айналым керек? Орын әр айналымда бір рет өссе, дәл төрт.",
            "error": "«Соңғысын өткізбеу үшін `position <= length` жазамыз». Орын ұзындыққа тең кезде ол жерде жазба жоқ: жарамды индекстер 0-ден `length − 1`-ге дейін. Таңбаны түзетіп, бір элементпен тексеріңіз.",
            "transfer": "Санаудың орнына алғашқы орындалмаған тапсырманы табыңыз. Тізім соңына жетпей тоқтауға бола ма? Иә, нәтиже табылса. Бірақ мұндай ерте шығу барлық орындалғанды санауға жарамайды.",
            "project": "`ALGORITHM-kz.md` ішіне `done=true` санау циклін үш айналымдық кестемен жазыңыз. Инвариант пен тоқтау шартын қосыңыз. Бос тізімді, бір элементті және үш бастапқы тапсырманы тексеріңіз. Әзірге алгоритм `tasks.json` файлын өзгертпейді.",
            "task": "`false,true,false` және бос тізім үшін трасса жасаңыз. Орынның өсуін әдейі алып тастап, тоқтау дәлелі қайда бұзылғанын атаңыз. Дәлел: кесте, инвариант, түзетілген цикл.",
            "review": "Ертең бос тізім неге қауіпсіз екенін түсіндіріңіз. Жеті күннен соң алғашқы орындалмағанды іздеуді бақылаңыз. Бір айдан кейін кодыңыздағы циклдің тоқтауын тексеріңіз.",
        },
        "en": {
            "lead": "Visit every task without copying commands and prove that repetition stops.",
            "scene": "The assistant has three tasks. Writing “check task” three times is easy. Tomorrow there may be thirty tasks, and copying the command thirty times would be absurd. We need one repeated step and a clear stopping point.",
            "terms": "A **loop** repeats an action while elements remain or a condition holds. An **iteration** is one pass. A **counter** stores how many elements have been processed. A **stopping condition** says when repetition ends. A **loop invariant** is a statement true before and after every pass: “records before the current position have been checked; the others have not.” An **infinite loop** occurs when the exit condition never arrives, for example when position never advances. An **empty list** is an important test: the loop must stop without error and return zero completed tasks.",
            "signal": "position = 0 → while position < length → process → position + 1 → stop",
            "worked": "For `t-01`, `t-02`, `t-03`, let `done` be false, true, false. Start at `position=0`, `completed=0`. First pass: false, count stays 0, position becomes 1. Second: true, count becomes 1, position 2. Third: false, count stays 1, position 3. Now `position < 3` is false and the answer is 1. Check the invariant after each pass: the count equals the number of true values in the part already visited. Advance before reading and the first task vanishes. Never advance and the loop never ends.",
            "predict": "What does an empty list return? Zero: the condition is false immediately. For `true, true, true`, the result is 3; for `false, false, false`, it is 0. Predict the passes for four records: exactly four if the index advances once per pass.",
            "error": "“To include the last record, write `position <= length`.” At position equal to length there is no record: valid indexes run from 0 to `length − 1`. Fix the sign and test a one-item list.",
            "transfer": "Instead of counting done tasks, find the first unfinished one. Can you stop before the end? Yes, once it is found; explain why early exit cannot count all done tasks.",
            "project": "Add a `done=true` counting loop with a three-pass table to `ALGORITHM-en.md`. Include the invariant and stopping condition. Test empty list, one item, and the original three tasks. This algorithm reads data but does not change `tasks.json` yet.",
            "task": "Trace `false,true,false` and an empty list. Deliberately remove position advancement and show where the stopping proof fails. Evidence: table, invariant, and repaired loop.",
            "review": "Tomorrow explain why an empty list is safe. In seven days trace a search for the first unfinished item. In a month find a loop in your code and check its termination.",
        },
    },
    24: {
        "ru": {
            "lead": "Выделим проверку срока в отдельную функцию с ясным входом, выходом и поведением при ошибке.",
            "scene": "Один и тот же вопрос «пора ли напомнить?» понадобился в списке задач и в карточке задачи. Если скопировать правило дважды, через месяц исправят только одну копию. Нужна одна функция и письменный договор о её поведении.",
            "terms": "**Функция** — названная часть алгоритма, которая получает вход и возвращает результат. **Параметр** — имя входа внутри описания; **аргумент** — конкретное переданное значение. **Возвращаемое значение** — ответ функции, не обязательно сообщение на экране. **Предусловие** описывает, какие входы допустимы. **Постусловие** описывает гарантированный результат для допустимого входа. **Контракт** объединяет эти правила и поведение при ошибке. Функция не обязана быть без побочных эффектов, но для простой проверки срока мы явно запрещаем менять файл.",
            "signal": "вход + предусловие → одна функция → результат + гарантия",
            "worked": "Опишите `should_remind(done, days_to_due)`. Вход: логическое `done` и целое число дней либо отсутствие срока. Выход: одно из `REMIND`, `NOT_YET`, `OVERDUE`, `NO_DATE`, `DONE`. Порядок: если `done=true`, вернуть `DONE`; иначе если срока нет, `NO_DATE`; иначе если дней меньше 0, `OVERDUE`; иначе если не более 2, `REMIND`; иначе `NOT_YET`. Для `(false,2)` ответ `REMIND`, для `(false,3)` — `NOT_YET`, для `(true,2)` — `DONE`. Файл при вызове не изменяется. Это важная гарантия: экран может спрашивать функцию сколько угодно раз.",
            "predict": "Каков ответ `(false,-1)`? `OVERDUE`; `(false,None)`? `NO_DATE`; `(true,None)`? По выбранному порядку `DONE`. Если ученик предпочитает сообщать `NO_DATE` даже для завершённой задачи, это другой допустимый контракт, но его нужно записать и одинаково применять везде.",
            "error": "«Функция получает `days_to_due`, поэтому может молча считать отсутствующий срок нулём». Ноль означает сегодня, а отсутствие означает неизвестно. Смешение даёт ложные напоминания. Исправьте тип входа или добавьте отдельную ветку.",
            "transfer": "Опишите функцию `count_done(tasks)` с входом «список задач» и выходом «целое число». Её предусловие требует, чтобы у каждой записи `done` было логическим значением. Постусловие: результат между 0 и длиной списка; сам список не меняется.",
            "project": "В `ALGORITHM-ru.md` добавьте контракт `should_remind`: таблицу входов, пять возможных выходов, правило отсутствующего срока и гарантию «не меняет файл». Свяжите его с ветвлением урока 22 и тремя проверками границы.",
            "task": "Дайте другому ученику только контракт. Он должен предсказать пять результатов, не глядя на вашу схему. Затем поменяйте порядок двух проверок и найдите вход, на котором ответ меняется. Доказательство — контракт и контрпример.",
            "review": "Завтра различите параметр и аргумент. Через семь дней напишите контракт для другой задачи. Через месяц сверяйте поведение Python-функции с обещанными случаями.",
        },
        "kz": {
            "lead": "Мерзім тексерісін кірісі, шығысы және қате кезіндегі тәртібі анық жеке функцияға бөлеміз.",
            "scene": "«Еске салу керек пе?» сұрағы тапсырма тізімінде де, карточкасында да қажет. Ережені екі рет көшірсеңіз, бір айдан соң біреуін ғана түзетуіңіз мүмкін. Бір функция және оның тәртібі туралы жазбаша келісім керек.",
            "terms": "**Функция** — кіріс алып, нәтиже қайтаратын аталған алгоритм бөлігі. **Параметр** — сипаттама ішіндегі кіріс атауы; **аргумент** — берілген нақты мән. **Қайтарылатын мән** — функция жауабы, міндетті түрде экрандағы хабар емес. **Алғышарт** қандай кіріс жарамды екенін көрсетеді. **Соңғы шарт** жарамды кіріс үшін кепілденетін нәтижені айтады. **Келісім** осы ережелер мен қате кезіндегі тәртіпті біріктіреді. Функцияның жанама әсері болуы мүмкін, бірақ мерзімді тексеру функциясына файлды өзгертпеуді айқын талап етеміз.",
            "signal": "кіріс + алғышарт → бір функция → нәтиже + кепілдік",
            "worked": "`should_remind(done, days_to_due)` сипаттаңыз. Кіріс: логикалық `done` және бүтін қалған күн саны не мерзімнің жоқтығы. Шығыс: `REMIND`, `NOT_YET`, `OVERDUE`, `NO_DATE`, `DONE`. Реті: `done=true` болса, `DONE`; мерзім жоқ болса, `NO_DATE`; күн теріс болса, `OVERDUE`; 2-ден аспаса, `REMIND`; өзгеше болса, `NOT_YET`. `(false,2)` үшін `REMIND`, `(false,3)` үшін `NOT_YET`, `(true,2)` үшін `DONE`. Шақырғанда файл өзгермейді: экран функциядан қанша рет сұраса да қауіпсіз.",
            "predict": "`(false,-1)` жауабы? `OVERDUE`; `(false,None)`? `NO_DATE`; `(true,None)`? Таңдалған реттілік бойынша `DONE`. Біреу орындалған тапсырмада да `NO_DATE` дегенді қаласа, ол өзге келісім; оны жазып, барлық жерде бірдей қолдану қажет.",
            "error": "«Мерзім жоқ болса, оны 0 күн деп алайық». Нөл — бүгін, ал жоқ мән — белгісіз. Екеуін араластыру жалған еске салу туғызады. Кіріс түрін не жеке тармақты түзетіңіз.",
            "transfer": "`count_done(tasks)` функциясын сипаттаңыз: кірісі тапсырма тізімі, шығысы бүтін сан. Алғышарт: әр жазбаның `done` мәні логикалық. Соңғы шарт: нәтиже 0 мен тізім ұзындығы арасында; тізім өзгермейді.",
            "project": "`ALGORITHM-kz.md` ішіне `should_remind` келісімін қосыңыз: кірістер, бес шығыс, мерзім жоқ ережесі және «файлды өзгертпейді» кепілдігі. 22-сабақтағы шекара тексерісіне байланыстырыңыз.",
            "task": "Өзге оқушыға тек келісімді беріңіз. Ол сызбаға қарамай бес нәтижені табуы тиіс. Содан кейін екі тексеріс ретін ауыстырып, жауап өзгеретін кірісті табыңыз. Дәлел — келісім мен қарсы мысал.",
            "review": "Ертең параметр мен аргументті ажыратыңыз. Жеті күннен соң басқа функция келісімін жазыңыз. Бір айдан кейін Python-функцияның тәртібін осы уәделермен салыстырыңыз.",
        },
        "en": {
            "lead": "Extract the due-date check as one function with clear input, output, and failure behaviour.",
            "scene": "The same “should we remind?” question appears in the task list and on a task card. Copy the rule twice and a later fix may reach only one copy. We need one function and a written contract for its behaviour.",
            "terms": "A **function** is a named part of an algorithm that accepts input and returns a result. A **parameter** names an input inside its definition; an **argument** is the concrete value passed in. A **return value** is the answer, not necessarily a screen message. A **precondition** says which inputs are valid. A **postcondition** promises a result for a valid input. A **contract** collects these rules and the behaviour on failure. Functions may have side effects, but for a simple date check we explicitly forbid changing the file.",
            "signal": "input + precondition → one function → result + guarantee",
            "worked": "Describe `should_remind(done, days_to_due)`. Input: Boolean `done` and an integer day count or missing date. Output: one of `REMIND`, `NOT_YET`, `OVERDUE`, `NO_DATE`, `DONE`. Order: if `done=true`, return `DONE`; else if date missing, `NO_DATE`; else if days below 0, `OVERDUE`; else if no more than 2, `REMIND`; otherwise `NOT_YET`. `(false,2)` gives `REMIND`, `(false,3)` gives `NOT_YET`, `(true,2)` gives `DONE`. Calling it does not change the file, so the screen can ask repeatedly.",
            "predict": "What does `(false,-1)` return? `OVERDUE`; `(false,None)`? `NO_DATE`; `(true,None)`? Under this order, `DONE`. Someone could choose `NO_DATE` for a done task instead, but that is a different contract that must be written and applied consistently.",
            "error": "“If the date is absent, silently treat it as zero days.” Zero means today; absence means unknown. Mixing them creates false reminders. Repair the input type or add a separate branch.",
            "transfer": "Specify `count_done(tasks)` with task-list input and integer output. Its precondition requires Boolean `done` for every record. Its postcondition says the result is between 0 and list length and the list remains unchanged.",
            "project": "Add the `should_remind` contract to `ALGORITHM-en.md`: inputs, five outputs, missing-date rule, and “does not change file” guarantee. Link it to lesson 22's boundary cases.",
            "task": "Give another learner only the contract. They must predict five results without your diagram. Then swap two checks and find an input where the answer changes. Evidence: the contract and a counterexample.",
            "review": "Tomorrow distinguish parameter from argument. In seven days write a contract for another task. In a month compare Python behaviour with the promised cases.",
        },
    },
    25: {
        "ru": {
            "lead": "Научимся сначала доказывать правильность алгоритма, а затем сравнивать работу на маленьком и большом списке.",
            "scene": "В трёх задачах одинаковые `id` можно заметить взглядом. Но если записей тысяча, как проверить их быстро и не пропустить повтор? Скорость важна только после того, как мы точно определили, что считать повтором и какой ответ нужен.",
            "terms": "**Корректность** означает, что алгоритм выполняет записанный договор для всех допустимых входов, а не только для одного примера. **Контрпример** — вход, на котором обещание ломается. **Эффективность** сравнивает нужную работу и память при росте входа. **Размер входа** `n` — здесь число задач. **Линейный проход** смотрит каждую запись примерно один раз. **Квадратичный рост** появляется при сравнении каждой записи с каждой: число пар `n(n−1)/2`. **Множество** — коллекция уникальных значений, которая обычно позволяет быстро проверить, встречалось ли `id`; она требует дополнительной памяти. Сложность описывает рост, а не обещает секунды на конкретном ноутбуке.",
            "signal": "сначала договор и контрпримеры → затем число действий и память",
            "worked": "Способ A: для каждой задачи сравнить её `id` со всеми следующими. При 4 задачах это 6 пар, при 10 — 45. Способ B: идти слева направо с пустым множеством `seen`; если `id` уже там, сообщить о повторе, иначе добавить его. Для `t-01,t-02,t-03,t-02` шаги B: добавить `t-01`, `t-02`, `t-03`, на четвёртом обнаружить повтор. При 4 задачах проверяется не более 4 поступающих значений, но нужно место для уже встреченных `id`. Сравнивать следует именно `id`, не названия: два разных задания могут называться одинаково.",
            "predict": "Что будет для пустого списка и для одного `id`? Повторов нет у обоих способов. А для `t-01,t-01`? Повтор на втором. Если `id` отличаются только регистром (`t-01` и `T-01`), результат зависит от заранее записанного правила нормализации; молча менять регистр нельзя.",
            "error": "«Способ B быстрее на любом устройстве и при любом входе». Он обычно делает меньше сравнений при больших списках, но хранит множество и зависит от реализации. Выберите способ по требованиям и измерьте на реальных размерах после реализации, не выдавая учебную модель за бенчмарк.",
            "transfer": "Для списка уже отсортированных сроков нужно найти ближайший. Подумайте, нужен ли полный просмотр, если порядок гарантирован. Сначала докажите гарантию сортировки; иначе ранний выход может дать неверный ответ.",
            "project": "В `ALGORITHM-ru.md` добавьте оба способа проверки повторных `id`, таблицу числа пар для `n=1,4,10` и случаи `t-01,t-02,t-01`, пустой список и одинаковые названия с разными `id`. Запишите компромисс: меньше проверок ценой дополнительной памяти.",
            "task": "Попросите одноклассника найти контрпример алгоритму, который сравнивает названия вместо `id`. Затем он должен обосновать корректность способа B: после каждого шага `seen` содержит ровно уже просмотренные идентификаторы. Доказательство — трасса и объяснение инварианта.",
            "review": "Завтра восстановите шесть пар для четырёх записей. Через семь дней оцените проверки для пяти записей. Через месяц сравните бумажный прогноз с измерением своей программы.",
        },
        "kz": {
            "lead": "Әуелі алгоритмнің дұрыстығын дәлелдеп, содан кейін шағын және үлкен тізімдегі жұмысын салыстырамыз.",
            "scene": "Үш тапсырмадағы бірдей `id` көзге бірден түседі. Ал жазба мың болса, қайталауды қалай тез әрі сенімді табамыз? Жылдамдықты талқыламас бұрын, нені қайталау деп санайтынымызды және қандай жауап күтетімізді анықтаймыз.",
            "terms": "**Дұрыстық** — алгоритмнің бір мысалда емес, барлық жарамды кірісте жазылған келісімді орындауы. **Қарсы мысал** — уәде бұзылатын кіріс. **Тиімділік** — кіріс өскендегі әрекет пен жад шығынын салыстыру. **Кіріс өлшемі** `n` — мұнда тапсырма саны. **Сызықтық өту** әр жазбаны шамамен бір рет қарайды. **Квадраттық өсу** әр жазбаны басқаларымен салыстырғанда пайда болады: жұп саны `n(n−1)/2`. **Жиын** — қайталанбайтын мәндер коллекциясы, онда `id` бұрын кездескенін әдетте тез тексеруге болады; бірақ қосымша жад қажет. Күрделілік өсу сипатын көрсетеді, нақты ноутбуктағы секундқа кепіл емес.",
            "signal": "әуелі келісім мен қарсы мысал → кейін әрекет саны мен жад",
            "worked": "A тәсілі: әр тапсырманың `id` мәнін кейінгілермен салыстыру. 4 тапсырмада 6 жұп, 10 тапсырмада 45 жұп. B тәсілі: бос `seen` жиынымен солдан оңға өту; `id` ішінде болса, қайталау табылды, болмаса қосу. `t-01,t-02,t-03,t-02` үшін B: алғашқы үшеуін қосып, төртіншісінде қайталауды табамыз. 4 жазбада ең көбі 4 кіріс мәні тексеріледі, бірақ бұрынғыларды сақтау керек. Атауды емес, `id` салыстырыңыз: екі бөлек тапсырманың атауы бірдей болуы мүмкін.",
            "predict": "Бос тізімде және бір `id` үшін не шығады? Екеуінде де қайталау жоқ. `t-01,t-01` үшін? Екіншісінде табылады. `t-01` мен `T-01` болса, жауап алдын ала жазылған регистр ережесіне тәуелді; регистрді үнсіз ауыстырмаңыз.",
            "error": "«B кез келген құрылғыда, кез келген кірісте жылдам». Үлкен тізімде әдетте салыстыру аз, бірақ жиынға жад кетеді және іске асыру маңызды. Таңдауды талапқа сүйеніп жасаңыз, код дайын болғанда нақты өлшеңіз; қағаз үлгіні бенчмарк деп атамаңыз.",
            "transfer": "Мерзімдері сұрыпталған тізімнен ең жақынын іздеңіз. Рет кепілденсе, түгел қарау керек пе? Әуелі сұрыптау кепілдігін дәлелдеңіз, әйтпесе ерте тоқтау қате жауап беруі мүмкін.",
            "project": "`ALGORITHM-kz.md` ішіне қайталанатын `id` табудың екі тәсілін, `n=1,4,10` жұп санын және `t-01,t-02,t-01`, бос тізім, атауы бірдей бірақ `id` бөлек жағдайларын енгізіңіз. Мәмілені жазыңыз: азырақ тексеру үшін қосымша жад.",
            "task": "Сыныптасыңыз атауды салыстыратын қате алгоритмге қарсы мысал тапсын. Кейін B тәсілін негіздесін: әр қадамнан соң `seen` дәл қаралған идентификаторларды сақтайды. Дәлел — трасса мен инвариант.",
            "review": "Ертең төрт жазбаға алты жұпты қалпына келтіріңіз. Жеті күннен соң бес жазбаның салыстыруын есептеңіз. Бір айдан кейін қағаз болжамды бағдарлама өлшемімен салыстырыңыз.",
        },
        "en": {
            "lead": "Prove an algorithm correct first, then compare its work on small and large lists.",
            "scene": "Duplicate `id` values are easy to spot among three tasks. What about a thousand? We need a reliable check. Speed matters only after we define what counts as a duplicate and what answer is required.",
            "terms": "**Correctness** means an algorithm meets its written contract for every valid input, not just one example. A **counterexample** is an input that breaks the promise. **Efficiency** compares work and memory as input grows. **Input size** `n` is the task count here. A **linear scan** visits each record roughly once. **Quadratic growth** occurs when each record is compared with every other: there are `n(n−1)/2` pairs. A **set** stores unique values and usually checks whether an `id` has appeared quickly, at the cost of extra memory. Complexity describes growth, not seconds guaranteed on one laptop.",
            "signal": "contract and counterexamples first → operations and memory second",
            "worked": "Method A: compare each task `id` with every later one. Four tasks give 6 pairs; ten give 45. Method B: scan left to right with empty set `seen`; if `id` is already in it, report duplicate, otherwise add it. For `t-01,t-02,t-03,t-02`, B adds the first three and finds a duplicate on the fourth. Four records require at most four arriving values to be checked, but earlier IDs occupy memory. Compare `id`, not titles: distinct tasks may have the same title.",
            "predict": "What about an empty list or one `id`? Neither has a duplicate. For `t-01,t-01`, the second is a duplicate. For `t-01` and `T-01`, the answer depends on a documented case rule; do not silently normalise case.",
            "error": "“B is faster on every device and every input.” It usually needs fewer comparisons on large lists, but uses memory and depends on implementation. Choose by requirements and measure realistic sizes after writing code; a paper model is not a benchmark.",
            "transfer": "Find the nearest due date in a list said to be sorted. Can you stop early? First establish that sorted order is guaranteed; otherwise early exit can give a wrong answer.",
            "project": "In `ALGORITHM-en.md`, document both duplicate-ID checks, pair counts for `n=1,4,10`, and cases `t-01,t-02,t-01`, empty list, and equal titles with distinct IDs. Record the trade-off: fewer checks for extra memory.",
            "task": "Ask a classmate for a counterexample to comparing titles instead of IDs. They then justify B: after each step, `seen` contains exactly the IDs already visited. Evidence: a trace and invariant explanation.",
            "review": "Tomorrow reconstruct six pairs for four records. In seven days count comparisons for five. In a month compare the paper prediction with a measurement of your program.",
        },
    },
    26: {
        "ru": {
            "lead": "Соберём бумажную версию 0.3 помощника и проверим её на обычных, граничных и неожиданных данных.",
            "scene": "Друг получил только ваш файл `ALGORITHM-ru.md` и три задачи версии 0.2. Он хочет понять, когда придёт напоминание и сколько задач завершено. Если ему приходится спрашивать вас о значении пустого срока, алгоритм ещё не готов к переводу на Python.",
            "terms": "**Спецификация** — записанное обещание о входах, выходах и ошибках. **Тестовый случай** — конкретный вход с ожидаемым ответом. **Регрессия** — возвращение старой ошибки после изменения. **Эталон** — заранее записанный ожидаемый результат, а не ответ, придуманный после выполнения. **Приёмка** — решение о готовности по наблюдаемым критериям. **Версия 0.3** здесь означает проверенные бумажные алгоритмы: программа появится в следующем блоке. Файл `tasks.json` версии 0.2 остаётся источником трёх вымышленных записей; сроки в этом блоке заданы отдельными тестовыми карточками, а не незаметно добавлены в старый формат.",
            "signal": "договор → трасса → границы → инвариант → чужая проверка → версия 0.3",
            "worked": "Проведите `t-01` через все правила. Карточка теста говорит `done=false`, `days_to_due=2`; функция возвращает `REMIND`. Для `t-02` из исходного файла `done=true`, даже если карточка задаёт 0 дней, ответ `DONE`. Для `t-03` без карточки срока ответ `NO_DATE`. Подсчёт исходного списка даёт ровно 1 завершённую задачу. Затем добавьте в тестовый список четвёртую вымышленную запись с повторным `id=t-02`: проверка уникальности должна остановить её до напоминания. Не меняйте исходные три записи ради удобного ожидаемого ответа.",
            "predict": "Перед чтением таблицы ответов запишите результаты для дней −1, 0, 1, 2, 3 при `done=false`, затем для тех же дней при `done=true`. Должны получиться `OVERDUE, REMIND, REMIND, REMIND, NOT_YET` и пять `DONE`. Если срок отсутствует, `NO_DATE`; если задача уже выполнена и срок отсутствует, по выбранному контракту `DONE`.",
            "error": "«Три исходные задачи открылись, значит 0.3 готова». Открытие проверяет формат 0.2, но не ветви, остановку цикла, повторные идентификаторы или понимание другого человека. Покажите не один удачный экран, а набор контрпримеров и исправлений.",
            "transfer": "Пусть школьный кружок заменил дни на часы и напоминает при 48 часах включительно. Какие части схемы переиспользуются, а какие требования надо переписать? Объясните, почему 2 календарных дня не всегда равны ровно 48 часам при разном времени суток.",
            "project": "Сдайте `ALGORITHM-ru.md`, таблицу трасс, `cases.json` с вымышленными входами и журнал одного исправления. В README версии 0.3 укажите, что алгоритм на бумаге ещё не запускается и не отправляет уведомления. Другой ученик должен по этим материалам получить те же ожидаемые ответы без ваших подсказок.",
            "task": "Проверьте 10 пунктов: (1) цель и вход; (2) выход и ошибки; (3) состояние до/после; (4) порядок шагов; (5) случаи −1/0/1/2/3; (6) отсутствие срока; (7) завершённая задача; (8) пустой список и остановка; (9) повторный `id` и инвариант; (10) независимый перенос на 48 часов. Для зачёта нужно 8/10 сейчас, включая пункты 9 и 10, и 7/10 на новом примере через семь дней. Покажите исправление каждого проваленного пункта, затем повторите равносильную задачу.",
            "review": "Завтра восстановите пять ответов функции. Через семь дней выполните новую приёмку без страницы. Через месяц сопоставьте обещания 0.3 с Python-версией 1.0 и отметьте расхождения до публикации.",
        },
        "kz": {
            "lead": "Көмекшінің қағаздағы 0.3 нұсқасын құрастырып, әдеттегі, шекаралық және тосын дерекпен тексереміз.",
            "scene": "Досыңыз тек `ALGORITHM-kz.md` және 0.2 нұсқасындағы үш тапсырманы алды. Ол еске салу қашан шығатынын және қанша тапсырма орындалғанын білгісі келеді. Бос мерзімнің мағынасын сізден сұрауға мәжбүр болса, алгоритм Python-ға көшуге дайын емес.",
            "terms": "**Сипаттама** — кіріс, шығыс және қате туралы жазылған уәде. **Тест жағдайы** — нақты кіріс пен күтілген жауап. **Регрессия** — өзгерістен кейін ескі қатенің қайта шығуы. **Үлгі нәтиже** — орындалмай тұрып жазылған күтілген жауап. **Қабылдау** — бақыланатын өлшемге сүйеніп дайындықты шешу. Мұндағы **0.3 нұсқасы** — қағазда тексерілген алгоритмдер; бағдарлама келесі бөлімде болады. 0.2 нұсқасындағы `tasks.json` үш ойдан шығарылған жазбаның көзі болып қалады; мерзімдер ескі форматқа жасырын қосылмай, бөлек тест карточкаларында беріледі.",
            "signal": "келісім → трасса → шекара → инвариант → өзге адамның тексеруі → 0.3",
            "worked": "`t-01` жазбасын барлық ережемен өткізіңіз. Тест карточкасы `done=false`, `days_to_due=2` дейді: функция `REMIND` қайтарады. Бастапқы файлдағы `t-02` үшін `done=true`; карточка 0 күн десе де жауап `DONE`. `t-03` үшін мерзім карточкасы жоқ: `NO_DATE`. Бастапқы тізімдегі орындалғандар саны дәл 1. Содан кейін тек тест тізіміне `id=t-02` қайталанған төртінші ойдан шығарылған жазбаны қосыңыз: бірегейлік тексерісі оны еске салудан бұрын тоқтатуы керек. Күтілген жауапқа лайықтап бастапқы үш жазбаны өзгертпеңіз.",
            "predict": "Жауап кестесін ашпай тұрып `done=false` үшін −1, 0, 1, 2, 3 күн нәтижесін жазыңыз: `OVERDUE, REMIND, REMIND, REMIND, NOT_YET`. `done=true` болса, бес нәтиже де `DONE`. Мерзім жоқ болса, `NO_DATE`; ал тапсырма дайын әрі мерзім жоқ болса, таңдалған келісім бойынша `DONE`.",
            "error": "«Үш бастапқы тапсырма ашылды, демек 0.3 дайын». Ашу 0.2 форматын ғана тексереді; тармақтарды, циклдің тоқтауын, қайталанған идентификаторды және өзге адамның түсінуін тексермейді. Бір сәтті экран орнына қарсы мысалдар мен түзетулерді көрсетіңіз.",
            "transfer": "Үйірме күн орнына сағат қолданып, 48 сағат қалғанда қоса еске салады. Сызбаның қай бөлігі сақталады, қай талап қайта жазылады? Тәулік ішіндегі уақыт әртүрлі болса, екі күнтізбелік күн әрдайым дәл 48 сағат емес екенін түсіндіріңіз.",
            "project": "`ALGORITHM-kz.md`, трасса кестесі, ойдан шығарылған кірістері бар `cases.json` және бір түзету журналы тапсырылады. 0.3 нұсқасының README файлында қағаз алгоритмі әлі іске қосылмайтынын және хабар жібермейтінін жазыңыз. Басқа оқушы сізсіз сол күтілген жауаптарды табуы керек.",
            "task": "10 тармақты тексеріңіз: (1) мақсат пен кіріс; (2) шығыс пен қате; (3) бұрынғы/кейінгі күй; (4) қадам реті; (5) −1/0/1/2/3; (6) мерзім жоқ; (7) дайын тапсырма; (8) бос тізім және тоқтау; (9) қайталанған `id` пен инвариант; (10) 48 сағатқа тәуелсіз көшіру. Қазір 8/10, міндетті түрде 9 және 10, жеті күннен кейін жаңа мысалда 7/10 қажет. Қате тармақты түзетіп, ұқсас өзге есепте қайталаңыз.",
            "review": "Ертең функцияның бес жауабын жатқа айтыңыз. Жеті күннен соң бетті ашпай жаңа қабылдау тексерісін орындаңыз. Бір айдан кейін 0.3 уәделерін Python 1.0 нұсқасымен салыстырып, айырманы жариялауға дейін түзетіңіз.",
        },
        "en": {
            "lead": "Assemble the assistant's paper version 0.3 and test it on ordinary, boundary, and surprising inputs.",
            "scene": "A friend receives only `ALGORITHM-en.md` and the three tasks from version 0.2. They want to know when a reminder appears and how many tasks are done. If they must ask you what a missing date means, the algorithm is not ready to become Python.",
            "terms": "A **specification** is a written promise about inputs, outputs, and failures. A **test case** is a concrete input with expected output. A **regression** is an old fault returning after a change. An **oracle** is an expected answer written before execution, not invented afterwards. **Acceptance** decides readiness using observable criteria. **Version 0.3** here means tested paper algorithms; executable code arrives in the next block. Version 0.2 `tasks.json` remains the source of three fictional records; dates are supplied on separate test cards, not silently added to the old format.",
            "signal": "contract → trace → boundary → invariant → independent check → version 0.3",
            "worked": "Take `t-01` through the rules. Its test card says `done=false`, `days_to_due=2`; the function returns `REMIND`. Original `t-02` has `done=true`, so even a test card saying 0 days produces `DONE`. `t-03` has no due-date card: return `NO_DATE`. Counting the original list gives exactly 1 completed task. Then add a fourth fictional record with duplicate `id=t-02` only to the test list: the uniqueness check must reject it before reminding. Do not alter the original three records to force a convenient answer.",
            "predict": "Before viewing answers, predict outputs for −1, 0, 1, 2, 3 days with `done=false`, then the same days with `done=true`. They should be `OVERDUE, REMIND, REMIND, REMIND, NOT_YET` and five `DONE` answers. A missing date gives `NO_DATE`; a done task with missing date gives `DONE` under our chosen contract.",
            "error": "“The three original tasks opened, so 0.3 is ready.” Opening checks the 0.2 format but not branches, loop termination, duplicate identifiers, or another person's understanding. Show counterexamples and repairs, not one successful screen.",
            "transfer": "A school club switches from days to hours and reminds at 48 hours inclusive. Which parts of your plan can be reused, and which requirement must change? Explain why two calendar days are not always exactly 48 hours if times of day differ.",
            "project": "Submit `ALGORITHM-en.md`, trace tables, `cases.json` with fictional inputs, and a log of one repair. The version 0.3 README must say the paper algorithm does not yet run or send notifications. Another learner should obtain the same expected answers without your help.",
            "task": "Check ten points: (1) goal and input; (2) output and failures; (3) state before/after; (4) step order; (5) −1/0/1/2/3 cases; (6) missing date; (7) done task; (8) empty list and stopping; (9) duplicate `id` and invariant; (10) independent transfer to 48 hours. Passing requires 8/10 now, including 9 and 10, and 7/10 on a new case after seven days. Repair each failed item, then retry an equivalent problem.",
            "review": "Tomorrow recall the function's five answers. In seven days perform a new acceptance check without this page. In a month compare 0.3 promises with Python 1.0 and repair differences before release.",
        },
    },
}

DEEP = {
    19: {
        "ru": "Возьмите четыре листка: `id`, `done`, срок и ответ. Название задачи держите отдельно. Попросите другого ученика сыграть роль помощника: он получает листки по одному и должен назвать, какой листок ему нужен следующим. Уберите листок со сроком: ученик должен остановиться, а не угадывать дату. Поменяйте название при том же `id`: результат не должен измениться. Так вы проверите, какие сведения действительно влияют на решение. Запишите это как правило до того, как рисовать экран или писать код.",
        "kz": "Төрт қағаз алыңыз: `id`, `done`, мерзім және жауап. Тапсырма атауын бөлек ұстаңыз. Басқа оқушы көмекші рөлін атқарсын: қағаздарды біртіндеп алып, келесі керегін атайды. Мерзім қағазын алып тастаңыз: ол күнді болжай салмай, тоқтауы керек. Бірдей `id` кезінде атауды өзгертіңіз: нәтиже өзгермеуі тиіс. Осылайша шешімге қай дерек әсер ететінін анықтап, экран салмай тұрып ереже жазыңыз.",
        "en": "Take four cards: `id`, `done`, due date, and output. Keep the task title on a separate card. Let a partner act as the assistant: hand over cards one by one, and ask which card is needed next. Remove the date card: the partner must stop rather than guess. Change the title while keeping the same `id`: the result should not change. This reveals which information actually affects the decision. Write the rule down before drawing a screen or writing code.",
    },
    20: {
        "ru": "Нарисуйте три клетки для числа очков: «было», «действие», «стало». При `3 − 2 + 4` сначала запишите `3 → 1`, затем `1 → 5`; не перепрыгивайте сразу к пяти. Рядом нарисуйте две карточки задачи с одним `id`: `done=false` до действия «отметить выполненной» и `done=true` после. Название остаётся тем же. Спросите: что произойдёт, если отметку поставить второй раз? Наш договор должен сказать, останется ли `true`, иначе состояние непредсказуемо.",
        "kz": "Ұпайға үш ұяшық сызыңыз: «бұрын», «әрекет», «кейін». `3 − 2 + 4` үшін әуелі `3 → 1`, содан соң `1 → 5` жазыңыз; бірден беске секірмеңіз. Қасына `id` бірдей екі карточка салыңыз: «орындалды» әрекетіне дейін `done=false`, кейін `done=true`. Атау өзгермейді. Белгіні екінші рет қойса не болады? Келісімде `true` күйінде қала ма, соны көрсетіңіз, әйтпесе күй анық болмайды.",
        "en": "Draw three score boxes: before, action, after. For `3 − 2 + 4`, record `3 → 1` and then `1 → 5`; do not jump straight to five. Beside them draw two cards for the same task `id`: `done=false` before “mark complete” and `done=true` afterwards. Its title stays unchanged. Ask what a second completion action should do. The contract must say whether `true` remains `true`; otherwise the state is ambiguous.",
    },
    21: {
        "ru": "Устройте настольный прогон: один ученик держит карточку `count`, другой выполняет инструкции `+1`, «показать», `+1` строго слева направо. После каждого шага впишите в таблицу номер шага, новое значение и показанный ответ. Затем поменяйте местами «показать» и последнее `+1`: конечный `count` останется равным 2, но пользователь увидит другое число. Это и есть причина, по которой одного итогового состояния мало для проверки программы с выводом.",
        "kz": "Үстелдегі сынақ жасаңыз: бір оқушы `count` карточкасын ұстасын, екіншісі `+1`, «көрсету», `+1` нұсқауларын солдан оңға дәл орындайды. Әр қадамнан кейін қадам нөмірін, жаңа мәнді және көрсетілген жауапты кестеге түсіріңіз. Сосын «көрсету» мен соңғы `+1` орындарын ауыстырыңыз: соңғы `count` бәрібір 2, бірақ адам басқа сан көреді. Демек экранға шығатын бағдарламада тек соңғы күйді тексеру жеткіліксіз.",
        "en": "Run a table-top trace: one learner holds the `count` card, another follows `+1`, “display,” `+1` exactly from left to right. After every step, write the step number, current value, and visible output in a table. Swap “display” with the final `+1`: the final `count` remains 2, yet the person sees a different number. That is why checking only the final state cannot validate a program with visible output.",
    },
    22: {
        "ru": "Поставьте на нарисованной числовой прямой точки −1, 0, 1, 2, 3. Закрасьте только отрезок от 0 до 2, включая концы. Теперь переведите рисунок в условие `0 ≤ days_to_due ≤ 2`: каждая часть условия отвечает за один край. Уберите левую часть и проверьте −1; уберите правую и проверьте 3. Верните обе части. Отдельно положите карточку `done=true` поверх точки 1: напоминания уже нет. Так видны две независимые причины изменить ответ.",
        "kz": "Сан сәулесіне −1, 0, 1, 2, 3 нүктелерін белгілеңіз. Тек 0 мен 2 арасын, шеттерін қоса бояңыз. Суретті `0 ≤ days_to_due ≤ 2` шартына айналдырыңыз: шарттың әр бөлігі бір шекті қорғайды. Сол бөлігін алып, −1-ді; оң бөлігін алып, 3-ті тексеріңіз. Екеуін қайта қосыңыз. Содан кейін 1 нүктесіне `done=true` карточкасын қойыңыз: еске салу жоқ. Жауапты өзгертетін екі бөлек себепті осылай көресіз.",
        "en": "Mark −1, 0, 1, 2, and 3 on a number line. Shade only the interval from 0 through 2, including both ends. Translate the picture into `0 ≤ days_to_due ≤ 2`: each part protects one boundary. Remove the left part and test −1; remove the right part and test 3. Restore both. Then place a `done=true` card over point 1: there is still no reminder. These are two independent reasons for a different answer.",
    },
    23: {
        "ru": "Разложите три карточки `false, true, false` в ряд и передвигайте фишку позиции только вправо. До каждого шага скажите вслух, сколько карточек уже обработано и сколько `true` найдено; после шага проверьте оба числа. На позиции 3 необработанных карточек нет: дальше двигаться нельзя. Повторите с пустым рядом: позиция уже равна длине, значит цикл не начинается. Эти два опыта показывают и инвариант, и остановку без необходимости верить рисунку на слово.",
        "kz": "`false, true, false` үш карточкасын қатар қойып, орын фишкасын тек оңға жылжытыңыз. Әр қадам алдында неше карточка қаралғанын және неше `true` табылғанын айтыңыз; қадамнан кейін екеуін де тексеріңіз. 3-орында қаралмаған карточка қалмайды: әрі жүруге болмайды. Бос қатармен қайталаңыз: орын бірден ұзындыққа тең, цикл басталмайды. Осы екі тәжірибе инвариантты да, тоқтауды да көрсетеді.",
        "en": "Line up three cards `false, true, false` and move a position token only to the right. Before each step, say how many cards have been processed and how many `true` values have been found; check both after the step. At position 3 nothing is left, so the token must stop. Repeat with an empty line: position already equals length, and the loop never starts. These two experiments show both the invariant and termination.",
    },
    24: {
        "ru": "Пусть одноклассник играет роль функции: вы передаёте карточки `done` и `days_to_due`, он возвращает ровно одну карточку ответа. Начните с `done=true, days_to_due` отсутствует: ответ `DONE`, потому что завершённость проверяется раньше срока. Затем передайте `done=false, days_to_due` отсутствует: теперь `NO_DATE`. Нарисуйте стрелку возврата для каждого случая. Если партнёр пытается вернуть два ответа или молчит, уточните договор функции. Функция не должна изменять исходную задачу ради ответа.",
        "kz": "Сыныптасыңыз функция болсын: оған `done` және `days_to_due` карточкаларын беріңіз, ол дәл бір жауап карточкасын қайтарады. Алдымен `done=true`, мерзім жоқ: жауап `DONE`, өйткені орындалу мерзімнен бұрын тексеріледі. Кейін `done=false`, мерзім жоқ: енді `NO_DATE`. Әр жағдайға қайтару жебесін салыңыз. Серігіңіз екі жауап берсе немесе үндемесе, функция келісімін нақтылаңыз. Жауап алу үшін бастапқы тапсырманы өзгертуге болмайды.",
        "en": "Let a partner act as a function: hand over `done` and `days_to_due` cards, and ask for exactly one output card. Start with `done=true` and no date: return `DONE`, because completion is checked before the date. Then try `done=false` and no date: return `NO_DATE`. Draw a return arrow for each case. If the partner returns two answers or none, clarify the function contract. The function must not modify the source task merely to produce an answer.",
    },
    25: {
        "ru": "Выпишите четыре `id`: `t-01, t-02, t-03, t-02`. Для попарной проверки нарисуйте пары позиций 1–2, 1–3, 1–4, 2–3, 2–4, 3–4; повтор обнаружится на пятой паре. Теперь ведите множество `seen`: после первых трёх шагов там три значения, на четвёртом `t-02` уже есть. При подсчёте работы называйте, что именно считаете: сравнения пар или проверки принадлежности. Даже при одном и том же результате цифры 5 и 4 относятся к разным операциям; скорость на устройстве предстоит измерить позже.",
        "kz": "Төрт `id` жазыңыз: `t-01, t-02, t-03, t-02`. Жұппен тексеруде 1–2, 1–3, 1–4, 2–3, 2–4, 3–4 орын жұптарын сызыңыз; қайталау бесінші жұпта табылады. Енді `seen` жиынын жүргізіңіз: алғашқы үш қадамнан кейін үш мән бар, төртіншісінде `t-02` бұрыннан кездеседі. Жұмысты санағанда нені санайтыныңызды атаңыз: жұп салыстыру ма, жиында барын тексеру ме. 5 пен 4 әртүрлі әрекет саны; нақты жылдамдық кейін өлшенеді.",
        "en": "Write four IDs: `t-01, t-02, t-03, t-02`. For pairwise checking draw position pairs 1–2, 1–3, 1–4, 2–3, 2–4, 3–4; the duplicate appears in the fifth comparison. Now track `seen`: it holds three values after three steps, and `t-02` is already present at step four. When comparing work, name the operation being counted: pair comparisons or membership checks. The numbers 5 and 4 refer to different operations; actual device speed still needs measuring later.",
    },
    26: {
        "ru": "Проведите маленькую защиту без автора. Партнёр открывает `cases.json`, закрывает столбец `expected` и заполняет его по вашим правилам. Затем сравнивает с эталоном и подчёркивает первое расхождение, а не просто число правильных ответов. Попросите его придумать ещё один случай, которого нет в файле: например, выполненная задача с просроченным сроком. Если ответ нельзя вывести из договора, вернитесь к уроку 24 и дополните порядок проверок. Сохраните найденное расхождение и исправление в журнале проекта.",
        "kz": "Авторсыз шағын қорғау өткізіңіз. Серігіңіз `cases.json` файлын ашып, `expected` бағанын жауып, сіздің ережемен толтырады. Кейін үлгі жауаппен салыстырып, тек дұрыс жауап санын емес, алғашқы айырманы белгілейді. Файлда жоқ тағы бір жағдай ойлап табуды сұраңыз: мысалы, мерзімі өткен, бірақ орындалған тапсырма. Жауапты келісімнен шығару мүмкін болмаса, 24-сабақтағы тексеру ретін толықтырыңыз. Табылған айырма мен түзетуді жоба журналына сақтаңыз.",
        "en": "Run a short defence without the author. A partner opens `cases.json`, hides the `expected` column, and fills it from your rules. They compare it with the oracle and mark the first mismatch, not only the number correct. Ask for one new case outside the file, such as a completed task with an overdue date. If the contract cannot determine the answer, return to lesson 24 and clarify the checking order. Record the mismatch and repair in the project log.",
    },
}

def render(number: int, lang: str) -> str:
    row = CONTENT[number][lang]
    title = ROWS[number][f"title_{lang}"]
    h = HEAD[lang]
    image = f"/static/course/informatics/map-{STEMS[number]}-{lang}.svg"
    intro = {"ru": "Это третий блок одного проекта. Мы пользуемся данными версии 0.2, но пока описываем действия на бумаге: так можно обнаружить ошибку до написания Python.", "kz": "Бұл бір жобаның үшінші бөлімі. 0.2 нұсқасының деректерін қолданамыз, бірақ әрекеттерді әзірге қағазда сипаттаймыз: Python жазбай тұрып қатені табуға болады.", "en": "This is the third block of one project. We use version 0.2 data but describe actions on paper first, where mistakes are easier to find before writing Python."}[lang]
    parts = [f"# {title}", f"_{h[0]}:_ **{row['lead']}**", f"## {h[1]}\n\n{intro}\n\n![{title}]({image})"]
    for heading, key in zip(h[2:12], ("scene", "terms", "signal", "worked", "predict", "error", "transfer", "project", "task", "review")):
        value = row[key]
        if key == "signal": value = f"`{value}`"
        parts.append(f"## {heading}\n\n{value}")
        if key == "worked":
            deep_heading = {"ru": "Проверка руками", "kz": "Қолмен тексеру", "en": "Check it by hand"}[lang]
            parts.append(f"## {deep_heading}\n\n{DEEP[number][lang]}")
    if number < 26:
        parts.append(f"[{h[12]}: {ROWS[number+1][f'title_{lang}']}](/read/informatics-{STEMS[number+1]}?lang={lang})")
    else:
        next_title = ROWS[27][f'title_{lang}']
        parts.append(f"[{h[12]}: {next_title}](/read/informatics-27-python-first-state?lang={lang})")
    return "\n\n".join(parts) + "\n"

def main() -> None:
    for number in range(19, 27):
        for lang in ("ru", "kz", "en"):
            suffix = "" if lang == "ru" else f"-{lang}"
            (OUT / f"{STEMS[number]}{suffix}.md").write_text(render(number, lang), encoding="utf-8")
    print("Generated 24 localized algorithm lessons")

if __name__ == "__main__":
    main()
