#!/usr/bin/env python3
"""Build reviewed KZ/EN SQL lessons while preserving canonical code verbatim."""
from pathlib import Path
import json, re

ROOT=Path(__file__).resolve().parents[2]; SRC=ROOT/"course/lessons/sql"
FENCE=re.compile(r"```(sql|python|text)\s*\n(.*?)```",re.S)

DATA={
"schema":{
"en":("CREATE TABLE: a schema that rejects impossible data","Create the family-budget tables and move essential validation into the database.","An interface checks only one input path. Imports and scripts can bypass it; database constraints protect every path.","A schema is an ice tray: water may arrive from any jug, but the mould will not produce an impossible cube.","NOT NULL requires a value; UNIQUE prevents duplicate account names; CHECK validates a row; REFERENCES rejects a missing account or category. SQLite foreign keys must be enabled for each connection with PRAGMA foreign_keys=ON. INTEGER PRIMARY KEY already generates a row identifier; AUTOINCREMENT is rarely needed. SQLite stores our ISO date as TEXT because it has no dedicated DATE type.","Why are NOT NULL and CHECK different?|What happens when account_id refers to no account?|Why does the date constraint make two checks?","Create goals with a key, unique non-empty name, positive target_tiyn, and an optional valid ISO due date.","The complete contract lives in course/sql-budget/schema.sql; later queries rely on it."),
"kz":("CREATE TABLE: мүмкін емес деректі қабылдамайтын сұлба","Отбасы бюджетінің кестелерін құрып, негізгі тексерулерді дерекқордың өзіне тапсырамыз.","Интерфейс тек бір енгізу жолын тексереді. Импорт пен басқа бағдарлама оны айналып өте алады; дерекқор шектеуі барлық жолды қорғайды.","Сұлба — мұзға арналған қалып: су кез келген ыдыстан құйылуы мүмкін, бірақ қалып мүмкін емес текше жасамайды.","NOT NULL мәнді міндеттейді; UNIQUE шот атауының қайталануын тоқтатады; CHECK бір жолдың шартын тексереді; REFERENCES жоқ шотқа не санатқа сілтеме жасатпайды. SQLite-та сыртқы кілттер әр қосылымда PRAGMA foreign_keys=ON арқылы қосылады. INTEGER PRIMARY KEY жол нөмірін өзі бере алады; AUTOINCREMENT көбіне қажет емес. SQLite-та жеке DATE типі болмағандықтан, күн ISO пішіміндегі TEXT ретінде сақталады.","NOT NULL мен CHECK қандай бөлек міндет атқарады?|Жоқ шоттың account_id мәнін берсеңіз не болады?|Күн шарты неліктен екі тексеруден тұрады?","Кілті, қайталанбайтын бос емес атауы, оң target_tiyn сомасы және міндетті емес дұрыс ISO мерзімі бар goals кестесін құрыңыз.","Толық сұлба course/sql-budget/schema.sql файлында; кейінгі сұраулар оның кепілдіктеріне сүйенеді.")},
"insert":{
"en":("INSERT and parameters: add spending safely","Insert one or several transactions and keep user values separate from SQL code.","A note such as O'Reilly contains a quote. String concatenation can break a query or let hostile input change its meaning; parameters carry values separately.","The query is a printed form and parameters fill its boxes; a value cannot draw another command on the form.","Always name inserted columns, so table order cannot change the meaning. A parameter replaces a value, not a table name, column, or sort direction. Choose identifiers from an application allow-list. INSERT OR REPLACE deletes the conflicting row before inserting; use UPDATE or an explicit ON CONFLICT clause when that is what you mean.","Why list columns explicitly?|What can a parameter replace?|Why is SQL string concatenation dangerous?","Add a 3,200.50 tenge Transport expense on 16 September from Card; convert it to tiyn before the query.","seed.sql creates a repeatable fictional history; an application uses parameters and transactions."),
"kz":("INSERT және параметрлер: шығынды қауіпсіз қосу","Операцияларды бір-бірден және топпен қосып, пайдаланушы мәнін SQL кодынан бөлеміз.","O'Reilly кітабы сияқты ескертпеде апостроф бар. Жолдарды қосу сұрауды бұзады, ал зиянды енгізу оның мағынасын өзгертуі мүмкін; параметр мәнді бөлек жеткізеді.","Сұрау — дайын бланк, параметрлер — оның ұяшықтарындағы мәндер; мән бланкіге жаңа команда қоса алмайды.","INSERT бағандарын әрқашан атаңыз: кестедегі орын тәртібі мағынаны өзгертпейді. Параметр мәнді ғана алмастырады, кесте мен баған атауын алмастырмайды. Идентификаторларды қолданба рұқсат еткен тізімнен таңдаңыз. INSERT OR REPLACE алдымен қайшы жолды өшіреді; саналы жаңарту үшін UPDATE немесе нақты ON CONFLICT қолданыңыз.","Бағандарды неге ашық жазамыз?|Параметр нені алмастыра алады?|SQL жолдарын біріктіру неліктен қауіпті?","16 қыркүйекте Card шотынан Transport санатына 3 200,50 теңге шығын қосыңыз; соманы алдын ала тиынға айналдырыңыз.","seed.sql қайталанатын ойдан алынған тарих жасайды; қолданба параметрлер мен транзакцияны пайдаланады.")},
"select":{
"en":("SELECT: find the needed rows without changing them","Learn projection, filtering, stable sorting, and limiting a result.","A database is useful because it returns exactly what is needed: recent spending, purchases above a threshold, or one month's events.","FROM puts the receipt box on the table; WHERE keeps matching receipts; SELECT covers unused fields; ORDER BY arranges them; LIMIT takes the first few.","The logical order begins with FROM and WHERE even though SELECT is written first. SELECT * is fine for exploration, but application contracts should name columns. Without ORDER BY row order is undefined; add id as a tie-breaker. LIKE rules, especially case handling, differ across systems.","Why is SELECT written first but not evaluated first?|What resolves equal dates?|When is SELECT * risky?","Return September's three largest transactions with date, tenge amount, and note; break ties by newest row.","This query pattern powers transaction history and previews rows before a bulk change."),
"kz":("SELECT: керекті операцияны тауып, ештеңені өзгертпеу","Нәтиже бағандарын таңдау, сүзу, тұрақты сұрыптау және жол санын шектеуді үйренеміз.","Дерекқор бәрін сақтағаны үшін емес, керегін дәл бергені үшін пайдалы: соңғы шығын, шектен үлкен сатып алу немесе бір айдың операциялары.","FROM түбіртек жәшігін үстелге қояды; WHERE керегін қалдырады; SELECT артық өрісті жабады; ORDER BY реттейді; LIMIT алғашқы бірнешеуін алады.","Логикалық орындау FROM және WHERE бөліктерінен басталады, бірақ SELECT бірінші жазылады. SELECT * зерттеуге ыңғайлы, ал қолданба нақты бағандарды атауы керек. ORDER BY болмаса, жол ретіне кепіл жоқ; тең күнге id қосыңыз. LIKE регистрінің тәртібі әр жүйеде өзгеше.","SELECT неге бірінші жазылып, кейін орындалады?|Күндер тең болса, ретті не анықтайды?|SELECT * қашан тәуекел тудырады?","Қыркүйектегі ең ірі үш операцияның күнін, теңгедегі сомасын және ескертпесін шығарыңыз; тең сомада жаңасын бірінші қойыңыз.","Бұл үлгі операция тарихын және жаппай өзгеріс алдындағы тексеруді құрайды.")},
"expressions":{
"en":("CASE, COALESCE, and dates: turn stored facts into a useful view","Compute display columns, handle NULL honestly, and define month boundaries.","The database stores stable facts—tiyn, ISO dates, and keys—while a reader needs tenge, labels, and a limit status.","A stored fact is an ingredient; a SELECT expression plates it. Do not store an ingredient pre-cut for every possible dish.","AS names a result. Dividing by 100.0 produces a display value while the stored money stays integral. COALESCE returns the first non-NULL value without rewriting the fact. CASE checks conditions top-down. Pass period boundaries as parameters; SQLite date modifiers are useful but not portable syntax.","Why keep tiyn after displaying tenge?|What does COALESCE preserve?|Why does CASE order matter?","Add a label showing whether each expense is within its category limit.","These expressions make the report readable without duplicating source facts."),
"kz":("CASE, COALESCE және күн: сақталған фактіні түсінікті көрсету","Есептелетін бағандар құрып, NULL мәнін дұрыс өңдеп, ай шекарасын белгілейміз.","База тиын, ISO күн және кілт сияқты тұрақты фактіні сақтайды; оқырманға теңге, түсінікті атау мен лимит күйі керек.","Сақталған факт — азық, SELECT өрнегі — оны ұсыну тәсілі. Азықты әр тағамға алдын ала бөліп сақтамаңыз.","AS нәтижені атайды. 100.0-ге бөлу тек көрсетуге арналған, бастапқы ақша бүтін болып қалады. COALESCE фактіні өзгертпей, алғашқы NULL емес мәнді қайтарады. CASE шарттарды жоғарыдан төмен тексереді. Кезең шекарасын параметрмен беріңіз; SQLite күн модификаторлары пайдалы, бірақ басқа жүйеге дәл көшпейді.","Теңгені көрсетсек те, тиынды неге сақтаймыз?|COALESCE қандай мағынаны сақтайды?|CASE шарттарының реті неге маңызды?","Әр шығынның санат лимитіне сыйғанын не асқанын көрсететін белгі қосыңыз.","Бұл өрнектер бастапқы фактіні қайталамай, есепті түсінікті етеді.")},
"aggregate":{
"en":("SUM, COUNT, GROUP BY, and HAVING: totals by category","Compress transactions into auditable totals and detect limits that were exceeded.","A list of receipts does not answer how much each category consumed. Aggregates calculate the answer while retaining a visible rule.","GROUP BY puts receipts into envelopes; an aggregate counts each envelope; HAVING keeps envelopes based on their total.","WHERE filters source rows before grouping; HAVING filters groups afterwards. COUNT(*) counts rows, COUNT(column) counts non-NULL values, and SUM totals values. Every selected non-aggregate expression should identify the group. Group by stable category id as well as its readable name.","When do WHERE and HAVING act?|How do COUNT(*) and COUNT(note) differ?|Why group by category id?","Show expense categories whose September total exceeds monthly_limit_tiyn.","These totals form the main budget dashboard and its limit warnings."),
"kz":("SUM, COUNT, GROUP BY және HAVING: санат қорытындысы","Операцияларды тексерілетін қорытындыға жинап, лимиттен асқан санаттарды табамыз.","Түбіртек тізімі әр санатқа қанша кеткенін айтпайды. Агрегат жауапты есептейді және есептеу ережесін ашық қалдырады.","GROUP BY түбіртектерді конверттерге бөледі; агрегат әр конвертті есептейді; HAVING қорытындысына қарай конвертті қалдырады.","WHERE топтауға дейін бастапқы жолдарды, HAVING топталған нәтижені сүзеді. COUNT(*) жолдарды, COUNT(column) NULL емес мәндерді санайды, SUM қосады. Агрегат емес таңдалған өрнек топты анықтауы керек. Оқылатын атаумен бірге тұрақты санат id бойынша топтаңыз.","WHERE мен HAVING қашан іске қосылады?|COUNT(*) пен COUNT(note) қалай ерекшеленеді?|Неліктен санат id бойынша топтаймыз?","Қыркүйек шығыны monthly_limit_tiyn мәнінен асқан санаттарды көрсетіңіз.","Бұл қорытындылар бюджет панелі мен лимит ескертуінің негізі болады.")},
"join":{
"en":("Keys and JOIN: connect transactions, accounts, and categories","Normalise the budget model and join tables by stable keys without multiplying rows.","Repeating a category name in every receipt creates spelling variants and conflicting rules. Store the meaning once and reference its key.","A transaction holds a cloakroom token; JOIN retrieves the exact coat by token number, not by a similar colour.","INNER JOIN keeps matches; LEFT JOIN preserves every left row and uses NULL for missing right data. Join on keys, not similar text. Before trusting totals, verify key uniqueness and compare row counts: duplicate lookup keys can multiply facts.","How do INNER and LEFT JOIN differ?|Why not join names?|How can a join multiply money?","List every account and its transaction count, including accounts with none.","Joins add readable names to compact facts while foreign keys protect relationships."),
"kz":("Кілттер және JOIN: операцияны шот пен санатқа байланыстыру","Бюджет моделін қалыпқа келтіріп, кестелерді тұрақты кілтпен, жолдарды көбейтпей байланыстырамыз.","Әр түбіртекте санат атауын қайталау емле нұсқаларын және қайшы ережелерді туғызады. Мағынаны бір жерде сақтап, кілтіне сілтеңіз.","Операцияда киім ілгіштің жетоны бар; JOIN ұқсас түске емес, жетонның дәл нөміріне қарай киімді қайтарады.","INNER JOIN сәйкестікті ғана қалдырады; LEFT JOIN сол жақтағы барлық жолды сақтап, жоқ оң мәнге NULL береді. Ұқсас мәтінмен емес, кілтпен байланыстырыңыз. Қорытындыға дейін кілт бірегейлігін және жол санын тексеріңіз: қайталанған анықтамалық кілті ақшаны көбейте алады.","INNER JOIN мен LEFT JOIN қалай ерекшеленеді?|Атаумен байланыстыру неге дұрыс емес?|JOIN ақшаны қалай көбейтіп жібереді?","Операциясы жоқтарын да қамтып, әр шот пен оның операция санын көрсетіңіз.","JOIN ықшам фактіге түсінікті атау қосады, ал сыртқы кілт байланысты қорғайды.")},
"cte":{
"en":("Subqueries and WITH: answer a complex question in steps","Break the savings-rate calculation into named, testable CTE stages.","Copying one long formula makes review difficult. Named intermediate steps reveal where a wrong total entered the calculation.","CTEs are clear mixing bowls: prepare income and spending separately, inspect them, then combine them.","A CTE exists for one statement; it is not a stored table. Read several CTEs top-down as calculation stages. NULLIF(income,0) prevents a false percentage when income is zero. Correlated subqueries are not automatically slow; choose between them, joins, and pre-aggregation using clarity and the query plan.","How does a CTE differ from a table?|Why use NULLIF here?|Why not declare every subquery slow?","Add a CTE that returns spending as a percentage of income and NULL when income is absent.","Named stages become the final report and let us test each calculation separately."),
"kz":("Ішкі сұрау және WITH: күрделі сұрақты қадамға бөлу","Жинақ үлесін есептеуді атауы бар, тексерілетін CTE кезеңдеріне бөлеміз.","Бір ұзын формуланы қайталау тексеруді қиындатады. Аралық қадамның атауы қате қорытындының қайда кіргенін көрсетеді.","CTE — мөлдір ыдыстар: кіріс пен шығысты бөлек дайындап, тексеріп, содан кейін біріктіреміз.","CTE бір команда уақытында ғана бар; ол сақталған кесте емес. Бірнеше CTE есеп кезеңдері ретінде жоғарыдан төмен оқылады. NULLIF(income,0) кіріс нөл болғанда жалған пайыз шығармайды. Корреляцияланған ішкі сұрау әрдайым баяу емес; ішкі сұрау, JOIN және алдын ала топтауды түсініктілік пен жоспарға қарап таңдаңыз.","CTE кестеден несімен ерекшеленеді?|Мұнда NULLIF не үшін керек?|Барлық ішкі сұрауды неге алдын ала баяу дей алмаймыз?","Шығынның кіріске пайызын, ал кіріс жоқта NULL қайтаратын CTE қосыңыз.","Атауы бар кезеңдер қорытынды есепке кіріп, әр есепті жеке тексеруге мүмкіндік береді.")},
"windows":{
"en":("Window functions: a running balance without losing rows","Calculate the balance after every event and rank spending while keeping each source row.","GROUP BY collapses a month into totals. To find when cash was lowest, we need each transaction and its running context.","GROUP BY folds a deck into one total; a window writes a running total on every card without discarding it.","OVER turns an aggregate into a window function. Window ORDER BY defines calculation order; outer ORDER BY defines display order. State the ROWS frame explicitly and add id to break date ties. PARTITION BY starts an independent window per category; ROW_NUMBER, RANK, and DENSE_RANK treat ties differently.","How does a window differ from GROUP BY?|Why sort twice?|What does PARTITION BY do?","Number expenses within each category from largest to smallest with ROW_NUMBER().","The running balance reveals the moment of a cash shortfall, not only the month-end total."),
"kz":("Терезелік функциялар: жолдарды жоғалтпайтын жинақталған қалдық","Әр операциядан кейінгі қалдық пен шығын рейтингін бастапқы жолдарды сақтай отырып есептейміз.","GROUP BY айды бірнеше қорытындыға жинайды. Ақша қай сатып алудан кейін азайғанын табу үшін әр операция және оның жанындағы жинақталған нәтиже керек.","GROUP BY карталар бумасын бір сомаға жинайды; терезе ешбір картаны тастамай, әрқайсына ағымдағы қорытынды жазады.","OVER агрегатты терезелік функцияға айналдырады. Терезедегі ORDER BY есеп ретін, сыртқы ORDER BY көрсету ретін береді. ROWS шеңберін анық жазып, тең күнді id арқылы ажыратыңыз. PARTITION BY әр санатқа жеке терезе ашады; ROW_NUMBER, RANK және DENSE_RANK тең мәндерді әртүрлі өңдейді.","Терезе GROUP BY-дан қалай ерекшеленеді?|Сұрыптау неге екі рет жазылған?|PARTITION BY не істейді?","ROW_NUMBER() арқылы әр санаттағы шығындарды үлкенінен кішісіне нөмірлеңіз.","Жинақталған қалдық ай соңын ғана емес, ақша жетіспеген сәтті де көрсетеді.")},
"transactions":{
"en":("Transactions and UPDATE: change everything or nothing","Make safe corrections and treat a transfer as one atomic database operation.","A transfer needs at least two related records. If debit succeeds and credit fails, the database invents or loses money.","A transaction is a lock with two gates: either the boat passes completely or boat and water return to their initial state.","ACID summarises atomicity, consistency, isolation, and durability; exact guarantees vary by DBMS. Before UPDATE or DELETE, run SELECT with the same WHERE and then check the affected-row count. COMMIT makes changes durable; ROLLBACK cancels unfinished work; SAVEPOINT rolls back part. A transfer between your accounts is not household spending.","What is atomicity?|How do you test WHERE before changing data?|Why is an internal transfer not spending?","Inside a transaction set Transport's limit to 40,000 tenge, read it, ROLLBACK, and confirm the old value returned.","Every related budget change is atomic and can be cancelled before commit."),
"kz":("Транзакциялар және UPDATE: бәрін өзгерту немесе ештеңені өзгертпеу","Деректі қауіпсіз түзетіп, шоттар арасындағы аударымды бір атомдық әрекет ретінде орындаймыз.","Шоттар арасындағы аударым кемінде екі байланысты жазбадан тұрады. Ақша алу сақталып, қосу сақталмаса, база жоқ ақшаны көрсетеді.","Транзакция — екі қақпалы шлюз: қайық не толық өтеді, не су мен қайық бастапқы орнына қайтады.","ACID атомдық, келісімділік, оқшаулану және тұрақтылықты білдіреді; нақты кепілдік ДҚБЖ-ға байланысты. UPDATE не DELETE алдында дәл сол WHERE бар SELECT орындап, кейін өзгерген жол санын тексеріңіз. COMMIT бекітеді, ROLLBACK аяқталмаған жұмысты қайтарады, SAVEPOINT бір бөлігін қайтарады. Өз шоттарыңыз арасындағы аударым отбасы шығыны емес.","Атомдық деген не?|WHERE шартын өзгеріске дейін қалай тексереміз?|Ішкі аударым неге шығын емес?","Транзакция ішінде Transport лимитін 40 000 теңгеге өзгертіп, оқыңыз; ROLLBACK жасап, ескі мәннің қайтқанын тексеріңіз.","Байланысты бюджет өзгерістері бірге орындалып, бекітуге дейін қайтарыла алады.")},
"audit":{
"en":("Data reconciliation: find a gap before making a decision","Use control totals, duplicate candidates, and relationship checks to test completeness.","A query without an error does not prove complete data. One receipt imported twice creates a plausible but wrong total.","Reconciliation is a scale at the warehouse exit: individual records look valid, but their total weight must agree.","Duplicate identity is a business rule, not simply equal ids; equal dates and amounts may still be two purchases. foreign_key_check finds broken links and integrity_check checks file structure, but neither knows whether spending is sensible. A row CHECK cannot enforce a rule across a whole month. Opening balances plus income minus spending must reconcile with calculated balances.","Why does a match only identify a duplicate candidate?|How does integrity_check differ from a business check?|What equation reconciles the budget?","Record transaction count and expense total, insert a copied transaction with a new id, and show which checks detect it.","Run reconciliation after imports and before publishing a report."),
"kz":("Деректерді салыстырып тексеру: шешімге дейін сәйкессіздікті табу","Бақылау теңдігі, ықтимал қайталау және байланыс тексеруі арқылы толықтықты анықтаймыз.","Қатесіз орындалған сұрау деректің толық екенін дәлелдемейді. Бір түбіртекті екі рет импорттау сенімді көрінетін, бірақ қате қорытынды береді.","Салыстырып тексеру — қойма шығысындағы таразы: жеке жазбалар дұрыс көрінсе де, жалпы салмақ сәйкес келуі керек.","Қайталауды id теңдігі емес, пәндік ереже анықтайды; күні мен сомасы тең екі бөлек сатып алу болуы мүмкін. foreign_key_check бұзылған байланысты, integrity_check файл құрылымын табады, бірақ шығынның орынды екенін білмейді. Бір жолдың CHECK шарты тұтас ай ережесін тексермейді. Бастапқы қалдыққа кірісті қосып, шығынды алғанда есептелген қалдық шығуы тиіс.","Сәйкестік неге тек ықтимал қайталауды көрсетеді?|integrity_check пәндік тексеруден қалай ерекшеленеді?|Бюджетті қандай теңдікпен салыстырамыз?","Операция саны мен шығын сомасын жазып алыңыз, бір операцияны жаңа id-мен көшіріп қосып, оны қай тексерулер тапқанын көрсетіңіз.","Салыстырып тексеру импорттан кейін және есепті жариялау алдында орындалады.")},
"final":{
"en":("Indexes, EXPLAIN, and the final report","Assemble the report, inspect its plan, add a justified index, and prove a backup by restoring it.","A correct query may become slow; a fast query may be wrong; an untested backup may be unusable.","An index is a book index: faster lookup costs space and update work. A backup is a spare key tested in the real door.","Match an index to a measured query path; do not index every column or judge using eight rows. EXPLAIN QUERY PLAN output is diagnostic and version-dependent. SCAN is not always bad for a small table. A VIEW stores a query, not its result. Back up an open SQLite database with .backup or the backup API, then open the copy, run integrity_check, and compare control totals. Never commit real financial data.","What does an index cost?|Why is SCAN not always bad?|When is a backup verified?","Create a backup, open it separately, run integrity_check and the monthly report, and compare all three totals.","The finished project has protected facts, explainable calculations, a measured index, and a recoverable copy."),
"kz":("Индекс, EXPLAIN және қорытынды есеп","Отбасы есебін жинап, сұрау жоспарын өлшеп, негізделген индекс құрып, сақтық көшірмені қалпына келтіру арқылы тексереміз.","Дұрыс сұрау көп жолда баяулауы, жылдам сұрау қате нәтиже беруі мүмкін. Тексерілмеген көшірме қажет сәтте ашылмауы ықтимал.","Индекс — кітаптың әліпбилік көрсеткіші: іздеуді жеделдету үшін орын және жаңарту жұмысы жұмсалады. Сақтық көшірме — шынайы есікте сыналған қосалқы кілт.","Индексті өлшенген сұрау жолына сәйкестендіріңіз; әр бағанға индекс жасамаңыз және сегіз жолмен жылдамдық бағаламаңыз. EXPLAIN QUERY PLAN — нұсқаға тәуелді диагностика. Шағын кестеде SCAN дұрыс жоспар болуы мүмкін. VIEW нәтиже көшірмесін емес, сұрауды сақтайды. Ашық SQLite базасын .backup не backup API арқылы көшіріп, көшірмені бөлек ашыңыз, integrity_check орындап, бақылау сомаларын салыстырыңыз. Нақты қаржы дерегін Git-ке қоспаңыз.","Индекстің құны қандай?|SCAN неліктен әрдайым жаман емес?|Сақтық көшірме қашан тексерілген саналады?","Көшірме жасап, оны бөлек ашыңыз; integrity_check пен айлық есепті орындап, үш қорытындыны салыстырыңыз.","Дайын жобада фактілер қорғалған, есеп түсіндіріледі, индекс өлшенген, көшірме қалпына келеді.")}}

HEAD={"en":("Why this matters","Image","See the whole thing first","Explanation","Lesson map","Say it in your own words","Exercise","Where this fits in the project","Answers","Sources"),"kz":("Бұл не үшін қажет","Бейне","Алдымен тұтас көрініс","Талдау","Сабақ картасы","Өз сөзіңізбен айтыңыз","Тапсырма","Жобадағы орны","Жауаптар","Дереккөздер")}
for stem,langs in DATA.items():
    source=(SRC/f"{stem}.md").read_text(); blocks=FENCE.findall(source); links=re.findall(r"^- \[(.*?)\]\((https?://.*?)\)$",source,re.M)
    for lang,v in langs.items():
        title,lead,why,image,explain,questions,task,place=v; h=HEAD[lang]; label="_Lead (summary):_" if lang=="en" else "_Лид (summary):_"
        replacements={
         "en":{"Без заметки":"No note","крупная":"large","средняя":"medium","небольшая":"small","Книга О'Райли":"O'Reilly book"},
         "kz":{"Без заметки":"Ескертпесіз","крупная":"ірі","средняя":"орташа","небольшая":"шағын","Книга О'Райли":"O'Reilly кітабы"}}
        def code(b):
         content=b[1].strip()
         for old,new in replacements[lang].items(): content=content.replace(old,new)
         return f"```{b[0]}\n{content}\n```"
        first=code(blocks[0]); rest="\n\n".join(code(b) for b in blocks[1:]) or ("The answer follows from the complete query above." if lang=="en" else "Жауап жоғарыдағы толық сұраудан шығады.")
        q="\n".join(f"{i}. {x}" for i,x in enumerate(questions.split("|"),1)); sources="\n".join(f"- [{a}]({u})" for a,u in links)
        alt=title.split(":")[0]; body=f"# {title}\n\n{label} **{lead}**\n\n## {h[0]}\n\n{why}\n\n> **{h[1]}.** {image}\n\n## {h[2]}\n\n{first}\n\n## {h[3]}\n\n{explain}\n\n## {h[4]}\n\n![{alt}](/static/course/sql/map-{stem}-{lang}.svg)\n\n## {h[5]}\n\n{q}\n\n## {h[6]}\n\n{task}\n\n## {h[7]}\n\n{place}\n\n## {h[8]}\n\n{rest}\n\n## {h[9]}\n\n{sources}\n"
        (SRC/f"{stem}-{lang}.md").write_text(body,encoding="utf-8")

# The publication map is generated from the same lesson list, so adding a
# translation without making it publishable is impossible.
slugs={
 "why":"sql-zachem-nuzhen-semeinyi-byudzhet", "model":"sql-tablica-stroka-stolbec-null",
 "schema":"sql-create-table-ogranicheniya", "insert":"sql-insert-i-parametry",
 "select":"sql-select-where-order-limit", "expressions":"sql-case-coalesce-daty",
 "aggregate":"sql-sum-count-group-by-having", "join":"sql-klyuchi-i-join",
 "cte":"sql-podzaprosy-i-cte", "windows":"sql-okonnye-funkcii",
 "transactions":"sql-tranzakcii-i-update", "audit":"sql-sverka-dannyh",
 "final":"sql-indeks-explain-backup"}
mapping_path=ROOT/"tools/course/lesson-slugs.json"
mapping=json.loads(mapping_path.read_text(encoding="utf-8"))
for stem,slug in slugs.items():
 for suffix,lang in (("","ru"),("-kz","kz"),("-en","en")):
  mapping[f"sql/{stem}{suffix}"]=[slug,lang]
mapping_path.write_text(json.dumps(mapping,ensure_ascii=False,indent=2,sort_keys=True)+"\n",encoding="utf-8")
