"""Human-authored Kazakh and English lesson content for the mathematics course.

The data is deliberately kept in the repository: every mathematical term,
example, and progression can be reviewed without calling a translation service.
"""


def E(title, summary, where, alt, image, meaning, signal, worked, mistake, task, next_):
    return {
        "title": title, "summary": summary, "where": where, "alt": alt,
        "image": image, "meaning": meaning, "signal": signal,
        "worked": worked, "mistake": mistake, "task": task, "next": next_,
    }


DATA = {
    "preface": {
        "kz": E(
            "Математиканы қалай оқимыз: жаттаудан түсінуге дейін",
            "Курс ұғымдардың тәуелділік картасымен жүреді: әр жаңа қадам бұрынғы тірекке сүйенеді, ал білім түсіндіру және жаңа жағдайға көшіру арқылы тексеріледі.",
            "Бұл — бүкіл бағыттың картасы. Диагностикадан кейін сандар, бөлшектер, алгебра алдындағы ұғымдар мен функцияларға бірізді өтеміз.",
            "Сандардан алгебра мен модельдеуге апаратын математика курсының картасы",
            "Үй салғанда шатырдан бастамайды: алдымен іргетас, кейін қабырға, содан соң жоғарғы қабаттар салынады. Математикада да бөлшек сан ұғымына, ал теңдеу амалдардың мағынасына сүйенеді.",
            "Біз тақырыптарды сынып нөмірімен емес, олардың бір-біріне тәуелділігімен орналастырамыз. Қателесу қабілетсіздік белгісі емес; ол қай тіректі қалпына келтіру керегін көрсетеді.",
            "бейне → қысқа белгі → өз сөзіңмен түсіндіру → қолдану → аралықтан кейін қайталау",
            "Егер оқушы пайызды есептей алмаса, бірден формуланы жаттатпаймыз. Алдымен жүзден бір үлес, бөлшек және ондық жазу түсінікті ме, соны тексереміз.",
            "«Тақырыпты оқыдым, демек білемін» деу қате. Білімнің дәлелі — тірексіз түсіндіру, жаңа сандармен шығару және қатені табу.",
            "Картаны қарап, өзіңіз сенімді және сенімсіз сезінетін үш түйінді атаңыз. Диагностиканы адал орындап, алғашқы әлсіз тіректі белгілеңіз.",
            "Келесі бет баға қоймайды: ол сізге дұрыс бастау нүктесін табуға көмектеседі."
        ),
        "en": E(
            "How we will learn mathematics: from memorizing to understanding",
            "The course follows a dependency map: every new step rests on an earlier idea, and understanding is checked through explanation and transfer to a new situation.",
            "This is the map of the whole route. After diagnosis, we move through numbers, fractions, prealgebra, and functions in a deliberate order.",
            "Map of the mathematics course from numbers to algebra and modeling",
            "A house is built from its foundation, then its walls, and only then its upper floors. Mathematics works the same way: fractions depend on the idea of number, while equations depend on the meaning of operations.",
            "Topics are ordered by what they require, rather than by a school grade label. A mistake is useful evidence: it points to the support idea that needs to be rebuilt.",
            "image → compact support → explain in your own words → apply → recall later",
            "If a learner cannot solve a percentage problem, we do not begin with another formula. We first check whether one hundredth, fractions, and decimal notation are understood.",
            "The claim “I read the topic, so I know it” is unreliable. Evidence of learning is explaining without the page, solving with new numbers, and correcting an error.",
            "Study the map and name three ideas that feel secure and three that feel uncertain. Complete the diagnosis honestly and mark the first missing support.",
            "The next page does not grade you. It helps you choose the right starting point."
        ),
    },
    "01-diagnostic": {
        "kz": E(
            "Кіріс диагностикасы: алғашқы жоғалған тіректі табу",
            "Он қысқа тапсырма мектеп ережелерін түгел есте сақтауды талап етпей, оқуды қай жерден бастау керегін көрсетеді.",
            "Диагностика курстың қақпасы. Ол адамды бағаламайды, тек білім тізбегіндегі бірінші әлсіз буынды табады.",
            "Диагностикадан кейін сандар, бөлшектер, қатынас, пайыз және теңдеуге апаратын бағыт",
            "Дәрігер ем тағайындамас бұрын белгілерді тексереді. Мұнда да әр жауаптың қасына «+», «?» немесе «−» қойып, жауапқа ғана емес, өз сеніміңізге де қараймыз.",
            "«+» — тәсілді түсіндіре аласыз; «?» — жауап бар, бірақ себепке күмәнданасыз; «−» — неден бастарыңызды білмейсіз. Бірінші «?» немесе «−» оқу нүктесін көрсетеді.",
            "тапсырма → менің тәсілім → жауап → түсіндіру → сенімділік белгісі",
            "12 затты төрт тең топқа бөлсек, әр топта 3 зат болады. `12 ÷ 4 = 3`; тек жауап емес, топтау мағынасы да айтылды.",
            "`3/8` суретіндегі сегізді «сегіз боялған бөлік» деу қате. Сегіз — бүтін неше тең бөлікке бөлінгенін, үш — соның нешеуі алынғанын көрсетеді.",
            "Он тапсырманың бәріне жауап беріп, әрқайсысына `+`, `?` немесе `−` қойыңыз. Бірінші күмәнді жауапты екі сөйлеммен түсіндіріңіз.",
            "Нәтиже сізді ең ерте қажет тірекке: сан мағынасына, бөлшекке, қатынасқа, пайызға немесе теңдеуге бағыттайды."
        ),
        "en": E(
            "Entry diagnosis: find the first missing support",
            "Ten short problems locate the right starting point without judging the learner or demanding perfect recall of school rules.",
            "Diagnosis is the gateway to the course. It evaluates the learning chain, rather than the person, and finds its first weak link.",
            "Diagnostic route leading to numbers, fractions, ratios, percentages, and equations",
            "A doctor checks symptoms before choosing a treatment. Here you mark every answer with `+`, `?`, or `−`, so we observe confidence and reasoning as well as the final number.",
            "A `+` means you can explain the method; `?` means you have an answer but doubt the reason; `−` means you do not know how to begin. The first `?` or `−` identifies the starting point.",
            "problem → my method → answer → explanation → confidence mark",
            "Dividing 12 objects into four equal groups gives 3 in each group. `12 ÷ 4 = 3`; the explanation names what the division means.",
            "Calling the 8 in `3/8` “eight shaded pieces” is wrong. Eight says how many equal parts make the whole; three says how many of them are selected.",
            "Answer all ten problems and mark each one with `+`, `?`, or `−`. Explain your first uncertain answer in two sentences.",
            "Your result sends you to the earliest support you need: number meaning, fractions, ratio, percent, or equations."
        ),
    },
    "10-quantity-counting": {
        "kz": E("Сан және санау: сан «нешеу?» деген сұраққа жауап береді", "Натурал санның мағынасын «бір зат — бір сан» сәйкестігі арқылы құрамыз, заттарды топпен көріп, санды оның жазылуынан ажыратамыз.", "Сандық іргетастың алғашқы сабағы: амалдан бұрын мөлшердің өзін түсінеміз.", "Төрт алтыдан топ және тағы үш зат арқылы 27 санын көрсету", "Бытыраған 27 нүктені бір-бірлеп санау баяу. Оларды алтыдан төрт топқа жинасақ, тағы үш нүкте қалады.", "Натурал сан жеке заттардың мөлшерін немесе реттегі орнын білдіреді. Цифр — санды жазуға арналған таңба; бір сан әртүрлі түрде көрсетілуі мүмкін.", "бір зат ↔ бір сан; тең топтар × топтағы саны + қалдық", "Төрт топтың әрқайсысында 6 зат және тағы 3 зат бар: `4 × 6 + 3 = 27`.", "Санағанда бір затты екі рет көрсету 27 орнына 28 береді. Әр затқа санау қатарынан дәл бір сан сәйкес келуі керек.", "25–40 ұсақ зат алып, алдымен мөлшерін шамалаңыз, кейін тең топтармен санап, өрнекпен жазыңыз.", "Келесі сабақ бірліктердің ондықтарға, жүздіктерге және мыңдықтарға қалай жиналатынын көрсетеді."),
        "en": E("Quantity and counting: a number answers “how many?”", "We build the meaning of a natural number through one object to one count, see quantities in groups, and separate a number from its written notation.", "This is the first numerical foundation: we understand quantity itself before operating on it.", "Twenty-seven objects shown as four groups of six and three more", "Counting 27 scattered dots one by one is slow. Arrange them in four groups of six and three dots remain.", "A natural number describes a quantity of separate objects or a position in an order. A digit is a symbol used to write a number; the same number can have several representations.", "one object ↔ one count; equal groups × group size + remainder", "Four groups contain 6 objects each, with 3 more: `4 × 6 + 3 = 27`.", "Pointing to one object twice produces 28 instead of 27. Exactly one counting word must correspond to each object.", "Take 25–40 small objects, estimate first, then count in equal groups and record the structure as an expression.", "The next lesson shows how units are bundled into tens, hundreds, and thousands."),
    },
    "11-place-value": {
        "kz": E("Разрядтар: цифрдың орны бірліктің көлемін көрсетеді", "Бірліктерді ондық, жүздік және мыңдыққа жинаймыз, нөлді бос разряд деп оқимыз және санды разрядтық қосылғыштарға жіктейміз.", "Санаудан көптаңбалы санның құрылымына өтеміз.", "4 072 санының мыңдық, жүздік, ондық және бірлік разрядтары", "Ақшадағы он бірлік бір ондыққа ауысатыны сияқты, он бірлік келесі разрядтың бір бірлігіне бірігеді.", "Разряд — цифрдың сан жазуындағы орны. Оңнан солға қарай бірлік, ондық, жүздік, мыңдық орналасады; нөл сол орындағы бірліктің жоқ екенін сақтайды.", "10 бірлік = 1 ондық → 10 ондық = 1 жүздік → 10 жүздік = 1 мыңдық", "`4 072 = 4 × 1000 + 0 × 100 + 7 × 10 + 2`. Сондықтан бұл төрт мың жетпіс екі.", "`3 040 = 3 × 1000 + 4 × 100` деу қате: 4 ондық разрядында тұр, сондықтан қосылғыш `4 × 10`.", "`6 205`, `980`, `10 040` сандарын разрядтық қосындыға жіктеп, әр цифрдың мәнін атаңыз және жүздікке дейін дөңгелектеңіз.", "Разрядтық түсінік қосу мен азайтудағы алмастыруды мағыналы етеді."),
        "en": E("Place value: a digit’s position shows the size of its unit", "We bundle units into tens, hundreds, and thousands, read zero as an empty place, and expand numbers so written operations make sense.", "We move from counting objects to the structure of multidigit numbers.", "Thousands, hundreds, tens, and ones in the number 4,072", "Just as ten small currency units can be exchanged for one larger unit, ten units in one place are bundled into one unit of the next place.", "Place value is a digit’s position in a numeral. From right to left we have ones, tens, hundreds, and thousands; zero preserves a place that contains no units.", "10 ones = 1 ten → 10 tens = 1 hundred → 10 hundreds = 1 thousand", "`4,072 = 4 × 1000 + 0 × 100 + 7 × 10 + 2`. We read it as four thousand seventy-two.", "Writing `3,040 = 3 × 1000 + 4 × 100` is wrong: 4 occupies the tens place, so its contribution is `4 × 10`.", "Expand `6,205`, `980`, and `10,040`, name the value of every digit, and round each number to the nearest hundred.", "Place value makes regrouping in addition and subtraction understandable."),
    },
    "12-addition-subtraction": {
        "kz": E("Қосу мен азайту: өзгеріс, салыстыру және кері жол", "Бөліктерді біріктіруді, артуды, қалдықты және айырманы ажыратып, разрядтық алмастыруды орындаймыз және әр амалды кері амалмен тексереміз.", "Разрядтар дайын болған соң мөлшердің қалай өзгеретінін зерттейміз.", "268-ге 157 қосып 425 алу және азайтумен кері қайту", "Екі қораптағы заттарды біріктіру — қосу; бүтіннен бір бөлігін алу — азайту. Сол үш сан бір амалдар отбасын құрайды.", "Қосу бөліктерден бүтінді немесе артқаннан кейінгі мәнді табады. Азайту қалдықты, айырманы немесе бастапқы мәнді қайтарады.", "бөлік + бөлік = бүтін; бүтін − бөлік = басқа бөлік; қосу ↔ азайту", "`268 + 157 = 425`. Тексеру: `425 − 157 = 268`; кері амал бастапқы санды қайтарды.", "`217 + 185 = 392` дегенде бірліктер дұрыс, бірақ ондық алмастыру жоғалған. Разрядпен қайта есептеу `402` береді.", "`487 + 368`, `700 − 456` есептерін шығарып, әрқайсын кері амалмен тексеріңіз; біріктіру мен салыстыруға бір-бір есеп құрыңыз.", "Келесі сабақ бірдей қосылғыштарды көбейтуге, ал тең бөлуді бөлуге айналдырады."),
        "en": E("Addition and subtraction: change, comparison, and the way back", "We distinguish joining, increase, remainder, and difference, regroup by place value, and check every operation with its inverse.", "With place value in place, we study how quantities change.", "Adding 157 to 268 to get 425 and reversing the path by subtraction", "Combining two boxes of objects suggests addition; removing one part from a whole suggests subtraction. The same three numbers form a family of related facts.", "Addition finds a whole from parts or a value after an increase. Subtraction finds a remainder, a difference, or the original value.", "part + part = whole; whole − part = other part; addition ↔ subtraction", "`268 + 157 = 425`. Check: `425 − 157 = 268`; the inverse operation returns the starting number.", "In `217 + 185 = 392`, the ones were handled but a regrouped ten was lost. Recalculating by place gives `402`.", "Solve `487 + 368` and `700 − 456`, check each with the inverse operation, and write one joining problem and one comparison problem.", "The next lesson turns repeated equal additions into multiplication and equal sharing into division."),
    },
    "13-multiplication-division": {
        "kz": E("Көбейту мен бөлу: тең топтар және екі сұрақ", "Көбейтуді тең топтардың қысқа жазбасы деп түсінеміз, ал бөлудің «неше топ?» және «әр топта нешеу?» деген екі мағынасын ажыратамыз.", "Қосу мен азайтудан тең топтар әрекетіне өтеміз.", "Төрт қатардағы алты нүкте және 24-ті екі тәсілмен бөлу", "Әрқайсысында алтыдан төрт табақ болса, бірдей қосылғышты төрт рет жазудың орнына `4 × 6` дейміз.", "Көбейту топ саны мен топ көлемінен жалпы мөлшерді табады. Бөлу жалпы мөлшерден топ санын немесе бір топтың көлемін табады.", "топ саны × топ көлемі = барлығы; барлығы ÷ бір көбейткіш = екінші көбейткіш", "`4 × 6 = 24`; сондықтан `24 ÷ 6 = 4` топ және `24 ÷ 4 = 6` заттан.", "`24 ÷ 6 = 6` деу екі сұрақты шатастырады. Алтыдан неше топ барын нақты заттармен орналастырсақ, төрт топ шығады.", "24 затты әртүрлі тікбұрышты массивтерге орналастырып, әрқайсына бір көбейту және екі бөлу теңдігін жазыңыз.", "Келесі сабақ күрделі өрнекте қай амалды бірінші орындау керегін және жауапты шамалауды үйретеді."),
        "en": E("Multiplication and division: equal groups and two questions", "We understand multiplication as shorthand for equal groups and distinguish division as asking either “how many groups?” or “how many in each group?”", "We move from addition and subtraction to operations on equal groups.", "Four rows of six dots and two ways to divide 24", "If four trays hold six items each, we can write `4 × 6` instead of repeating the same addend four times.", "Multiplication finds a total from the number and size of equal groups. Division uses the total to find either the number of groups or the size of each group.", "number of groups × group size = total; total ÷ one factor = the other factor", "`4 × 6 = 24`; therefore `24 ÷ 6 = 4` groups and `24 ÷ 4 = 6` in each group.", "Writing `24 ÷ 6 = 6` confuses the two division questions. Arranging objects into groups of six shows that there are four groups.", "Arrange 24 objects into different rectangular arrays and write one multiplication fact and two division facts for each array.", "The next lesson decides which operation comes first in a longer expression and uses estimation to check the result."),
    },
    "14-order-estimation": {
        "kz": E("Амалдар реті және шамалау: есептемей тұрып жауапты болжау", "Жақшаның құрылымын оқимыз, амалдарды дұрыс ретпен орындаймыз және өрескел қатені нәтижені алдын ала шамалау арқылы табамыз.", "Негізгі төрт амал енді бір өрнекте кездеседі.", "240 − 6 × (18 + 7) өрнегінің есептеу ағашы және 90 бағасы", "Ас әзірлеу нұсқаулығында қадамдар ретсіз орындалса, нәтиже өзгереді. Жақша математикалық нұсқаулықтағы алдымен орындалатын бөлікті көрсетеді.", "Алдымен жақша, кейін дәреже, одан соң көбейту мен бөлу, соңында қосу мен азайту орындалады. Бір деңгейдегі амалдар солдан оңға жүреді.", "құрылымды оқу → шамалау → ретімен есептеу → шамамен салыстыру", "`240 − 6 × (18 + 7)`: жақша `25`, көбейтінді `150`, сонда `240 − 150 = 90`.", "`240 − 6 × 25 = 234 × 25` деу азайтуды көбейтуден бұрын орындаған. Өрнек ағашы `6 × 25` тармағын алдымен аяқтауды көрсетеді.", "`360 ÷ (8 + 4) + 7 × 5` мәнін алдымен шамалап, кейін дәл есептеңіз және екі нәтижені салыстырыңыз.", "Теріс сандар сан осін нөлдің сол жағына кеңейтіп, азайтудың жаңа мағынасын ашады."),
        "en": E("Order of operations and estimation: predict before calculating", "We read the structure of parentheses, perform operations in the correct order, and use an advance estimate to catch unreasonable results.", "The four basic operations now meet in one expression.", "Expression tree for 240 − 6 × (18 + 7) and an estimate of 90", "A recipe changes if its steps are carried out in the wrong order. Parentheses mark the part of a mathematical instruction that must be completed first.", "Do parentheses first, then powers, multiplication and division, and finally addition and subtraction. Operations at the same level proceed from left to right.", "read structure → estimate → calculate in order → compare with estimate", "For `240 − 6 × (18 + 7)`, the parentheses give `25`, the product is `150`, and `240 − 150 = 90`.", "Turning `240 − 6 × 25` into `234 × 25` performs subtraction too early. The expression tree shows that the `6 × 25` branch must be completed first.", "Estimate and then calculate `360 ÷ (8 + 4) + 7 × 5`; compare the exact result with your estimate.", "Negative numbers extend the number line to the left of zero and reveal another meaning of subtraction."),
    },
    "15-negative-numbers": {
        "kz": E("Теріс сандар: нөлден солға қарай да қашықтық бар", "Теріс санды қарыз, температура және бағыт арқылы түсінеміз, сан осінде қозғалып, таңба мен амал белгісін ажыратамыз.", "Сан осін натурал сандардан бүтін сандарға дейін кеңейтеміз.", "−3 нүктесінен оңға жеті қадам жүріп 4-ке жету", "Температура `0°C`-тан үш градус төмен болса, ол `−3°C`. Жеті градус жылынса, сан осімен оңға жеті қадам жасаймыз.", "Теріс сан нөлден кіші мәнді білдіреді. Санның алдындағы минус оның таңбасы, ал екі сан арасындағы минус азайту амалы болуы мүмкін.", "оңға → арту; солға → кему; қарама-қарсы сандардың нөлден қашықтығы бірдей", "`−3 + 7 = 4`: −3-тен оңға жеті қадам −2, −1, 0, 1, 2, 3, 4 нүктелерінен өтеді.", "`−5` саны `−2`-ден үлкен деу қате. Сан осінде −5 сол жақта орналасқан, сондықтан `−5 < −2`.", "Сан осінде `−6 + 9`, `4 − 11`, `−3 − 5` амалдарын көрсетіп, әр қозғалыстың бағытын сөзбен түсіндіріңіз.", "Бөлінгіштік сандарды көбейткіштерден қалай құрауға және бөлшектерді қалай қысқартуға болатынын ашады."),
        "en": E("Negative numbers: distance also extends left of zero", "We understand negative numbers through debt, temperature, and direction, move on a number line, and separate a number’s sign from an operation sign.", "We extend the number line from natural numbers to integers.", "Seven steps to the right from −3 ending at 4", "A temperature three degrees below `0°C` is `−3°C`. If it rises by seven degrees, we move seven steps to the right on the number line.", "A negative number represents a value below zero. A minus attached to a number is its sign; a minus between two numbers can mean subtraction.", "right → increase; left → decrease; opposite numbers are equally far from zero", "`−3 + 7 = 4`: seven steps right from −3 pass −2, −1, 0, 1, 2, 3, and end at 4.", "Saying `−5` is greater than `−2` is wrong. −5 lies farther left on the number line, so `−5 < −2`.", "Show `−6 + 9`, `4 − 11`, and `−3 − 5` on a number line and describe the direction of every movement.", "Divisibility reveals how numbers are built from factors and prepares us to simplify fractions."),
    },
    "16-divisibility-primes": {
        "kz": E("Бөлінгіштік және жай сандар: санның ішкі құрылысы", "Еселік пен бөлгішті ажыратып, жай көбейткіштерге жіктейміз және бөлінгіштік белгілерін мағынасымен қолданамыз.", "Бүтін сандарды олардың көбейту құрылымы арқылы зерттейміз.", "84 санының 2 × 2 × 3 × 7 жай көбейткіштер ағашы", "84 затты тең топтарға бөлуге болатын әр тәсіл оның бөлгішін көрсетеді. Ағаш тармақтары құрама санды енді бөлінбейтін жай сандарға дейін ашады.", "`a` саны `b`-ге қалдықсыз бөлінсе, `b` — бөлгіш, ал `a` — оның еселігі. Жай санның дәл екі оң бөлгіші бар: 1 және өзі.", "бөлгіш жұптары → жай көбейткіштер → көбейтіндімен кері тексеру", "`84 = 4 × 21 = (2 × 2) × (3 × 7) = 2² × 3 × 7`.", "1-ді жай сан деу қате: жай санның екі әртүрлі оң бөлгіші болуы керек, ал 1-дің тек бір бөлгіші бар.", "90 және 126 сандарын жай көбейткіштерге жіктеп, көбейтіндімен тексеріңіз; олардың ең үлкен ортақ бөлгішін табыңыз.", "Ондық бөлшектер разрядтық жүйені бірліктен кіші үлестерге жалғастырады."),
        "en": E("Divisibility and primes: the internal structure of a number", "We distinguish multiples from factors, decompose numbers into prime factors, and use divisibility tests with meaning.", "We investigate integers through their multiplicative structure.", "Prime-factor tree showing 84 as 2 × 2 × 3 × 7", "Every way to arrange 84 objects into equal groups identifies a factor. A factor tree opens a composite number until only primes remain at its leaves.", "If `a` divides by `b` with no remainder, `b` is a factor and `a` is a multiple of `b`. A prime number has exactly two positive factors: 1 and itself.", "factor pairs → prime factors → multiply back to check", "`84 = 4 × 21 = (2 × 2) × (3 × 7) = 2² × 3 × 7`.", "Calling 1 a prime number is wrong: a prime needs two distinct positive factors, while 1 has only one.", "Factor 90 and 126 into primes, multiply back to check, and find their greatest common factor.", "Decimals extend the place-value system to parts smaller than one."),
    },
    "17-decimal-fractions": {
        "kz": E("Ондық бөлшектер: үтірдің оң жағындағы разрядтар", "Ондық бөлшекті ондық жүйенің жалғасы деп оқимыз, жай бөлшекпен байланыстырамыз және мәнді үтірді механикалық жылжытпай салыстырамыз.", "Разрядтық жүйе енді бірліктен кіші ондық, жүздік және мыңдық үлестерге өтеді.", "3/8 бөлшегін 375/1000 және 0,375 түріне айналдыру", "Бір бүтінді он тең бөлікке бөлсек — ондық үлес, әрқайсын тағы онға бөлсек — жүздік үлес шығады.", "`0,375` дегеніміз 0 бірлік, 3 ондық, 7 жүздік және 5 мыңдық үлес. Ол `375/1000`, ал қысқартқанда `3/8`.", "разряд атауы → жай бөлшек → ондық жазу → сан осіндегі бір нүкте", "`3/8 = 375/1000 = 0,375`, өйткені алым мен бөлімді 125-ке көбейттік.", "`0,5 < 0,45`, өйткені 5 < 45 деу қате. Бірдей разрядқа келтірсек `0,50 > 0,45`.", "`7/20`, `13/25`, `9/8` бөлшектерін ондық түрде жазып, сан осіне орналастырыңыз және ең үлкенін атаңыз.", "Іргетас бақылауы сан, амал, бағалау, теріс сан және ондық бөлшектерді бір тапсырмалар жүйесінде біріктіреді."),
        "en": E("Decimals: place values to the right of the point", "We read decimals as a continuation of base ten, connect them to common fractions, and compare values without mechanically moving a point.", "The place-value system now continues below one into tenths, hundredths, and thousandths.", "Converting 3/8 into 375/1000 and 0.375", "Dividing one whole into ten equal parts creates tenths; dividing each tenth into ten creates hundredths.", "`0.375` means 0 ones, 3 tenths, 7 hundredths, and 5 thousandths. It is `375/1000`, which simplifies to `3/8`.", "place name → common fraction → decimal notation → same point on the number line", "`3/8 = 375/1000 = 0.375` because numerator and denominator were both multiplied by 125.", "Saying `0.5 < 0.45` because 5 < 45 is wrong. Writing equal places gives `0.50 > 0.45`.", "Write `7/20`, `13/25`, and `9/8` as decimals, place them on a number line, and identify the greatest.", "The foundation checkpoint combines number, operations, estimation, negatives, and decimals in one set of tasks."),
    },
    "18-foundations-mastery": {
        "kz": E("Бақылау нүктесі: сандық іргетасты өз бетіңізше қолдану", "Он жаңа тапсырма санау, разряд, төрт амал, амалдар реті, теріс сан, бөлінгіштік және ондық бөлшектерді түсіндіру мен көшіру арқылы тексереді.", "Бұл — бірінші толық тірек блогының тексеруі. Кемінде 8/10 нәтиже және түсіндірілген тәсіл келесі бөлімге дайындықты көрсетеді.", "Сандық іргетастың сегіз дағдысы және екі аралықтағы нәтиже", "Баспалдақтың бір сатысы бос болса, жоғары көтерілу қауіпті. Бақылау әр қатені өз тақырыбына қайтаратын карта ретінде қолданылады.", "Меңгеру тек дұрыс жауап саны емес. Оқушы модельді таңдап, есептеп, нәтижені тексеріп, қатесін түсіндіре және ұқсас емес жағдайда қолдана алуы керек.", "10 жаңа тапсырма → тәсілді көрсету → 8/10 → қатені жөндеу → жеті күннен кейін қайта тексеру", "`4 072` санын жіктеу, `−3 + 7` қозғалысын көрсету және `3/8 = 0,375` байланысын түсіндіру үш түрлі ұғымды сан осі мен разряд арқылы біріктіреді.", "Дұрыс жауапты дәлелсіз көшіру меңгеру емес. Әр есепте кемінде бір модель, аралық қадам немесе кері тексеру болуы тиіс.", "Барлық он тапсырманы тірексіз орындаңыз, сенім белгісін қойыңыз және қате кеткен тақырыпқа қайтыңыз. Жеті күннен кейін сандары өзгерген нұсқаны қайталаңыз.", "Іргетас берік болса, бөлшектер мен пропорционалдықты жеке ережелер емес, санның табиғи жалғасы ретінде оқимыз."),
        "en": E("Checkpoint: use the numerical foundations independently", "Ten new tasks test counting, place value, four operations, operation order, negatives, divisibility, and decimals through explanation and transfer.", "This checkpoint closes the first complete support block. At least 8/10 with explained methods indicates readiness for the next section.", "Eight numerical foundation skills and results from two attempts", "A staircase is unsafe if one step is missing. The checkpoint acts as a map that sends each error back to the idea that needs repair.", "Mastery is more than a count of correct answers. A learner must choose a model, calculate, check, explain an error, and transfer the idea to a less familiar setting.", "10 new tasks → show method → 8/10 → repair errors → retest after seven days", "Expanding `4,072`, showing the movement `−3 + 7`, and explaining `3/8 = 0.375` connect three different ideas through place value and the number line.", "Copying a correct answer without a reason is not mastery. Each solution needs a model, an intermediate step, or an inverse check.", "Complete all ten tasks without the support page, mark confidence, and revisit the topic behind every error. Repeat with changed numbers after seven days.", "With secure foundations, fractions and proportional reasoning become natural extensions of number rather than isolated rules."),
    },
    "02-fraction-meaning": {
        "kz": E("Бөлшек — бірінің үстіне бірі жазылған екі сан емес", "Бүтіннің бөлігі, өлшеу, бөлу және сан осіндегі нүктені байланыстырып, алым мен бөлімге нақты мағына береміз.", "Бүтін сандардан бірліктен кіші және бірліктен үлкен бөлшек сандарға өтеміз.", "Сегіз тең бөліктің үшеуі және сан осіндегі 3/8 нүктесі", "Бірдей пиццаны сегіз тең бөлікке бөліп, үшеуін алу — `3/8`. Бөліктер міндетті түрде тең болуы керек.", "Бөлім бүтіннің неше тең үлеске бөлінгенін, алым сол үлестің нешеуі алынғанын көрсетеді. `a/b` сонымен бірге `a ÷ b` саны.", "бірлік → тең үлестер → бір үлестің көлемі → алынған үлестер саны", "`3/8` үшін бірлік сегіз тең бөлікке бөлінеді, үшеуі алынады; нүкте 0 мен 1 арасында, нөлден үш сегіздік қашықта.", "`3/8` бен `3/5`-те алым бірдей болғандықтан сандар тең деу қате: бестен бір үлес сегізден бір үлестен үлкен.", "12 бірдей шелекке толатын ыдыста 7 шелек су бар. Толған бөлікті бөлшекпен, бөлуді және сан осін қолданып көрсетіңіз.", "Келесі сабақ бір нүктені әртүрлі бөлшекпен қалай жазуға болатынын түсіндіреді."),
        "en": E("A fraction is a number, not two numbers stacked together", "We connect part of a whole, measurement, division, and a point on a line so numerator and denominator gain precise meaning.", "We move from whole numbers to fractional numbers below and above one.", "Three of eight equal parts and the point 3/8 on a number line", "Cutting one pizza into eight equal pieces and taking three gives `3/8`. Equal parts are essential.", "The denominator tells how many equal parts make the whole; the numerator tells how many are selected. `a/b` is also the number `a ÷ b`.", "unit → equal parts → size of one part → number of selected parts", "For `3/8`, divide one unit into eight equal parts and take three; its point lies between 0 and 1, three eighths from zero.", "It is wrong to call `3/8` and `3/5` equal because their numerators match: a fifth is larger than an eighth.", "A tank holds 12 equal buckets and already contains 7. Represent the filled amount as a fraction, a division, and a point on a line.", "The next lesson shows how different fraction notations can name the same point."),
    },
    "03-equivalent-fractions": {
        "kz": E("Тең бөлшектер: үлес өлшемін өзгертіп, санды сақтау", "Негізгі бөлшек қасиетін бір ұзындық арқылы шығарып, санды өзгертпей жазуды қысқартамыз.", "Бөлшектің мағынасы дайын; енді бір мәннің бірнеше жазуын байланыстырамыз.", "Бірдей ұзындықты көрсететін 1/2 және 2/4 жолақтары", "Жарты жолақты әр бөлігін тағы екіге бөлсек, боялған ұзындық өзгермейді, бірақ атауы `2/4` болады.", "Алым мен бөлімді бірдей нөлден өзге санға көбейту немесе бөлу бөлшектің мәнін сақтайды: `a/b = ak/bk`.", "үстін де, астын да ×k → үлес ұсақталады → алынған саны өседі → нүкте өзгермейді", "`14/21 = 2/3`, өйткені алым мен бөлімді 7-ге бөлдік. Кері тексеру: `2/3 × 7/7 = 14/21`.", "`1/2 = 2/3` деп алым мен бөлімге 1 қосу қате: бұл бір бүтінді басқа өлшемді үлестерге бөліп, нүктені өзгертеді.", "`14/21` және `10/15` тең екенін қысқарту, айқыш көбейту және сан осі арқылы дәлелдеңіз.", "Ортақ үлестер тең емес бөлшектерді бір шкалада салыстыруға мүмкіндік береді."),
        "en": E("Equivalent fractions: change part size while preserving value", "We derive the fundamental fraction property from one length and simplify notation without changing the number.", "The meaning of a fraction is secure; now we connect several notations for one value.", "Strips showing the same length as 1/2 and 2/4", "Split each part of a half into two again. The shaded length stays fixed, although its name becomes `2/4`.", "Multiplying or dividing numerator and denominator by the same nonzero number preserves value: `a/b = ak/bk`.", "×k on top and bottom → smaller parts → more selected parts → same point", "`14/21 = 2/3` because both terms divide by 7. Check backward: `2/3 × 7/7 = 14/21`.", "Changing `1/2` to `2/3` by adding 1 to both terms is wrong: it changes the size of the parts and moves the point.", "Prove that `14/21` and `10/15` are equal by simplifying, cross-products, and a number-line model.", "Common-sized parts let us compare unequal fractions on one scale."),
    },
    "04-compare-fractions": {
        "kz": E("Бөлшектерді салыстыру: сандарды бір шкалаға қою", "Бөлшектерді ортақ үлестер, сан осі және 0, 1/2, 1 бағдарларымен салыстырып, нәтижені шамамен тексереміз.", "Тең бөлшектерді пайдаланып, әртүрлі жазуларды ретке келтіреміз.", "1/2 және 2/3 нүктелерін алтыншы үлестер шкаласында салыстыру", "Екі түрлі жолдың қанша бөлігі жүргенін тек бірдей толық ұзындық пен бірдей өлшемді үлестерде әділ салыстыруға болады.", "Ортақ бөлім үлестерді бірдей етеді; ортақ алым алынған үлес санын теңестіреді; бағдарлар санның шамасын жылдам тексереді.", "бір бүтін → бір шкала → сан осіндегі нүктелер → сол/оң → бағдармен тексеру", "`3/4 = 9/12`, `2/3 = 8/12`, сондықтан `3/4 > 2/3`; екі сан да 1-ден кіші деген бағамен үйлеседі.", "Бөлімі үлкен бөлшек әрқашан үлкен деу қате. Бір алымда керісінше: `3/8 < 3/5`, өйткені сегіздік үлес ұсақ.", "`7/8`, `5/6`, `11/12`, `3/4` сандарын өсу ретімен орналастырып, ортақ бөлім және бағдар арқылы тексеріңіз.", "Салыстырудан кейін бөлшектермен төрт амалды мағынасына сүйеніп орындаймыз."),
        "en": E("Comparing fractions: put the numbers on one scale", "We compare fractions through common parts, a number line, and benchmarks 0, 1/2, and 1, then check the order by estimation.", "Equivalent fractions now help us order different values.", "Comparing 1/2 and 2/3 on a scale divided into sixths", "Progress along two routes can only be compared fairly when the whole routes and units of measure agree.", "A common denominator makes part sizes equal; a common numerator equalizes selected counts; benchmarks provide a fast magnitude check.", "one whole → one scale → points on a line → left/right → benchmark check", "`3/4 = 9/12` and `2/3 = 8/12`, so `3/4 > 2/3`; both also remain below 1.", "The larger denominator does not automatically mean a larger fraction. With equal numerators, `3/8 < 3/5` because eighths are smaller.", "Order `7/8`, `5/6`, `11/12`, and `3/4`; verify with a common denominator and benchmarks.", "Next we perform all four fraction operations from their meanings."),
    },
    "05-fraction-operations": {
        "kz": E("Бөлшектермен амалдар: алдымен санау бірлігін атаңыз", "Қосу, азайту, көбейту және бөлуді байланыссыз төрт ереже емес, амалдардың мағынасы арқылы орындаймыз.", "Бөлшектерді танып және салыстырып болған соң олармен есептейміз.", "1/2 + 1/3 қосындысын алтыншы үлестер арқылы 5/6 ету", "Жарты алма мен үштен бір алманы тікелей «екі бөлік» деп қосуға болмайды: үлес өлшемдері әртүрлі.", "Қосу мен азайтуға ортақ санау бірлігі керек. Көбейту — бір санның бөлігін алу, бөлу — берілген үлестің неше рет сыятынын сұрау.", "бірлік атауы → модель таңдау → есептеу → кері амал не бағамен тексеру", "`1/2 + 1/3 = 3/6 + 2/6 = 5/6`. Жауап 1-ден кіші және екі қосылғыштың әрқайсысынан үлкен.", "`1/2 + 1/3 = 2/5` деу алым мен бөлімді жеке қосады, бірақ әртүрлі үлестерді бір санау бірлігіне келтірмейді.", "`7/8` парақтан әр бұйымға `3/16` кетсе, неше толық бұйым шығатынын және қанша материал қалатынын табыңыз.", "Бөлшектер арасындағы тұрақты байланыс қатынас ұғымына әкеледі."),
        "en": E("Operations with fractions: name the counting unit first", "We add, subtract, multiply, and divide fractions through meanings of operations rather than four unrelated rules.", "After recognizing and comparing fractions, we calculate with them.", "Turning 1/2 + 1/3 into 5/6 by counting sixths", "Half an apple and one third of an apple cannot be counted simply as “two parts” because the part sizes differ.", "Addition and subtraction need a common counting unit. Multiplication takes a part of a number; division asks how many portions of a given size fit.", "name the unit → choose a model → calculate → check by inverse or estimate", "`1/2 + 1/3 = 3/6 + 2/6 = 5/6`. The answer is below 1 and greater than either addend.", "Writing `1/2 + 1/3 = 2/5` adds tops and bottoms separately but never creates a common counting unit.", "A workshop has `7/8` of a sheet and uses `3/16` per item. Find the number of complete items and the material left.", "A relationship between two changing quantities leads to the idea of ratio."),
    },
    "06-ratio": {
        "kz": E("Қатынас: кез келген масштабта сақталатын рецепт", "`2:3` жазуын екі шаманың байланысы ретінде түсініп, тең қатынастар кестесін құрамыз және бірлікке шаққан мәнді табамыз.", "Бөлшек бір шаманы өлшейді; қатынас екі шаманы белгілі ретпен салыстырады.", "2:3 қатынасының екі есе үлкейіп 4:6 болуы", "Екі үлес шырынға үш үлес су қосылған рецептті екі есе көбейтсек, екі сан да бірге өзгереді.", "`a:b` реті маңызды. Шамалардың бірліктерін келісіп, екеуін де бір коэффициентке көбейту немесе бөлу қатынасты сақтайды.", "ретті атау → бірліктерді келісу → бір үлесті табу → екі шаманы бірге масштабтау", "`2:3 = 4:6`: екі мүшені де 2-ге көбейттік. Айқыш көбейтінділер де тең: `2 × 6 = 3 × 4`.", "`2:3` қатынасына тек бірінші санды қосып `4:3` алу рецептті сақтамайды; екі шама бір коэффициентпен өзгеруі тиіс.", "Көк және ақ бояу `3:5` қатынасында араласады. 32 литр қоспада әр түстен қанша литр барын табыңыз.", "Жүзден бір үлеске негізделген пайыз қатынастың күнделікті арнайы тілі болады."),
        "en": E("Ratio: a recipe that survives every scale", "We read `2:3` as a relationship between two quantities, build tables of equivalent ratios, and find a unit rate.", "A fraction measures one quantity; a ratio compares two quantities in a stated order.", "Scaling the ratio 2:3 by two to obtain 4:6", "If a drink uses two parts juice to three parts water, doubling the recipe must change both amounts together.", "Order matters in `a:b`. After matching units, multiplying or dividing both terms by the same factor preserves the ratio.", "state the order → align units → find one part → scale both quantities together", "`2:3 = 4:6` because both terms were multiplied by 2. Cross-products confirm it: `2 × 6 = 3 × 4`.", "Changing only the first term from `2:3` to `4:3` does not preserve the recipe; both quantities need the same scale factor.", "Blue and white paint are mixed in a `3:5` ratio. Find each amount in 32 litres of mixture.", "Percent is a widely used ratio language built around one hundred parts."),
    },
    "07-percent": {
        "kz": E("Пайыз: үш формуланың орнына жүзден бір үлес", "Пайызды бөлшек және ондық санмен байланыстырып, жеңілдік пен өсімді бірлік арқылы есептейміз және үлестің қай негізден алынғанын тексереміз.", "Қатынастың арнайы түрін — 100-ге қатысты салыстыруды зерттейміз.", "Жүз ұяшықтың 37-сі боялып, 37% = 37/100 көрсетілуі", "Жүз тең ұяшықтың 37-сі боялса, ол `37/100 = 0,37 = 37%`.", "Пайыз — жүзден бір үлес. Есептеуде әрқашан 100% болатын негізді атау керек; негіз өзгерсе, бірдей сан басқа пайыз береді.", "100% негізін атау → пайызды үлеске айналдыру → көбейту → нәтижені шамамен тексеру", "80 000 теңгенің 15%-ы `80 000 × 0,15 = 12 000`; жеңілдіктен кейін `68 000` қалады.", "20% төмендеп, кейін 20% өскенде бастапқы мән қайтады деу қате: екінші пайыз кішірек жаңа негізден алынады.", "80 000 теңге бағаға алдымен 15%, кейін жаңа бағаға 10% жеңілдік қолданылып, жалпы төмендеу пайызын табыңыз.", "Пропорция пайыз бен масштаб есептерінде қандай қатынас тұрақты қалатынын айқын көрсетеді."),
        "en": E("Percent: one hundredth instead of three formulas", "We connect percent to fractions and decimals, calculate discounts and growth through a unit, and identify the base from which a percentage is taken.", "We study a special ratio: comparison with one hundred.", "Thirty-seven shaded cells out of one hundred showing 37% = 37/100", "If 37 of 100 equal cells are shaded, the amount is `37/100 = 0.37 = 37%`.", "Percent means one hundredth. Every problem needs a named 100% base; when the base changes, the same amount represents a different percentage.", "name the 100% base → convert percent to a fraction → multiply → estimate the size", "15% of 80,000 tenge is `80,000 × 0.15 = 12,000`; the discounted price is `68,000`.", "A 20% decrease followed by a 20% increase does not restore the original value because the second percentage uses a smaller new base.", "Apply a 15% discount to 80,000 tenge, then 10% to the new price, and find the total percentage decrease.", "Proportion makes the invariant relationship in percent and scale problems explicit."),
    },
    "08-proportion": {
        "kz": E("Пропорция және масштаб: қандай байланыс сақталуы керек", "Өзгермейтін қатынас арқылы пропорция шешіп, тура және кері тәуелділікті ажыратамыз және өлшем бірліктерін тексереміз.", "Тең қатынастардан белгісіз шаманы табуға өтеміз.", "2/3 = 6/9 теңдігі және екі шаманы үш есе масштабтау", "Картадағы 2 см шындықтағы 3 км болса, картадағы 6 см сол масштабта 9 км-ге сәйкес келеді.", "Тура пропорцияда екі шама бір коэффициентпен өзгереді; кері пропорцияда олардың көбейтіндісі тұрақты қалады.", "не өзгермейді? → тура ма, кері ме? → бірліктер → есептеу → мағынамен тексеру", "`2/3 = 6/9`, өйткені екі сан да 3 есе өсті; `2 × 9 = 3 × 6` теңдігі тексеруді береді.", "Жұмысшы саны екі есе артса, уақыт та екі есе артады деу қате (бірдей өнімділікте): жұмысшы × уақыт тұрақты.", "3 л концентрат 12 л сумен араласады. Сол құрамдағы 35 л ерітіндіге әр компоненттен қанша керегін табыңыз.", "Бақылау нүктесі бөлшек, қатынас, пайыз және пропорцияны жаңа жағдайларда біріктіреді."),
        "en": E("Proportion and scale: which relationship must stay fixed?", "We solve proportions through an invariant ratio, distinguish direct and inverse relationships, and check units.", "We move from equivalent ratios to finding an unknown quantity.", "The equality 2/3 = 6/9 produced by scaling both quantities by three", "If 2 cm on a map represents 3 km, then 6 cm at the same scale represents 9 km.", "In direct proportion both quantities change by the same factor; in inverse proportion their product remains constant.", "what stays fixed? → direct or inverse? → units → calculate → check meaning", "`2/3 = 6/9` because both values tripled; `2 × 9 = 3 × 6` provides a check.", "Saying twice as many equally productive workers need twice as much time is wrong: workers × time stays constant.", "Three litres of concentrate mix with 12 litres of water. Find each component in 35 litres of the same solution.", "The checkpoint combines fractions, ratio, percent, and proportion in unfamiliar settings."),
    },
    "09-mastery": {
        "kz": E("Бақылау нүктесі: бөлшектер, қатынас, пайыз және көшіру", "Он жаңа тапсырма модельді, есептеуді, түсіндіруді, қатені түзетуді және білімді жаңа жағдайға көшіруді тексереді.", "Пропорционалдық блогын аяқтап, келесі алгебралық тілге дайындықты тексереміз.", "Бес дағды және алғашқы әрекет пен жеті күннен кейінгі нәтиже", "Спорттағы бір жарыс кездейсоқ болуы мүмкін; тұрақты дағды әртүрлі жағдайда және уақыт өткен соң қайта көрінеді.", "Кемінде 8/10 — бағдар. Маңыздысы: әр жауаптың моделі, өлшем бірлігі, тексеруі және қате болса қай тірекке қайту керегі.", "модель → есептеу → түсіндіру → қатені түзету → жаңа жағдай → аралықпен қайталау", "`37% = 37/100`, `2:3 = 4:6` және `3/8 = 0,375` жазулары әртүрлі, бірақ барлығы бөліктер мен бірлік арасындағы байланысты көрсетеді.", "Калькулятор берген санды өлшем бірліксіз жазу толық шешім емес. Санның нені білдіретінін және оның шамасы қисынды екенін көрсету керек.", "Он тапсырманың бәрін шешіп, әр тәсілді көрсетіңіз. 8/10-нан төмен тақырыптарды қайталап, жеті күннен кейін сандары өзгерген нұсқаны орындаңыз.", "Келесі блок әріптерді шамалардың атауы ретінде енгізіп, өрнек пен теңдеуге алып барады."),
        "en": E("Checkpoint: fractions, ratios, percentages, and transfer", "Ten new problems test modeling, calculation, explanation, error correction, and transfer to a new setting.", "We close proportional reasoning and check readiness for algebraic language.", "Five skills and results from a first attempt and seven days later", "One successful sports attempt can be luck; a stable skill reappears under changed conditions and after time has passed.", "At least 8/10 is a guide. Every answer still needs a model, units, a check, and a route back to the support behind an error.", "model → calculate → explain → correct error → new setting → delayed recall", "`37% = 37/100`, `2:3 = 4:6`, and `3/8 = 0.375` look different, yet all express relationships between parts and a unit.", "A calculator output without units is not a complete solution. State what the number means and why its size is reasonable.", "Solve all ten tasks and show each method. Revisit topics below 8/10 and repeat a changed version after seven days.", "The next block introduces letters as names for quantities and leads to expressions and equations."),
    },
    "19-variables": {
        "kz": E("Айнымалы: әріп өзгеретін шаманың мәнін сақтайды", "Әріпті жасырын сан емес, мағынасы, бірлігі және өзгеру шекарасы бар шаманың атауы ретінде оқимыз.", "Нақты сандардан шамалар арасындағы жалпы байланысты жазатын алгебралық тілге өтеміз.", "C = 700 + 120d жол жүру бағасының моделі", "Таксидің бағасы 700 теңге тұрақты төлемнен және әр километрге 120 теңгеден құралады. Қашықтық өзгергенде жалпы баға да өзгереді.", "Айнымалы — мәні өзгеруі мүмкін шаманың белгісі. Оның нені білдіретінін, өлшем бірлігін және рұқсат етілген мәндерін әрқашан атау керек.", "шаманы атау → әріп пен бірлік → байланыс формуласы → мән қою → мағынамен тексеру", "`C = 700 + 120d`; `d = 5 км` болса, `C = 700 + 120 × 5 = 1300` теңге.", "`d = 5` қойғанда `700 + 120 + 5` жазу қате: 120 әр километр үшін алынады, сондықтан `120d` көбейтінді.", "Осы модельмен 0, 3 және 12 км бағасын табыңыз; әр айнымалының мағынасы мен бірлігін жазыңыз.", "Айнымалылардан құралған өрнекті мәнін сақтап ықшамдауды үйренеміз."),
        "en": E("Variables: a letter holds the value of a changing quantity", "We read a letter as the name of a quantity with meaning, units, and a valid range rather than as a mysterious hidden number.", "We move from particular numbers to algebraic language that records a general relationship.", "The travel-cost model C = 700 + 120d", "A taxi fare combines a fixed 700 tenge charge with 120 tenge for every kilometre. As distance changes, total cost changes.", "A variable represents a quantity whose value may change. Always state its meaning, units, and allowed values.", "name quantity → letter and unit → relationship → substitute → check meaning", "`C = 700 + 120d`; for `d = 5 km`, `C = 700 + 120 × 5 = 1300` tenge.", "Replacing `d` with 5 as `700 + 120 + 5` is wrong: 120 is charged for each kilometre, so `120d` is a product.", "Use the model to find costs for 0, 3, and 12 km; state every variable’s meaning and unit.", "Next we simplify expressions made from variables without changing their value."),
    },
    "20-expressions": {
        "kz": E("Өрнектер: мағынаны өзгертпей жазуды ықшамдау", "Жақшаны ашып, ұқсас мүшелерді біріктіреміз және әр түрлендіруді мән қою арқылы тексереміз.", "Айнымалы енді амалдармен байланысып, өрнек құрайды.", "3(2x + 5) − 4x өрнегінің 2x + 15 түріне дейінгі жолы", "Бір затты әртүрлі ретпен жинақтауға болады: алты жеке қорап пен тағы он бес затты екі үлкен топ және он бес зат деп қайта топтастыру мәнді өзгертпейді.", "Ұқсас мүшелердің айнымалы бөлігі бірдей. Үлестірімділік `a(b+c)=ab+ac` жақшаның сыртындағы көбейткішті әр мүшеге таратады.", "құрылымды оқу → жақшаны ашу → ұқсас мүшелерді жинау → бір мәнмен тексеру", "`3(2x + 5) − 4x = 6x + 15 − 4x = 2x + 15`; `x=4` болса, екі жазу да 23 береді.", "`3(2x+5)=6x+5` деу қате: 3 жақшадағы екі мүшеге де көбейтіледі, сондықтан тұрақты мүше 15.", "`5(2a−3)+4a−7` өрнегін ықшамдап, `a=2` мәнімен бастапқы және жаңа жазуды тексеріңіз.", "Теңдеу өрнектің мәні белгілі болғанда белгісіз шаманы табуды сұрайды."),
        "en": E("Expressions: simplify notation without changing value", "We expand parentheses, combine like terms, and check every transformation by substitution.", "A variable now joins operations to form an expression.", "The path from 3(2x + 5) − 4x to 2x + 15", "The same collection can be regrouped without changing its quantity. Algebraic rewriting does the same when its properties are respected.", "Like terms have the same variable part. Distribution `a(b+c)=ab+ac` sends the outside factor to every term inside.", "read structure → distribute → combine like terms → check one value", "`3(2x + 5) − 4x = 6x + 15 − 4x = 2x + 15`; both forms equal 23 at `x=4`.", "Writing `3(2x+5)=6x+5` is wrong: 3 multiplies both terms, so the constant becomes 15.", "Simplify `5(2a−3)+4a−7` and verify the original and new forms at `a=2`.", "An equation asks for an unknown quantity when the value of an expression is known."),
    },
    "21-equations-basic": {
        "kz": E("Теңдеулер: теңдіктің екі жағын тепе-тең ұстау", "Белгісізді оқшаулау үшін теңдіктің екі жағына бірдей амал жасап, шешімді бастапқы теңдеуге қою арқылы тексереміз.", "Өрнектер арасындағы теңдік белгісіз мәнді табу міндетіне айналады.", "3x + 5 = 26 теңдеуінің таразы тепе-теңдігі", "Таразының екі табағына бірдей өзгеріс жасалса, тепе-теңдік сақталады. Теңдеудің екі жағына да сол амал қолданылуы керек.", "Теңдеу — екі өрнектің теңдігі. Шешім — айнымалының осы теңдікті ақиқат ететін мәні.", "екі жаққа бір амал → x-ті оқшаулау → бастапқы теңдікке қою → ақиқат па?", "`3x+5=26`; екі жақтан 5 азайтамыз: `3x=21`; екі жағын 3-ке бөлеміз: `x=7`; тексеру `26=26`.", "Тек сол жақтан 5 азайтып `3x=26` қалдыру теңдікті бұзады. Бірдей амал екі жаққа да жасалуы тиіс.", "`5x−8=27` және `4(x+2)=32` теңдеулерін шешіп, әр жауапты бастапқы жолға қойыңыз.", "Екі теңдеу бір мезетте орындалса, олардың ортақ шешімі жүйені береді."),
        "en": E("Equations: keep both sides balanced", "We isolate an unknown by applying the same operation to both sides and check the solution in the original equation.", "Equality between expressions becomes a task of finding an unknown value.", "Balance model for the equation 3x + 5 = 26", "A balance remains level when the same change is made to both pans. The two sides of an equation require the same operation.", "An equation states that two expressions are equal. A solution is a variable value that makes the statement true.", "same operation on both sides → isolate x → substitute into original → true?", "`3x+5=26`; subtract 5 from both sides: `3x=21`; divide both sides by 3: `x=7`; check gives `26=26`.", "Subtracting 5 only on the left and leaving `3x=26` breaks equality. The same change must happen on both sides.", "Solve `5x−8=27` and `4(x+2)=32`; substitute every answer into its original equation.", "When two equations must hold together, their common solution forms a system."),
    },
    "22-coordinates": {
        "kz": E("Координаталар: сандар жазықтықтағы мекенжайға айналады", "Нүктені реттелген жұппен белгілеп, осьтердің бағытын оқимыз және бір түзудегі нүктелер арақашықтығын табамыз.", "Бір сан осіне екінші перпендикуляр ось қосып, жазықтық моделін құрамыз.", "A(−3; 2) және B(4; 2) нүктелері, арақашықтығы 7", "Қаладағы мекенжайда алдымен көше, кейін үй нөмірі айтылады. Координатада да рет маңызды: алдымен x, кейін y.", "`(x;y)` нүктесінің x мәні көлденең, y мәні тік қозғалысты көрсетеді. Бірдей y бар екі нүктенің көлденең қашықтығы x айырмасының модулі.", "бастау нүктесі → x бойымен жүру → y бойымен жүру → нүкте → арақашықтық", "`A(−3;2)`, `B(4;2)`; бір деңгейде жатқандықтан қашықтық `|4−(−3)|=7`.", "`(−3;2)` орнына `(2;−3)` белгілеу координаталардың ретін ауыстырады және басқа нүкте береді.", "`P(−4;−1)`, `Q(3;−1)`, `R(3;5)` нүктелерін салыңыз; PQ, QR және тікбұрыш периметрін табыңыз.", "Координаталық жазықтық функция графиктері мен геометриялық модельдердің негізгі тілі болады."),
        "en": E("Coordinates: numbers become an address in the plane", "We locate a point with an ordered pair, read axis directions, and find distance between aligned points.", "A second perpendicular number line turns the line into a plane.", "Points A(−3, 2) and B(4, 2) separated by 7 units", "An address states its parts in an agreed order. Coordinates do too: horizontal x first, vertical y second.", "For `(x,y)`, x controls horizontal movement and y controls vertical movement. Aligned points with equal y are separated by the absolute difference of x-values.", "origin → move along x → move along y → point → distance", "`A(−3,2)` and `B(4,2)` share a height, so their distance is `|4−(−3)|=7`.", "Plotting `(2,−3)` instead of `(−3,2)` reverses the coordinate order and produces a different point.", "Plot `P(−4,−1)`, `Q(3,−1)`, and `R(3,5)`; find PQ, QR, and the rectangle’s perimeter.", "The coordinate plane becomes the main language of function graphs and geometric models."),
    },
    "23-inequalities": {
        "kz": E("Теңсіздіктер: бір жауап емес, мәндер жиыны", "Теңсіздікті сан осіндегі аймақ ретінде оқып, шекараны табамыз және теріс санға көбейткенде белгінің неге ауысатынын түсіндіреміз.", "Теңдеу бір нүкте берсе, теңсіздік жарамды мәндердің тұтас аймағын береді.", "3x + 2 ≤ 14 теңсіздігінің x ≤ 4 шешімі", "Лифт ең көбі 600 кг көтерсе, бір ғана дұрыс салмақ емес, 0-ден 600-ге дейінгі барлық салмақ жарайды.", "`<` және `>` шекараны қоспайды; `≤` және `≥` қосады. Теріс санға көбейту сан осінің бағытын кері айналдыратындықтан белгі ауысады.", "шекараны табу → белгі қосыла ма? → сан осінде бояу → бір жарамды және бір жарамсыз мәнмен тексеру", "`3x+2≤14`; `3x≤12`; `x≤4`. `x=4` жарайды, `x=5` жарамайды.", "`−2x<6` теңсіздігін `x<−3` деп бөлу қате: −2-ге бөлгенде бағыт ауысып, `x>−3` болады.", "`5−2x≥−7` теңсіздігін шешіп, сан осінде көрсетіңіз және шекараның кіретінін екі мәнмен тексеріңіз.", "Предалгебра бақылауы айнымалы, өрнек, теңдеу, координата және теңсіздікті біріктіреді."),
        "en": E("Inequalities: a set of values rather than one answer", "We read an inequality as a region on a number line, find its boundary, and explain why the sign reverses when multiplying by a negative.", "An equation may identify a point; an inequality describes an entire region of valid values.", "The solution x ≤ 4 for 3x + 2 ≤ 14", "If an elevator carries at most 600 kg, many loads from 0 to 600 are valid rather than one exact weight.", "`<` and `>` exclude the boundary; `≤` and `≥` include it. Multiplication by a negative reverses number-line order, so the sign reverses.", "find boundary → included? → shade line → test one valid and one invalid value", "`3x+2≤14`; `3x≤12`; `x≤4`. The boundary 4 works, while 5 does not.", "Dividing `−2x<6` and keeping `x<−3` is wrong: division by −2 reverses the order, giving `x>−3`.", "Solve `5−2x≥−7`, show it on a number line, and test the boundary with two values.", "The prealgebra checkpoint combines variables, expressions, equations, coordinates, and inequalities."),
    },
    "24-prealgebra-mastery": {
        "kz": E("Бақылау нүктесі: предалгебрадан алгебраға дайындық", "Он тапсырма әріптің мағынасын, өрнек түрлендіруді, теңдеу мен теңсіздікті, координатаны және білімді көшіруді тексереді.", "Бұл бақылау символдарды механикалық емес, шамалардың тілі ретінде қолдануға дайындықты көрсетеді.", "Предалгебраның бес дағдысы және екі әрекеттің нәтижесі", "Шет тіліндегі сөздерді жаттау жеткіліксіз: олармен жаңа сөйлем құрау керек. Алгебрада да таңбаларды жаңа жағдайды модельдеу үшін қолданамыз.", "8/10 және әр шешімнің түсіндірмесі келесі блокқа өтуге жеткілікті. Қате жеке ережені емес, ең ерте әлсіз ұғымды көрсетеді.", "шама → өрнек → теңдік/теңсіздік → графикалық көрініс → тексеру → көшіру", "Жол бағасын айнымалымен жазу, өрнекті ықшамдау және координатамен нәтиже көрсету бір модельдің үш көрінісі болуы мүмкін.", "Әріпті тек «белгісіз сан» деп айту жеткіліксіз: ол белгілі бір мән, бірлік және шекарасы бар шама болуы мүмкін.", "Он тапсырманы орындап, 8/10-ға жетпеген ұғымды қайта құрыңыз. Жеті күннен кейін өзгертілген тапсырмамен қайталаңыз.", "Келесі бөлім функцияны екі шаманың өзгеру ережесі ретінде зерттейді."),
        "en": E("Checkpoint: readiness to move from prealgebra to algebra", "Ten tasks test the meaning of letters, expression transformations, equations, inequalities, coordinates, and transfer.", "This checkpoint shows readiness to use symbols as a language of quantities rather than as mechanical marks.", "Five prealgebra skills and the results of two attempts", "Memorizing words in a new language is insufficient; you must build new sentences. Algebra likewise uses symbols to model new situations.", "A score of 8/10 with explained solutions supports moving on. An error points to the earliest weak idea, not merely a rule to memorize.", "quantity → expression → equality/inequality → graphical view → check → transfer", "A travel cost may be written with a variable, simplified as an expression, and displayed with coordinates: three views of one model.", "Calling every letter only an “unknown number” is incomplete: it may represent a quantity with meaning, units, and a valid range.", "Complete ten tasks, rebuild any idea below 8/10, and repeat a changed set after seven days.", "The next section studies a function as a rule connecting two changing quantities."),
    },
    "25-linear-functions": {
        "kz": E("Сызықтық функция: тұрақты қадамнан түзу сызыққа", "Кесте, формула, график және сөздік жағдайды бір тәуелділіктің төрт көрінісі ретінде байланыстырамыз.", "Айнымалылар арасындағы ереже енді функцияға және оның графигіне айналады.", "y = 2x + 1 түзуі және (−1;−1), (0;1), (2;5) нүктелері", "Такси бағасы немесе су деңгейі әр бірдей қадамда бірдей мөлшерге өзгерсе, кестедегі тұрақты айырма графикте түзу береді.", "`y=kx+b` формуласында `k` — x бір бірлікке өзгергендегі y өзгерісі, `b` — x=0 кезіндегі бастапқы мән.", "бастапқы мән b → тұрақты қадам k → кесте → нүктелер → түзу → жағдаймен тексеру", "`y=2x+1`: x=−1,0,2 үшін y=−1,1,5; үш нүкте бір түзудің бойында.", "`b=1` графиктің x осімен қиылысуы деу қате: b — y осімен қиылысу, себебі x=0.", "`y=−3x+4` үшін бес мәндік кесте құрып, график салыңыз және k мен b мағынасын айтыңыз.", "Екі сызықтық шарт бір уақытта орындалғанда олардың қиылысуы теңдеулер жүйесінің шешімі болады."),
        "en": E("Linear functions: from a constant step to a straight line", "We connect a table, formula, graph, and verbal situation as four views of one relationship.", "A rule between variables now becomes a function and its graph.", "The line y = 2x + 1 through (−1,−1), (0,1), and (2,5)", "When a fare or water level changes by the same amount for every equal input step, a constant table difference produces a straight graph.", "In `y=kx+b`, `k` is the change in y for one unit of x, and `b` is the starting value when x=0.", "start b → constant step k → table → points → line → context check", "For `y=2x+1`, x=−1,0,2 gives y=−1,1,5; all three points lie on one line.", "Calling `b=1` the x-intercept is wrong: b is the y-intercept because it is the value at x=0.", "Build a five-value table for `y=−3x+4`, draw its graph, and explain k and b.", "When two linear conditions hold at once, their intersection solves a system of equations."),
    },
    "26-systems": {
        "kz": E("Теңдеулер жүйесі: екі шарттың ортақ шешімі", "Екі теңдеуді бір мезетте қанағаттандыратын жұпты график, алмастыру және жою әдістерімен табамыз.", "Бір функциядан екі байланысты салыстыруға өтеміз.", "x + y = 10 және 2x + y = 16 жүйесінің (6;4) шешімі", "Екі түрлі билеттен барлығы 10 дана, бағалық бірлікпен жалпы құны 16 болса, екі шарт бір жауапты бірге анықтайды.", "Жүйенің шешімі — әр теңдеуді ақиқат ететін реттелген жұп. Графикте ол екі қисықтың ортақ нүктесі.", "екі шарт → ортақ айнымалылар → бір айнымалыны жою → жұп → екі теңдеуде тексеру", "Екіншіден біріншіні азайтсақ `x=6`; сонда `y=4`. Тексеру: `6+4=10`, `12+4=16`.", "Тек бірінші теңдеуді қанағаттандыратын `(5;5)` жұбын шешім деу қате: ол екінші теңдеуде 15 береді.", "`x+y=14`, `3x+y=26` жүйесін жою және график әдісімен шешіп, нәтижені екі теңдеуде тексеріңіз.", "Дәрежелер қайталанатын көбейтуді ықшамдап, түбір оған кері сұрақ қояды."),
        "en": E("Systems of equations: one solution shared by two conditions", "We find an ordered pair satisfying two equations at once by graphing, substitution, and elimination.", "We move from one function to comparing two relationships.", "The solution (6,4) of x + y = 10 and 2x + y = 16", "If two ticket types total 10 and their weighted total is 16, the two conditions determine the counts together.", "A system solution is an ordered pair that makes every equation true. On a graph it is a common intersection point.", "two conditions → shared variables → eliminate one variable → pair → check both equations", "Subtracting the first equation from the second gives `x=6`, then `y=4`; both original equations check.", "The pair `(5,5)` is not a solution merely because it satisfies the first equation; it gives 15 in the second.", "Solve `x+y=14`, `3x+y=26` by elimination and graphing, then check both equations.", "Powers compress repeated multiplication, and roots ask the inverse question."),
    },
    "27-powers-roots": {
        "kz": E("Дәреже мен түбір: қайталанатын көбейту және кері сұрақ", "Дәрежені негіз бен көрсеткіш арқылы оқып, бір негізді дәрежелер заңдарын мағынадан шығарамыз және түбірмен кері тексереміз.", "Алгебралық жазуды қайталанатын көбейтуге кеңейтеміз.", "2³ × 2⁴ = 2⁷ = 128 және √144 = 12 байланысы", "Қағазды екіге қайта-қайта бүктегенде қабат саны 2, 4, 8 болып көбейеді: қайталану дәреже арқылы қысқа жазылады.", "`aⁿ` — a санының n рет көбейтіндісі. `√b` — квадраты b болатын теріс емес сан.", "негіз → көбейткіштер санын санау → көрсеткіштер заңын қолдану → түбірмен кері тексеру", "`2³×2⁴` жеті екі көбейткіш береді, сондықтан `2⁷=128`; `√144=12`, өйткені `12²=144`.", "`2³+2⁴=2⁷` деу қате: көрсеткіштер тек бір негізді дәрежелер көбейтілгенде қосылады.", "`3²×3⁴`, `5⁷÷5³`, `√225` есептерін көбейткіштерге ашып түсіндіріп, кері амалмен тексеріңіз.", "Дәрежелі мүшелер көпмүшелерді құрып, олардың амалдары үлестірімділікке сүйенеді."),
        "en": E("Powers and roots: repeated multiplication and its inverse question", "We read powers through base and exponent, derive same-base laws from meaning, and use roots as an inverse check.", "Algebraic notation now compresses repeated multiplication.", "The relationship 2³ × 2⁴ = 2⁷ = 128 and √144 = 12", "Repeatedly folding paper doubles its layers: 2, 4, 8. Powers record such repeated multiplication compactly.", "`aⁿ` is a product of n factors equal to a. `√b` is the nonnegative number whose square equals b.", "base → count factors → apply exponent law → check with a root or power", "`2³×2⁴` contains seven factors of 2, so `2⁷=128`; `√144=12` because `12²=144`.", "Writing `2³+2⁴=2⁷` is wrong: exponents add when same-base powers are multiplied, not added.", "Explain `3²×3⁴`, `5⁷÷5³`, and `√225` by expanding factors and checking inversely.", "Terms with powers form polynomials, whose operations rely on distribution."),
    },
    "28-polynomials": {
        "kz": E("Көпмүшелер: мүшелерді құрастыру, көбейту және тексеру", "Көпмүшенің дәрежесі мен коэффициентін оқып, үлестірімділікпен көбейтеміз және нәтижені мән қою арқылы тексереміз.", "Дәрежелі мүшелер енді бір өрнекке бірігеді.", "(2x + 3)(x − 4) көбейтіндісінің 2x² − 5x − 12 түріне ашылуы", "Тіктөртбұрыш қабырғалары қосындылармен берілсе, оның ауданы төрт кіші тіктөртбұрыш аудандарының қосындысы болады.", "Көпмүше — теріс емес бүтін дәрежелі мүшелердің қосындысы. Көбейткенде бірінші жақшаның әр мүшесі екінші жақшаның әр мүшесіне көбейеді.", "әр мүше × әр мүше → таңбаларды сақтау → ұқсас мүшелерді біріктіру → мәнмен тексеру", "`(2x+3)(x−4)=2x²−8x+3x−12=2x²−5x−12`.", "Ортаңғы мүшені `−8x−3x` деу қате: `3×x` оң `3x`, сондықтан қосынды `−5x`.", "`(3x−2)(x+5)` көбейтіндісін ашып, `x=2` кезінде екі түрдің мәнін салыстырыңыз.", "Квадраттық функция екінші дәрежелі көпмүшені графиктегі параболаға айналдырады."),
        "en": E("Polynomials: build, multiply, and check terms", "We read degree and coefficient, multiply through distribution, and verify the result by substitution.", "Powered terms now combine into one expression.", "Expanding (2x + 3)(x − 4) into 2x² − 5x − 12", "If a rectangle’s side lengths are sums, its area is the sum of four smaller rectangle areas.", "A polynomial is a sum of terms with nonnegative integer powers. In multiplication, every term in one factor multiplies every term in the other.", "every term × every term → preserve signs → combine like terms → substitute to check", "`(2x+3)(x−4)=2x²−8x+3x−12=2x²−5x−12`.", "Making the middle terms `−8x−3x` is wrong: `3×x` is positive `3x`, so they combine to `−5x`.", "Expand `(3x−2)(x+5)` and compare both forms at `x=2`.", "A quadratic function turns a degree-two polynomial into a parabola on a graph."),
    },
    "29-quadratics": {
        "kz": E("Квадраттық функция: параболадағы түбір, төбе және пішін", "Формула, көбейткіштер және толық квадрат түрлерін графикпен байланыстырып, әр жазудан бөлек қасиетті оқимыз.", "Сызықтық функциядан иілген, бірақ дәл сипатталатын квадраттық тәуелділікке өтеміз.", "y = x² − 4x + 3 параболасы, түбірлері 1 және 3, төбесі (2;−1)", "Жоғары лақтырылған дененің биіктігі әуелі өсіп, кейін кемиді. Мұндай өзгерісті түзу емес, парабола сипаттай алады.", "`y=ax²+bx+c` графигі — парабола. Түбірлерде y=0; төбе ең кіші не ең үлкен мәнді береді; a таңбасы ашылу бағытын анықтайды.", "жалпы түр → көбейткіштерден түбірлер → толық квадраттан төбе → графикпен тексеру", "`x²−4x+3=(x−1)(x−3)=(x−2)²−1`; түбірлері 1,3, төбесі `(2;−1)`.", "Төбені `(−2;−1)` деу қате: `(x−2)²` ең кіші мәнін x=2 кезінде алады.", "`y=x²−6x+5` функциясын көбейткіштерге жіктеп, толық квадратқа келтіріп, түбірі мен төбесін табыңыз.", "Көрсеткіштік функцияда тұрақты қосындының орнына тұрақты көбейткіш өзгерісті басқарады."),
        "en": E("Quadratic functions: roots, vertex, and the shape of a parabola", "We connect standard, factored, and vertex forms with a graph and read a different property from each form.", "We move from straight-line change to a curved but precisely described relationship.", "The parabola y = x² − 4x + 3 with roots 1 and 3 and vertex (2,−1)", "The height of a thrown object first rises and then falls. A parabola can model this change where a line cannot.", "The graph of `y=ax²+bx+c` is a parabola. Roots occur at y=0, the vertex gives a minimum or maximum, and the sign of a sets the opening direction.", "standard form → roots from factors → vertex from completed square → graph check", "`x²−4x+3=(x−1)(x−3)=(x−2)²−1`; roots are 1 and 3, vertex is `(2,−1)`.", "Calling the vertex `(−2,−1)` is wrong: `(x−2)²` reaches its minimum when x=2.", "Factor and complete the square for `y=x²−6x+5`; find its roots and vertex.", "In an exponential function, a constant factor replaces a constant additive step."),
    },
    "30-exponential-log": {
        "kz": E("Көрсеткіштік өсу және логарифм: бірдей уақыттағы бірдей еселік", "Сызықтық қосылуды көрсеткіштік көбейтуден ажыратып, логарифмді қажетті дәреже көрсеткіші деген кері сұрақ ретінде оқимыз.", "Функциялар енді тұрақты айырмадан тұрақты еселікке өтеді.", "N = 500 × 2ᵗ екі еселену моделі және log₂8 = 3", "Бактерия саны әр сағатта екі есе өссе, қосылатын сан тұрақты емес, ал көбейту коэффициенті тұрақты.", "`N=N₀aᵗ` моделінде N₀ — бастапқы мән, a — бір қадамдағы коэффициент. `logₐb` — a-ны b ету үшін керек дәреже.", "бастапқы мән → уақыт қадамы → тұрақты коэффициент → дәреже → логарифммен уақытты табу", "`N=500×2ᵗ`; t=3 болса `N=4000`. Кері сұрақ: `2³=8`, сондықтан `log₂8=3`.", "Үш екі еселенуден кейін `500+3×2=506` деу қате: әр қадам алдыңғы бүкіл мәнді екіге көбейтеді.", "1000 саны әр 4 сағатта 1,5 есе өседі. 12 сағаттан кейінгі мәнді және 3375-ке жету уақытын табыңыз.", "Тізбектер қадам бойынша алынған мәндерді ретпен көрсетіп, сызықтық пен көрсеткіштік өсуді біріктіреді."),
        "en": E("Exponential growth and logarithms: the same factor over equal time", "We distinguish linear addition from exponential multiplication and read a logarithm as the inverse question asking for an exponent.", "Functions now move from a constant difference to a constant factor.", "The doubling model N = 500 × 2ᵗ and log₂8 = 3", "If bacteria double each hour, the added amount is not constant, but the multiplication factor is.", "In `N=N₀aᵗ`, N₀ is the initial value and a is the factor per step. `logₐb` asks for the power of a that equals b.", "initial value → time step → constant factor → power → logarithm finds time", "`N=500×2ᵗ`; at t=3, `N=4000`. In reverse, `2³=8`, so `log₂8=3`.", "After three doublings, writing `500+3×2=506` is wrong: every step doubles the entire previous value.", "A quantity starts at 1000 and grows by a factor of 1.5 every 4 hours. Find its value after 12 hours and when it reaches 3375.", "Sequences list step-by-step values and connect linear and exponential patterns."),
    },
    "31-sequences": {
        "kz": E("Тізбектер: заңдылықты сөзден n-ші мүшеге дейін жеткізу", "Арифметикалық және геометриялық тізбекті айырма мен еселік арқылы ажыратып, рекурренттік және жалпы формуланы құрамыз.", "Функцияны бүтін қадамдарда қарап, реттелген мәндер тізбегіне айналдырамыз.", "5, 8, 11, 14 арифметикалық және 2, 6, 18, 54 геометриялық тізбектері", "Баспалдақ әр қадамда 3 см өссе — тұрақты айырма; әр қабат алдыңғысынан 3 есе болса — тұрақты еселік.", "Арифметикалық тізбекте `aₙ=a₁+(n−1)d`; геометриялықта `aₙ=a₁qⁿ⁻¹`. `n−1` — бірінші мүшеден n-шіге дейінгі ауысу саны.", "мүшелерді салыстыру → айырма ма, еселік пе? → рекурренттік ереже → n-ші мүше → тексеру", "`5,8,11,14`: d=3, `aₙ=5+3(n−1)`. `2,6,18,54`: q=3, `aₙ=2×3ⁿ⁻¹`.", "n-ші мүшеде n рет қадам бар деп `aₙ=a₁+nd` жазу қате: бірінші мүшеге жеткенде әлі бір де бір ауысу жасалмайды.", "`12,17,22,...` және `81,27,9,...` тізбектерінің түрін, рекурренттік және жалпы формуласын тауып, 10-мүшесін есептеңіз.", "Алгебра бақылауы функция, жүйе, дәреже, көпмүше, парабола, өсу және тізбекті бір модельдеу тізбегіне жинайды."),
        "en": E("Sequences: from a verbal pattern to the nth term", "We distinguish arithmetic and geometric sequences by difference and factor, then build recursive and explicit rules.", "Viewing a function only at integer steps creates an ordered sequence of values.", "The arithmetic sequence 5, 8, 11, 14 and geometric sequence 2, 6, 18, 54", "A staircase rising 3 cm each step has a constant difference; layers tripling each time have a constant factor.", "For arithmetic sequences, `aₙ=a₁+(n−1)d`; for geometric sequences, `aₙ=a₁qⁿ⁻¹`. The `n−1` counts transitions from the first term.", "compare terms → difference or factor? → recursive rule → nth term → check", "`5,8,11,14` has d=3 and `aₙ=5+3(n−1)`. `2,6,18,54` has q=3 and `aₙ=2×3ⁿ⁻¹`.", "Writing `aₙ=a₁+nd` counts n steps to the nth term, but reaching the first term requires zero transitions.", "For `12,17,22,...` and `81,27,9,...`, identify the type, write recursive and explicit rules, and find term 10.", "The algebra checkpoint joins functions, systems, powers, polynomials, parabolas, growth, and sequences into one modeling chain."),
    },
    "32-algebra-mastery": {
        "kz": E("Бақылау нүктесі: алгебралық модельді құру және қорғау", "Он жаңа тапсырма функция, жүйе, дәреже, көпмүше, квадраттық және көрсеткіштік модель мен тізбекті түсіндіру, тексеру және көшіру арқылы бағалайды.", "Бұл блоктың соңғы бақылауы жеке амалдарды емес, шынайы жағдайдан модель құрып, оның шекарасын қорғауды тексереді.", "Алгебраның жеті дағдысы және уақыт аралығындағы екі нәтиже", "Инженерлік сызба тек әдемі көріну үшін емес: ол өлшемге, жүктемеге және тексеруге шыдауы керек. Математикалық модель де сондай.", "Меңгеру үшін формуланы таңдау, айнымалыларды анықтау, есептеу, басқа көрініспен тексеру және модель қолданылмайтын шекараны айту қажет.", "жағдай → шамалар → модель → есептеу → график/кері тексеру → шекара → түсіндіру", "Сызықтық баға моделі, екі шарт жүйесі және көрсеткіштік өсу әртүрлі формула қолданады; таңдауды деректегі өзгеріс түрі анықтайды.", "Кез келген өсуге түзу сызық қолдану қате. Тұрақты айырма сызықтық, тұрақты еселік көрсеткіштік модельге жетелейді.", "Он тапсырманы толық шешіп, кемінде 8/10 және түсіндірілген тексеруге жетіңіз. Қатені түзеп, жеті күннен кейін өзгерген нұсқаны қайталаңыз.", "Келесі курстық блоктар осы алгебралық тілді геометрияға, ықтималдыққа, анализге және нақты деректерді модельдеуге қолданады."),
        "en": E("Checkpoint: build and defend an algebraic model", "Ten new tasks assess functions, systems, powers, polynomials, quadratic and exponential models, and sequences through explanation, checking, and transfer.", "This final checkpoint tests building a model from a real situation and defending its limits, rather than isolated operations.", "Seven algebra skills and results from two spaced attempts", "An engineering drawing must survive measurements, loads, and checks. A mathematical model likewise needs evidence beyond an attractive formula.", "Mastery requires choosing a formula, defining variables, calculating, checking with another representation, and stating where the model no longer applies.", "situation → quantities → model → calculate → graph/inverse check → boundary → explanation", "A linear fare, a system of two conditions, and exponential growth need different formulas; the type of change in the data determines the choice.", "Using a straight line for every growth process is wrong. Constant difference suggests linear change; constant factor suggests exponential change.", "Solve all ten tasks, reach at least 8/10 with explained checks, repair errors, and repeat a changed version after seven days.", "Later blocks apply this algebraic language to geometry, probability, calculus, and modeling with real data."),
    },
    "33-geometry-language": {
        "kz": E("Геометрия тілі: нүкте, түзу, бұрыш және дәлелдеу", "Анықтаманы суреттен ажыратып, бұрыштарды өлшейміз және дәлелдеуді сыртқы көрініске емес, себептер тізбегіне құрамыз.", "Алгебрадан пішін мен кеңістік тіліне өтеміз.", "A нүктесі, l түзуі және 125° пен 55° сыбайлас бұрыштар", "Картада қала нүктемен, жол сызықпен, бағыт сәулемен белгіленеді. Таңба объектінің өзі емес: математикалық нүктенің тек орны бар.", "Түзу екі бағытта шексіз, сәуленің басы, кесіндінің екі ұшы бар. Бұрыш ортақ төбелі екі сәуледен құралады. Дәлелдің әр қадамы анықтамаға, шартқа не белгілі қасиетке сүйенеді.", "объект → белгілеу → берілгені → дәлел → себеп → қорытынды", "Жазыңқы бұрыш 180°. Егер бір бөлігі 125° болса, екіншісі `180°−125°=55°`.", "«Суретте бірдей көрінеді, демек бұрыштар тең» деу қате: сызба дәл болмауы мүмкін, белгі не дәлел керек.", "Екі қиылысқан түзу салыңыз. Бір бұрыш 38° болса, қалған үшеуін тауып, сыбайлас және вертикаль бұрыштармен негіздеңіз.", "Үшбұрыш анықтамалар мен теңдік белгілерін алғашқы жүйелі дәлелдеуге біріктіреді."),
        "en": E("The language of geometry: points, lines, angles, and proof", "We separate a definition from a drawing, measure angles, and build a first proof as a chain of reasons rather than visual appearance.", "We move from algebra into the language of shape and space.", "Point A, line l, and adjacent angles of 125° and 55°", "A map marks a city with a point, a road with a line, and a direction with a ray. The mark is not the object itself: a mathematical point has position only.", "A line extends both ways, a ray has one endpoint, and a segment has two. An angle consists of two rays with a common endpoint. Every proof step needs a definition, given fact, or established property.", "object → notation → given → claim → reason → conclusion", "A straight angle is 180°. If one adjacent part is 125°, the other is `180°−125°=55°`.", "“The angles look equal” is not proof: a diagram may be inaccurate, so a mark, measurement, or logical reason is required.", "Draw two intersecting lines. If one angle is 38°, find the other three and justify them with adjacent and vertical angle properties.", "Triangles combine definitions and congruence tests into the first systematic proofs."),
    },
    "34-triangles-congruence": {
        "kz": E("Үшбұрыштар және теңдік: үш дерек қашан жеткілікті", "Үшбұрыштарды жіктеп, бұрыштар қосындысын қолданамыз және суретті салыстырудың орнына нақты белгілермен теңдігін дәлелдейміз.", "Нүкте, түзу және бұрыштан алғашқы қатаң фигураға өтеміз.", "Қабырғалары 5, 7, 8 болатын екі тең үшбұрыш", "Үшбұрышты керме пішінін қабырға ұзындығын өзгертпей бұрмалай алмайды. Сондықтан құрылыс қаңқаларында үшбұрыштар қолданылады.", "Тең үшбұрыштар беттестіргенде сәйкес келеді. Үш жеткілікті белгі: SSS, SAS және ASA. Үш бұрыш пішінді береді, бірақ өлшемді бермейді.", "төбелер сәйкестігі → жеткілікті белгі → үшбұрыштар тең → сәйкес бөліктер тең", "Екі үшбұрыштың сәйкес қабырғалары 5, 7, 8 болса, SSS бойынша олар тең; сәйкес бұрыштары да тең.", "SSA-ны жалпы белгі деу қате: екі қабырға мен олардың арасындағы емес бұрыш кейде екі түрлі үшбұрыш береді.", "Теңбүйірлі үшбұрышта бүйір қабырғалары тең, табан бұрышы 52°. Қалған бұрыштарды тауып, табан бұрыштарының теңдігін дәлелдеңіз.", "Өлшем өзгеріп, пішін сақталса, теңдік ұқсастыққа және масштаб коэффициентіне өтеді."),
        "en": E("Triangles and congruence: when three facts are enough", "We classify triangles, use the angle sum, and prove congruence with exact tests instead of comparing drawings.", "Points, lines, and angles now form the first rigid shape.", "Two congruent triangles with side lengths 5, 7, and 8", "A triangular brace cannot change shape without changing a side length, which is why frames and bridges use triangles for rigidity.", "Congruent triangles coincide when superimposed. SSS, SAS, and ASA are sufficient tests. Three angles determine shape but not size.", "match vertices → sufficient test → congruent triangles → corresponding parts equal", "If corresponding sides of two triangles are 5, 7, and 8, SSS proves congruence and all matching angles are equal.", "Treating SSA as a general test is wrong: two sides and a non-included angle can produce two different triangles.", "An isosceles triangle has a base angle of 52°. Find the other angles and prove the base angles equal.", "When size changes but shape remains, congruence gives way to similarity and scale."),
    },
    "35-similarity-scale": {
        "kz": E("Ұқсастық және масштаб: өлшемі бөлек, пішіні бір", "Тең бұрыштарды пропорционал қабырғалармен байланыстырып, ұқсастық коэффициентін және ұзындық, аудан, көлем өзгерісін табамыз.", "Тең фигуралардан бір пішінді әртүрлі өлшемде қарауға өтеміз.", "3–4–5 және 6–8–10 ұқсас үшбұрыштары, коэффициенті 2", "Экрандағы сурет пен плакаттағы нұсқа ені мен биіктігі бір коэффициентпен өзгерсе, бір пішінді сақтайды.", "Ұқсас фигуралардың сәйкес бұрыштары тең, қабырғалары пропорционал. k кезінде ұзындық k, аудан k², көлем k³ есе өзгереді.", "сәйкес төбелер → тең бұрыштар → бір k → ұзындық k → аудан k² → көлем k³", "`3,4,5` және `6,8,10`: барлық қатынас 2; периметр 2, аудан 4 есе артады.", "Сәйкес емес қабырғаларды салыстыру қате. Алдымен төбелер ретін орнатып, барлық жұп үшін бір коэффициентті тексеріңіз.", "1:50 модельдегі есік 4,2 см. Нақты биіктігін және ұқсас бөлшектер ауданының қатынасын табыңыз.", "Аудан мен көлем формулалары бірлік квадраттар мен кубтарды неге санайтынын ашады."),
        "en": E("Similarity and scale: one shape at different sizes", "We connect equal angles to proportional sides, find a scale factor, and track how length, area, and volume change.", "We move from identical figures to the same shape at different sizes.", "Similar 3–4–5 and 6–8–10 triangles with scale factor 2", "A screen image and a poster keep one shape when width and height are multiplied by the same factor.", "Similar figures have equal corresponding angles and proportional sides. Under factor k, lengths scale by k, areas by k², and volumes by k³.", "match vertices → equal angles → one k → lengths k → areas k² → volumes k³", "For `3,4,5` and `6,8,10`, every ratio is 2; perimeter doubles and area quadruples.", "Comparing noncorresponding sides is wrong. Establish the vertex order and verify one factor across every pair.", "A 1:50 model door is 4.2 cm high. Find its real height and the area ratio of similar panels.", "Area and volume explain why formulas count unit squares and cubes."),
    },
    "36-area-volume": {
        "kz": E("Аудан және көлем: бірлік квадраттар мен кубтар арқылы өлшеу", "Формулаларды кесіп қайта құрастырудан шығарып, өлшем бірліктерін келтіреміз және бет ауданын сыйымдылықтан ажыратамыз.", "Ұқсастықтағы k² және k³ өзгерістерінің себебін зерттейміз.", "Параллелограмды тіктөртбұрышқа айналдыру және призманы кубтармен толтыру", "Еден квадрат тақталармен жабылады, қорап кубтармен толтырылады. Шекара ұзындығы, тақта саны және куб саны бөлек сұрақтар.", "Параллелограмм `S=bh`, үшбұрыш оның жартысы, призма `V=Bh`. Биіктік негізге перпендикуляр болуы керек.", "өлшем → бірліктер → кесу/толтыру → формула → бағалау → жауап бірлігі", "Негізі 8 см, биіктігі 5 см параллелограмм ауданы `40 см²`; табаны 40 см², биіктігі 3 см призма көлемі `120 см³`.", "`8 см × 5 см = 40 см` деу қате: екі ұзындық көбейгенде нәтиже `40 см²`.", "10×6 м тіктөртбұрыш пен негізі 6 м, биіктігі 4 м үшбұрыштан тұратын алаңның ауданын және 0,08 м қабат көлемін табыңыз.", "Тікбұрышты үшбұрыш қабырғаларындағы квадраттар Пифагор теоремасына әкеледі."),
        "en": E("Area and volume: measuring with unit squares and cubes", "We derive formulas by cutting and rearranging, align units, and distinguish surface area from capacity.", "We explain why similarity produced k² and k³ changes.", "A parallelogram rearranged into a rectangle and a prism filled with cubes", "A floor is covered with square tiles and a box is filled with cubes. Boundary length, tile count, and cube count answer different questions.", "A parallelogram has `A=bh`, a triangle is half of it, and a prism has `V=Bh`. Height must be perpendicular to the base.", "dimension → units → cut/fill → formula → estimate → answer unit", "A parallelogram with base 8 cm and height 5 cm has `A=40 cm²`; a prism with base area 40 cm² and height 3 cm has `V=120 cm³`.", "Writing `8 cm × 5 cm = 40 cm` is wrong: multiplying two lengths produces `40 cm²`.", "Find the area of a 10×6 m rectangle plus a triangle of base 6 m and height 4 m, then the volume of a 0.08 m layer.", "Squares on the sides of a right triangle lead to the Pythagorean theorem."),
    },
    "37-pythagoras": {
        "kz": E("Пифагор теоремасы: квадрат аудандарынан қашықтық табу", "Катеттер мен гипотенуза байланысын аудан арқылы дәлелдеп, белгісіз қабырғаны табамыз және тік бұрыш шартын тексереміз.", "Аудан формуласын қашықтық туралы теоремаға қолданамыз.", "3–4–5 тікбұрышты үшбұрышы және аудандары 9, 16, 25 квадраттар", "Шығысқа 3, солтүстікке 4 көше жүрсек, тура қашықтық 7 емес; диагональ қысқа жолды береді.", "Тікбұрышты үшбұрышта `a²+b²=c²`, мұнда c — тік бұрышқа қарсы гипотенуза. Кері теорема тік бұрышты қабырғалардан тексереді.", "тік бұрыш → гипотенуза → катеттер квадраттары → теңдеу → оң түбір → бағалау", "`c²=3²+4²=25`, сондықтан `c=5`; 5 әр катеттен үлкен және олардың қосындысынан кіші.", "10-ды катет деп алып `c²=6²+10²` жазу қате: 10 ең үлкен қабырға ретінде гипотенуза болуы мүмкін.", "Ұзындығы 6,5 м саты қабырғадан 2,5 м жерде тұр. Биіктікті тауып, 5–12–13 үштігімен тексеріңіз.", "Шеңбер центрден бірдей қашықтықтағы нүктелерді жинап, π тұрақтысын енгізеді."),
        "en": E("The Pythagorean theorem: distance from square areas", "We prove the relation between legs and hypotenuse through area, find an unknown side, and check the right-angle condition.", "Area formulas now support a theorem about distance.", "A 3–4–5 right triangle with square areas 9, 16, and 25", "Walking 3 blocks east and 4 north does not make a straight distance of 7; the diagonal joins the endpoints directly.", "In a right triangle, `a²+b²=c²`, where c is opposite the right angle. The converse checks a right angle from side lengths.", "right angle → hypotenuse → squares of legs → equation → positive root → estimate", "`c²=3²+4²=25`, so `c=5`; it exceeds either leg and is below their sum.", "Using 10 as a leg in `c²=6²+10²` is wrong when 10 is already the longest side and may be the hypotenuse.", "A 6.5 m ladder stands 2.5 m from a wall. Find its height and check with the 5–12–13 triple.", "A circle gathers all points at one distance from its center and introduces π."),
    },
    "38-circles": {
        "kz": E("Шеңбер және дөңгелек: тұрақты қатынас пен қисықты өлшеу", "Шеңберді дөңгелектен ажыратып, радиус, диаметр, ұзындық пен ауданды байланыстырамыз және π-ді тұрақты қатынас деп түсінеміз.", "Қашықтықты бір нүктеден барлық бірдей қашық нүктеге кеңейтеміз.", "Радиусы 4, диаметрі 8, ұзындығы 8π және ауданы 16π дөңгелек", "Кез келген доңғалақ бір айналымда өз шекарасының ұзындығын жүріп өтеді; оның диаметрге қатынасы тұрақты.", "Шеңбер — шекара, дөңгелек — ішкі аймақпен бірге. `d=2r`, `C=2πr=πd`, `S=πr²`.", "центр → r не d → шекара ма, аудан ба? → π түріндегі дәл жауап → жуық мән және бірлік", "`r=4 см`: `d=8 см`, `C=8π≈25,13 см`, `S=16π≈50,27 см²`.", "`S=2πr` деу қате: бұл шекара ұзындығы; аудан `πr²`.", "Радиусы 3 м гүлзардың айналасында ені 1 м жол бар. Жол ауданын екі дөңгелек айырмасы ретінде табыңыз.", "Шеңбер ішіндегі тікбұрышты үшбұрыштар синус, косинус және тангенске апарады."),
        "en": E("Circles and disks: a constant ratio and measuring a curve", "We distinguish circumference from disk, connect radius, diameter, length, and area, and understand π as a constant ratio.", "Distance from one point now defines an entire curve.", "A disk of radius 4, diameter 8, circumference 8π, and area 16π", "Any wheel travels one circumference per revolution, and circumference divided by diameter is constant.", "A circle is the boundary; a disk includes its interior. `d=2r`, `C=2πr=πd`, and `A=πr²`.", "center → r or d → boundary or area? → exact π form → approximation and units", "For `r=4 cm`, `d=8 cm`, `C=8π≈25.13 cm`, and `A=16π≈50.27 cm²`.", "Writing `A=2πr` is wrong: that measures the boundary; area is `πr²`.", "A circular flower bed has radius 3 m and a 1 m path around it. Find the path area as a difference of disks.", "Right triangles inside circles lead to sine, cosine, and tangent."),
    },
    "39-trigonometry": {
        "kz": E("Тригонометрия: бұрыш қабырғалар қатынасы ретінде", "Синус, косинус және тангенсті тікбұрышты үшбұрыш арқылы анықтап, керекті қатынасты таңдаймыз және жауапты геометриямен тексереміз.", "Ұқсас тікбұрышты үшбұрыштардың тұрақты қатынастарын зерттейміз.", "3–4–5 үшбұрышы: sin α=3/5, cos α=4/5, tan α=3/4", "Жолдың 10% еңісі — көтерілу мен көлденең қашықтық қатынасы. Бір бұрышта бұл қатынас өлшемге тәуелсіз.", "`sin=қарсы катет/гипотенуза`, `cos=іргелес катет/гипотенуза`, `tan=қарсы/іргелес`.", "бұрыш → оған қатысты қабырғалар → белгілі мен белгісізге сай қатынас → теңдеу → бағалау", "3–4–5 үшбұрышында 3-ке қарсы бұрыш үшін `sin=3/5`, `cos=4/5`, `tan=3/4`.", "Гипотенузаны «іргелес катет» деу қате: бұл атау гипотенузаны қамтымайды.", "8 м саты қабырғамен 25° бұрыш жасайды. Биіктік пен қабырғадан қашықтықты тауып, Пифагормен тексеріңіз.", "Вектор ұзындық пен бағытты біріктіріп, орын ауыстыруларды қосуға мүмкіндік береді."),
        "en": E("Trigonometry: an angle as a ratio of sides", "We define sine, cosine, and tangent in a right triangle, choose the needed ratio, and check the answer geometrically.", "We study ratios preserved across similar right triangles.", "A 3–4–5 triangle with sin α=3/5, cos α=4/5, and tan α=3/4", "A 10% road grade is a rise-to-run ratio. The same angle keeps this ratio at every drawing size.", "`sin=opposite/hypotenuse`, `cos=adjacent/hypotenuse`, and `tan=opposite/adjacent`.", "mark angle → name sides relative to it → choose known/unknown ratio → equation → estimate", "In a 3–4–5 triangle, for the angle opposite 3: `sin=3/5`, `cos=4/5`, and `tan=3/4`.", "Calling the hypotenuse the adjacent leg is wrong: “adjacent leg” excludes the hypotenuse.", "An 8 m ladder makes a 25° angle with the wall. Find height and base distance, then check with Pythagoras.", "Vectors combine magnitude and direction so displacements can be added."),
    },
    "40-vectors-geometry": {
        "kz": E("Кеңістіктегі векторлар: ұзындық, бағыт және орын ауыстыруды қосу", "Орын ауыстыруды компоненттермен көрсетіп, векторларды қосамыз, ұзындығын және скаляр көбейтінді арқылы бұрышын тексереміз.", "Нүктенің мекенжайынан нүктелер арасындағы бағытталған ауысуға өтеміз.", "a=(3;4), b=(−1;2), қосындысы (2;6), |a|=5", "«5 метр жүр» деген бұйрық бағытсыз толық емес. Вектор шаманы да, бағытты да сақтайды.", "Векторлар компонент бойынша қосылады. `(x,y)` ұзындығы `√(x²+y²)`. `a·b=|a||b|cosθ`; нөл перпендикулярлықты көрсетеді.", "басы мен соңы → компоненттер → амал → ұзындық → бағыт пен скаляр тексеру", "`a=(3,4)`, `b=(−1,2)`: `a+b=(2,6)`, `|a|=5`, `a·b=5`.", "`(3,4)` ұзындығын `3+4=7` деу қате: перпендикуляр компоненттер үшін Пифагор қолданылады, жауап 5.", "`a=(2;−3;6)`, `b=(1;4;−2)` үшін қосынды, айырма, |a| және скаляр көбейтіндіні табыңыз.", "Қорытынды бақылау дәлел, масштаб, өлшеу, шеңбер, тригонометрия және векторды біріктіреді."),
        "en": E("Vectors in space: magnitude, direction, and adding displacements", "We represent displacement with components, add vectors, find magnitude, and use a dot product to check an angle.", "We move from the address of a point to a directed change between points.", "Vectors a=(3,4) and b=(−1,2), sum (2,6), and |a|=5", "The instruction “walk 5 metres” is incomplete without direction. A vector stores both size and direction.", "Vectors add componentwise. The magnitude of `(x,y)` is `√(x²+y²)`. `a·b=|a||b|cosθ`; zero for nonzero vectors means perpendicular.", "start and end → components → operation → magnitude → direction/dot-product check", "For `a=(3,4)` and `b=(−1,2)`, `a+b=(2,6)`, `|a|=5`, and `a·b=5`.", "Finding the length of `(3,4)` as `3+4=7` is wrong; perpendicular components require Pythagoras, giving 5.", "For `a=(2,−3,6)` and `b=(1,4,−2)`, find sum, difference, |a|, and dot product.", "The checkpoint combines proof, scale, measurement, circles, trigonometry, and vectors."),
    },
    "41-geometry-mastery": {
        "kz": E("Бақылау нүктесі: геометрия және кеңістік", "Он жаңа тапсырма анықтама, дәлел, ұқсастық, өлшеу, тікбұрышты үшбұрыш, шеңбер, тригонометрия және векторды тексереді.", "Бұл геометрия блогының қорытындысы; әр шешімде сызба, шарт, негіз және тексеру болуы керек.", "Геометрияның сегіз тірегі және екі аралықтағы нәтиже", "Сәулетші сызбаны тек әдемі көрінгені үшін қабылдамайды: өлшем, бұрыш, масштаб пен есеп үйлесуі керек.", "Меңгеру — дұрыс теореманы шарттарымен таңдау, себептер тізбегін құру, бірлікті сақтау және тәсілді жаңа жағдайға көшіру.", "сызба → берілген/табу → шартты теорема → есептеу → бірлік → тәуелсіз тексеру", "Бір есепте ұқсастық ұзындықты, Пифагор диагональды, аудан материал көлемін бере алады; әр өту негізделеді.", "Дұрыс формуланы сәйкес емес фигураға қолдану қате. Тік бұрышты, қабырға сәйкестігін және өлшемді алдымен тексеріңіз.", "Он тапсырманы орындаңыз. Әрқайсысында сызба, шешу жолы және тексеру болсын.\n\n1. Вертикаль бұрыштардың бірі 47°. Қалған үшеуін тауып, әр жауапты негіздеңіз.\n2. Теңбүйірлі үшбұрыштың төбе бұрышы 38°. Табан бұрыштарын табыңыз.\n3. △ABC және △DEF үшін AB=DE=6, BC=EF=8 және AC=DF=10 берілген. Олардың теңдігін дәлелдеп, сәйкес төбелерді атаңыз.\n4. 1:200 масштабты жоспарда қабырға 4,6 см. Нақты ұзындық пен ауданның өзгеру коэффициентін табыңыз.\n5. Негізі 9 см, биіктігі 6 см үшбұрыштың ауданын, содан кейін осы негізді биіктігі 5 см призманың көлемін табыңыз.\n6. Тіктөртбұрышты алаңның қабырғалары 9 м және 12 м. Диагоналін тауып, кері есеппен тексеріңіз.\n7. Дөңгелек диаметрі 10 см. Шеңбер ұзындығы мен ауданның дәл мәндерін және жүздікке дейінгі жуық мәндерін табыңыз.\n8. Гипотенуза 14 м, сүйір бұрыш 35°. Екі катетті тауып, Пифагор теоремасымен тексеріңіз.\n9. `a=(4;−2)` және `b=(−1;5)` үшін қосындыны, a ұзындығын және скаляр көбейтіндіні табыңыз.\n10. Қолжетпейтін нысан биіктігін өлшеу тәсілін ұсыныңыз, жорамалдар мен ең үлкен қателік көзін атаңыз.\n\nӨту шарты: 10 тапсырманың кемінде 8-і, соның ішінде 3 не 10-тапсырма орындалуы керек. Жеті күннен кейін өзгертілген нұсқадан кемінде 7/10 алыңыз.", "Келесі блок шек, туынды және интеграл арқылы үздіксіз өзгеріс пен жинақталуды зерттейді."),
        "en": E("Checkpoint: geometry and space", "Ten new problems test definitions, proof, similarity, measurement, right triangles, circles, trigonometry, and vectors.", "This closes the geometry block; every solution needs a diagram, conditions, reasons, and a check.", "Eight supports of geometry and two spaced results", "An architect does not accept a drawing because it looks right: dimensions, angles, scale, and calculations must agree.", "Mastery means choosing a theorem with its conditions, building a chain of reasons, preserving units, and transferring the method.", "diagram → given/seek → theorem with conditions → calculate → units → independent check", "One problem may use similarity for a length, Pythagoras for a diagonal, and area for material; every transition needs a reason.", "Using a correct formula on the wrong figure is an error. Check the right angle, side correspondence, and dimension first.", "Complete ten problems. Include a diagram, reasoning, and a check for each one.\n\n1. One of a pair of vertical angles is 47°. Find the other three and justify every answer.\n2. An isosceles triangle has a vertex angle of 38°. Find both base angles.\n3. In △ABC and △DEF, AB=DE=6, BC=EF=8, and AC=DF=10. Prove congruence and name corresponding vertices.\n4. A wall is 4.6 cm long on a 1:200 plan. Find its real length and the area scale factor.\n5. Find the area of a triangle with base 9 cm and height 6 cm, then the volume of a height-5-cm prism with that base.\n6. A rectangular site has sides 9 m and 12 m. Find its diagonal and check by reversing the calculation.\n7. A disk has diameter 10 cm. Find exact circumference and area, then approximate both to two decimals.\n8. A right triangle has hypotenuse 14 m and an acute angle of 35°. Find both legs and check them with Pythagoras.\n9. For `a=(4,−2)` and `b=(−1,5)`, find their sum, the magnitude of a, and their dot product.\n10. Design a method to measure an inaccessible height; state assumptions and the largest source of error.\n\nPass target: at least 8/10, including problem 3 or 10. After seven days, complete a changed version with a target of at least 7/10.", "The next block studies continuous change and accumulation through limits, derivatives, and integrals."),
    },
}
